### ISSUE TITLE
Keystore configs can only be provided via env variable

### ISSUE THREAD

**Issue by florianrusch-zf** [eclipse-edc/Connector#1106]
# Bug Report

## Describe the Bug
The configurations for the keystore (e.g. `EDC_KEYSTORE` or `EDC_KEYSTORE_PASSWORD`) are only configurable via an environment variable and not via the properties file.

### Expected Behavior
To have possibly just one configuration "storage" it would be nice to allow all configurations been placed into a properties file.

## Steps to Reproduce
You can try to add the `FsVault` module to the `:launchers:basic` module and try to configure the path or the password of the required keystore in the properties file.

## Context Information
- Used version https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/commit/e7929562

**Comment by jimmarino** [comment]
This look like code was removed and changed with various refactorings. The keystore should be pulled from the Vault and not be placed on the filesystem.

**Comment by jimmarino** [comment]
It appears code that properly handled this was removed and changed with various refactorings. Also, any certs will need to be dynamically generated and a Keystore created from the PEM on startup. Keystores should not be statically placed on a file system.

Keystore use also needs to be enabled for the web as the extension does not load keystores. FWIW, this is a significant amount of work to enable in a K8S environment.

**Comment by bearn01d** [comment]
This issue still persists, a fix would be highly appreciated.
