### ISSUE TITLE
System tests: use generated client for DM API

### ISSUE THREAD

**Issue by algattik** [eclipse-edc/Connector#1205]
# Feature Request

The project should include a generated client for the Data Management API, which should be used in system tests (instead of RestAssured).

## Which Areas Would Be Affected?
System tests

## Why Is the Feature Desired?
- Greatly reduce the verbosity, and improve the clarity of system tests
- Ensure the scope of system tests is not integration testing of the controllers, that can be done in specific RestAssured tests
- Provide a client module in Maven that can be directly used by end users running on JVM
- Dogfood our OpenAPI definition

## Solution Proposal
We've had good results with [openapi-generator-maven-plugin](https://github.com/catenax/ItemRelationshipServices/blob/main/irs-client/pom.xml), the [equivalent plugin](https://openapi-generator.tech/docs/plugins/) exists for Gradle.

## Type of Issue
Improvement

## Checklist

- [ ] assigned appropriate label?
- [x] **Do NOT select a milestone or an assignee!**

**Comment by algattik** [comment]
@paullatzelsperger @ndr-brt @bscholtes1A a penny for your thoughts on this :)

**Comment by ndr-brt** [comment]
Having an EDC REST client would be great, I never got the chance to try the openapi generator, but looking forward for that.

**Comment by algattik** [comment]
@paullatzelsperger @ndr-brt @bscholtes1A @zeier I built a quick spike at https://github.com/agera-edc/DataSpaceConnector/pull/249. Happy for your comments and feedback on proposed decision points.

**Comment by algattik** [comment]
https://github.com/agera-edc/DataSpaceConnector/pull/249

## Objectives

- Develop a REST client module with generated code from the OpenAPI definition, and use it in system tests
- Reduce the verbosity, increase the maintainability and improve the clarity of system tests
- Ensure the scope of system tests is not integration testing of the controllers, that can be done in specific RestAssured tests
- Provide a client module in Maven that can be directly used by end users running on JVM
- Dogfood our OpenAPI definition

## Results

- The `org.openapi.generator` [plugin](https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator-gradle-plugin) appears to work reliably as part of the build, and is fast (8 seconds).

- The plugin generates an entire gradle project in the build/ directory. We have the option:
   - Running the plugin manually and committing the files we want, as we are doing for the OpenAPI definition.
   - Run the plugin as part of every build, and simply add the generated `src/main/java` folder to the source set.

  Since the execution is fast, we opted for the latter option here.

- In EDC, we standardise on OkHttpClient and Jackson. The plugin can use various HTTP client libraries and JSON serialisation frameworks. If generating for OkHttpClient, only GSON serialisation can be used. This means that new generated DTO classes must be used on the client side.

  The generated DTO classes are mutable, and are created with this style: `new MyDto().field1(value1).field2(value2)`

  An alternative would be to use the `native` Java `HttpClient` (Java 11+) and Jackson serialisation. We could then reuse the existing DTO classes. We would then have to refactor existing data management API modules to separate DTOs from services into separate packages.

## Decisions

- **Reuse existing DTOs or generate new DTOs?** For quality purposes, my recommendation would be to avoid reusing DTO classes and use generated ones. This ensures that the client behaves exactly and only as specified in the OpenAPI definition, so that the Java client does not have any difference to any other client generated for another language.
- **Commit generated client code, or regenerate on build?** My recommendation would be to regenerate the client on build. This keeps the repo lean, ensures the code is always up to date and does not get manually modified. The time impact is very modest, and should be hardly noticeable in practice thanks to gradle build parallelism and caching.
- **Choice of client library**: My recommendation would be to use the native `HttpClient` rather than `OkHttpClient` to maximise portability and reduce client code size (`OkHttpClient` pulls in Kotlin). Clients who would want the additional advanced features of `OkHttpClient` would anyway be sophisticated enough that having to regenerate their own client from the OpenAPI definitions would hardly be an issue.

**Comment by algattik** [comment]
This is currently blocked by https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/1264

**Comment by ndr-brt** [comment]
@algattik in my opinion this would have been useful, will someone work on it?

**Comment by algattik** [comment]
@ndr-brt work on this would require first #1264 to be resolved
