### ISSUE TITLE
OpenAPI: erroneous definition of Polymorphic types

### ISSUE THREAD

**Issue by algattik** [eclipse-edc/Connector#1264]
Several classes used Jackson patterns that are not compatible with Swagger generator. As a result, the generated OpenAPI definitions provided in YAML are currently invalid.

- `Permission` and `Duty`: Swagger generator does not detect `JsonTypeName` annotations in superclasses. See https://github.com/swagger-api/swagger-core/issues/4181
- `PolicyType` uses custom deserialisation code. This is not compatible with Swagger generator.
- `DataPlaneInstance` and `DataPlaneInstanceImpl`: Missing annotations for Swagger generator to detect JSON inheritance scenario.

Regarding the first point: Below is a sample valid `Policy` payload (note the `permissions[0].edctype` property):

```json
{
  "uid": "f4405262-de43-404c-b94a-358963094361",
  "permissions": [
    {
      "edctype": "dataspaceconnector:permission",
      "uid": null,
      "target": "asset-id",
      "action": {
        "type": "USE",
        "includedIn": null,
        "constraint": null
      },
      "assignee": null,
      "assigner": null,
      "constraints": [],
      "duties": []
    }
  ],
  "prohibitions": [],
  "obligations": [],
  "extensibleProperties": {},
  "inheritsFrom": null,
  "assigner": null,
  "assignee": null,
  "target": null,
  "@type": {
    "@policytype": "set"
  }
}
```

The generated [YAML OpenAPI](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/8561416a1fbeacca21f574aa56e76a071a287e75/resources/openapi/yaml/policydefinition.yaml#L131) definition contains:
```yaml
    Permission:
      type: object
      properties:
        uid:
          type: string
        target:
          type: string
        action:
          $ref: '#/components/schemas/Action'
        assignee:
          type: string
        assigner:
          type: string
        constraints:
          type: array
          items:
            $ref: '#/components/schemas/Constraint'
        duties:
          type: array
          items:
            $ref: '#/components/schemas/Duty'
```

The `Permissions` type does not contain the `edctype` field. As a result, payloads from generated client to the policy creation endpoint fail with a deserialisation error.

```
Could not resolve subtype of [simple type, class org.eclipse.dataspaceconnector.policy.model.Permission]: missing type id property 'edctype' (for POJO property 'permissions')
 at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 1, column: 106] (through reference chain: org.eclipse.dataspaceconnector.policy.model.Policy$Builder["permissions"]->java.util.ArrayList[0])
org.eclipse.dataspaceconnector.client.ApiException: createPolicy call failed with: 400 - Could not resolve subtype of [simple type, class org.eclipse.dataspaceconnector.policy.model.Permission]: missing type id property 'edctype' (for POJO property 'permissions')
 at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 1, column: 106] 
``

**Comment by paullatzelsperger** [comment]
The `Permission` does in fact have the `JsonTypeName` annotation. But in order for that to get serialized, we have to use the `TypeManager` (as it tracks the types).
Seems like we have to hook into the yaml generation somehow.

Did you use an auto-generated (Java) client?

**Comment by algattik** [comment]
Created Swagger generator issue: https://github.com/swagger-api/swagger-core/issues/4181

**Comment by algattik** [comment]
From the OpenAPI spec it seems we need to use type names in the discriminator values, https://swagger.io/specification/ _The expectation now is that a property with name petType MUST be present in the response payload, and the value will correspond to the name of a schema defined in the OAS document._

So that would mean we can't have discriminator names like `dataspaceconnector:permission`.

Here's what I get with a generated client *Could not resolve type id 'dataspaceconnector:permission' as a subtype of org.eclipse.dataspaceconnector.client.models.Permission: known type ids = [Permission] (for POJO property 'permissions')*

**Comment by florianrusch-zf** [comment]
@algattik Was this fixed by the PR @paullatzelsperger has created a few days ago #1448?

**Comment by algattik** [comment]
> @algattik Was this fixed by the PR @paullatzelsperger has created a few days ago #1448?

No, that one covered documentation. Fixing this would require breaking change in the contract

**Comment by paullatzelsperger** [comment]
closing, implicitly fixed with JSON-LD
