### ISSUE TITLE
Update terminology.md

### ISSUE THREAD

**Issue by juliapampus** [eclipse-edc/Connector#1306]

**Comment by jimmarino** [comment]
Hi @juliapampus I'm working on some doc if you want to sync on that,

**Comment by juliapampus** [comment]
@jimmarino I think this would be nice. What areas does this affect? I am currently restructuring the whole directory, see #1307. Just rearranging and providing basic information. So no modification of existing content. If you like, you could take a look: https://fraunhoferisst.github.io/EclipseDataspaceConnector/

**Comment by juliapampus** [comment]
@jimmarino Maybe you also want to take a look at the templates in #1299? Would be nice if you could provide feedback on whether this is useful for aligning documentation.

**Comment by juliapampus** [comment]
Will be addressed with docs automation and the new docs repo.
