### ISSUE TITLE
Add committer guidelines

### ISSUE THREAD

**Issue by juliapampus** [eclipse-edc/Connector#1321]
How to become a committer etc.

**Comment by juliapampus** [comment]
Just created this issue and assigned you as this was already a point in #1138 and you said you are working on that :)

**Comment by florianrusch-zf** [comment]
@juliapampus in my opinion this is still a valid task or not? Then we should remove the stale tag

**Comment by juliapampus** [comment]
Done with https://github.com/eclipse-edc/.github/pull/49
