### ISSUE TITLE
Refactor multiple modules handling JWT generation and validation

### ISSUE THREAD

**Issue by algattik** [eclipse-edc/Connector#1357]
# Feature Request

- Redundant JWT generation and validation logic in common/token-generation-lib (used by OAuth2 module) and identity-did-service/identity-did-crypto
- ids-token-validation extension is not actually working (META-INF folder is misnamed)

## Which Areas Would Be Affected?
Several

## Why Is the Feature Desired?
Allow cross-cutting changes, such as #1176 

## Solution Proposal
- standardise on token-generation-lib / token-validation-lib modules, remove similar logic from identity-did-crypto
- fix ids-token-validation META-INF folder name
- write system test covering ids-token-validation and identity-did-service

## Type of Issue
cleanup, refactoring

## Checklist

- [ ] assigned appropriate label?
- [x] **Do NOT select a milestone or an assignee!**

**Comment by paullatzelsperger** [comment]
I am in favor of cleaning up and making stuff more unified.

**Comment by juliapampus** [comment]
> ids-token-validation extension is not actually working 

Relates to #1274

**Comment by florianrusch-zf** [comment]
@algattik @paullatzelsperger Isn't this still a valid issue?

**Comment by paullatzelsperger** [comment]
@florianrusch-zf it sure is. i'll reopen.
