### ISSUE TITLE
Add missing documentation to modules

### ISSUE THREAD

**Issue by juliapampus** [eclipse-edc/Connector#1382]
# Feature Request

Add missing documentation

## Which Areas Would Be Affected?
almost all modules, however, only markdown files

## Why Is the Feature Desired?
Provide necessary information, stick to templates (`docs/templates`) if possible 

## Solution Proposal
The following modules are missing a markdown file at all or are providing insufficient information. Some submodules are documented, some not - I have not listed them all separately, the list below covers the first level modules. 

I would kindly ask the mentioned people to take a look at "their" modules and submodules, and take care of providing documentation with opening PRs. You may provide a comment if you want to discuss, and leave a tick if you want to mark a task as finished.

Feel free to add general documentation items and missing decision records by creating a new issue or filling the lists in #1138 & #1302.

- [ ] :common:state-machine-lib @ndr-brt @algattik
- [ ] :common:token-generation-lib @bscholtes1A
- [ ] :common:token-validation-lib @bscholtes1A

- [ ] :core:base @jimmarino @paullatzelsperger
- [ ] :core:boot @jimmarino @paullatzelsperger
- [ ] :core:contract @jimmarino @juliapampus @ronjaquensel
- [ ] :core:defaults @paullatzelsperger
- [ ] :core:policy @jimmarino
- [ ] :core:transfer @jimmarino @bscholtes1A @paullatzelsperger @ndr-brt

- [x] :data-protocols:ids @ronjaquensel @juliapampus

- [ ] :extensions:api @ndr-brt @paullatzelsperger
- [ ] :extensions:aws @paullatzelsperger
- [ ] :extensions:azure @paullatzelsperger
- [ ] :extensions:data-plane-selector @paullatzelsperger
- [x] :extensions:data-plane-transfer @bscholtes1A
- [ ] :extensions:dataloading @paullatzelsperger
- [ ] :extensions:filesystem @jimmarino @paullatzelsperger
- [ ] :extensions:http-provisioner @jimmarino @paullatzelsperger
- [ ] :extensions:http-receiver @bscholtes1A
- [ ] :extensions:iam:daps @bscholtes1A
- [ ] :extensions:iam:decentralized-identity @paullatzelsperger
- [ ] :extensions:iam:oauth2 @bscholtes1A @jimmarino
- [ ] :extensions:sql @bcronin90 @denisneuling @paullatzelsperger
- [ ] :extensions:transaction @jimmarino

- [ ] :launchers:data-plane-server @bscholtes1A
- [ ] :launchers:dpf-selector @paullatzelsperger

## Type of Issue
documentation

## Checklist

- [x] assigned appropriate label?
- [x] **Do NOT select a milestone or an assignee!**

**Comment by bscholtes1A** [comment]
`data-plane-transfer` documentation here: https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/pull/1519
