### ISSUE TITLE
Streaming data from provider to consumer

### ISSUE THREAD

**Issue by newinnovations** [eclipse-edc/Connector#1390]
# Feature Request

From the discussion in issue #903 this is a request to implement (kafka) streaming from provider to consumer (and probably vice versa). 

![edc-streaming](https://user-images.githubusercontent.com/8201694/171424927-ceb822c7-2a9e-4681-834e-256cfd8a4765.png)

In this scenario actual data would be transferred to the consumer (instead of to some external/cloud  entity as implemented in the #903 scenario) and would “keep the data streaming“

## Which Areas Would Be Affected?
DPF

## Why Is the Feature Desired?
Many use cases simply involve data sharing between two parties without involving external/cloud resources.

## Solution Proposal
Mentioned by @bscholtes1A in response to my comment in #903 .

## Type of Issue
Improvement in use case.

## Checklist

- [ ] assigned appropriate label?
- [x] **Do NOT select a milestone or an assignee!**

**Comment by jimmarino** [comment]
@bscholtes1A Can we close as completed?

**Comment by jimmarino** [comment]
@bscholtes1A Can we close as completed?
