### ISSUE TITLE
Introduce a comprehensive Usage Control Concept

### ISSUE THREAD

**Issue by sebbader** [eclipse-edc/Connector#1406]
# Feature Request

Establish a general, documented picture of Usage Control and its aspects and characteristics for the EDC.

## Which Areas Would Be Affected?

docs, indirectly the policy engine, contract negotiation, contract objects etc.

## Why Is the Feature Desired?

Currently, various parts and features are implemented or are actively developed that intend to play into the EDC's Usage Control capabilities. However, an overarching idea is missing, making it hard to align the various activities into a comprehensive big picture. In particular, this non-existing concept makes it very challenging to identify blank spots and derive suitable counter measures.

## Solution Proposal

Extend the documentation at /docs/architecture/usage-control/ with appropriate viewpoints

## Type of Issue

improvement

## Checklist

- [ ] Start with a preliminary graphical structure
- [ ] Agree on a general categorisation 
- [ ] Document the single viewpoints
- [ ] Derive change requests and future activities

**Comment by sebbader** [comment]
Parts of the scope for this issue have been started in the discussion #1229.

**Comment by jimmarino** [comment]
Is the request to better document the architecture and relevant implementation pertaining to usage control?

**Comment by juliapampus** [comment]
in progress
