### ISSUE TITLE
Security: Make it possible to store API-Token-Key in Vault (instead of configuration)

### ISSUE THREAD

**Issue by DominikPinsel** [eclipse-edc/Connector#1537]
# Feature Request

At the time of writing the API-Token, for example used to authenticate at the Data Management API, is part of the connector configuration. It would be more secure if this information is moved into the Vault and the configuration only contains an alias.

## Which Areas Would Be Affected?
- `Auth-Tokenbased` Extension

## Why Is the Feature Desired?
- Improve security

## Solution Proposal
- Move auth key from settings to Vault
or
- Add configuration to store auth key in vault, so that it's possible to have the key in settings **or** Vault

## Type of Issue
- enhancement

## Checklist

- [x] assigned appropriate label?
- [x] **Do NOT select a milestone or an assignee!**

<sub>Dominik Pinsel <dominik.pinsel@daimler.com>, Mercedes-Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md) </sub>

**Comment by DominikPinsel** [comment]
> - Add configuration to store auth key in vault, so that it's possible to have the key in settings or Vault

I'd prefer this solution to avoid breaking changes and deprecate the configuration possiblity

**Comment by paullatzelsperger** [comment]
> I'd prefer this solution to avoid breaking changes and deprecate the configuration possiblity

Breaking changes are to be expected until a first final version is released. This was agreed on on numerous occasions.

**Comment by DominikPinsel** [comment]
> > I'd prefer this solution to avoid breaking changes and deprecate the configuration possiblity
> 
> Breaking changes are to be expected until a first final version is released. This was agreed on on numerous occasions.

This is true. But on the other hand there are already people using the EDC. So if it's possible without too much effort, we should  try not to make their EDC work unnecessarily difficult.

**Comment by DominikPinsel** [comment]
@paullatzelsperger would it be fine for you If i work on this issue?

**Comment by DominikPinsel** [comment]
> Yeah, sure. Generally, we don't need the complexity of multiple approaches for the same problem, however being able to supply the API key through config is really useful in testing, and demoing, so we we'll leave that in place. The order of precedence should be Vault -> configuration, auto-generation.

All right. I will add you as a review in the PR :+1:
