### ISSUE TITLE
DID resolver caching

### ISSUE THREAD

**Issue by algattik** [eclipse-edc/Connector#1848]
# Feature Request

Caching implementation for `DidResolver`

## Which Areas Would Be Affected?
IAM DID

## Why Is the Feature Desired?

The implementation for `DidResolver` does not cache downloaded DID Documents. When used in MVD with verifiable credentials, this generates a lot of redundant traffic.

## Solution Proposal
- Cache should be a decorator
- Use weak keys and values for memory management
- Refresh requested values after a customisable timeout (default 1 minute)
- Cache implementation should be generic to be adaptable to other scenarios
- Thread-safe
 
## Type of Issue
improvement

## Checklist

- [ ] assigned appropriate label?
- [x] **Do NOT select a milestone or an assignee!**

**Comment by paullatzelsperger** [comment]
this could be yet another area where an overarching caching framework could be useful. Related #1173
