### ISSUE TITLE
Typo + cardinality in documentation of domain model

### ISSUE THREAD

**Issue by BirgitBoss** [eclipse-edc/Connector#1957]
# Bug Report

## Describe the Bug
(https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/docs/developer/architecture/diagrams/domain-model.png)
Typo: permitions ==> permissions  for Policy

+ add text making clear that more than one policy can be part of the contract definition (written in text, but in figure it is not clear)

**Comment by jimmarino** [comment]
Thanks for filing this. This diagram is out-of-date and probably should be replaced by just referencing the code (or generating a UML diagram from some tool).

To be precise, a `ContractDefinition` does not contain a multiplicity of policies, it references exactly two policies, an access control policy and a contract policy (this is noted in the class attributes in the diagram).

**Comment by BirgitBoss** [comment]
Next time I will label it correctly, thank you!

It would be a pity to remove the diagram, it was showing exactly the dependencies I was looking for. But perhaps a link to a specification with such a diagram would be good as well.
