### ISSUE TITLE
Feature: implement explicit index queries on arrays in Postgres stores 

### ISSUE THREAD

**Issue by wolf4ood** [eclipse-edc/Connector#2010]
# Feature Request

Support explicit indexes when querying arrays in Postgres stores. 
The current behavior throws an exception on failed do find the mapping.

For now the `collectionIndexQuery` flags in all base tests is disabled in all PG tests

## Which Areas Would Be Affected?

All Postgres stores.

## Why Is the Feature Desired?

To achieve feature parity with InMemory and ComosDB stores.

## Solution Proposal

The query in case of an exact index on a collection should be rewritten using the `->` operator with works on the collection field
by providing in the right operand the index of the element we are interested in.

## Type of Issue
_i.e., new feature, improvement, cleanup, etc._

## Checklist

- [x] assigned appropriate label?
- [x] **Do NOT select a milestone or an assignee!**

**Comment by ndr-brt** [comment]
This was already solved by https://github.com/eclipse-edc/Connector/pull/3330
