### ISSUE TITLE
ids: token of response not validated

### ISSUE THREAD

**Issue by ronjaquensel** [eclipse-edc/Connector#2039]
# Feature Request

When processing the response to a request, the identity token is not checked. Thus, responses with an invalid token are accepted, even though the issuer of the response cannot be verified. Therefore, the token should be validated before any further processing of the response.

## Which Areas Would Be Affected?
`ids-api-multipart-dispatcher-v1`

## Why Is the Feature Desired?
To ensure that the response was sent by a valid data space participant.

## Solution Proposal
Validate the response token in `IdsMultipartSender` right after the response content has been parsed.

## Type of Issue
improvement

## Checklist

- [x] assigned appropriate label?
- [x] **Do NOT select a milestone or an assignee!**

**Comment by jimmarino** [comment]
@ronjaquensel Does this mean that the client which connects via HTTPS validates a token sent by the endpoint? Why would it need to do that if transport-level security is enabled via HTTPS?

**Comment by ronjaquensel** [comment]
@jimmarino the token gives information about whether or not the connector is operated by a valid dataspace participant. It could be that a connector provides a valid SSL certificate, but is not operated by a member of a dataspace, right? In that case, the communication should not be established, as anyone could request data then.

**Comment by dileep-ramachandrarao** [comment]
I would be interested to work on this issue, but unable to assign it to myself. Would be helpful if someone assigns it to me.

**Comment by jimmarino** [comment]
> @jimmarino the token gives information about whether or not the connector is operated by a valid dataspace participant. It could be that a connector provides a valid SSL certificate, but is not operated by a member of a dataspace, right? In that case, the communication should not be established, as anyone could request data then.

Picking this back up. I don't understand why this needs to be done. I also think we are mixing several concepts together:

1. Whether a participant is a valid member of a dataspace is determined by a verifiable presentation defined by whatever identity system is adopted by the dataspace. This is distinct from an SSL certificate.

2. Validating the verifiable presentation of a provider should be done out-of-band before the request is made for a contract agreement or asset. 
  
3. The JDK URLConnection implementation will verify the validity SSL certificate, which is distinct from an identity token.

**Comment by dileep-ramachandrarao** [comment]
In my opinion, I think @ronjaquensel is mentioning about the ids:token that is embedded in the [response to a IDS multipart request message](https://github.com/eclipse-edc/Connector/blob/main/data-protocols/ids/ids-api-multipart-dispatcher-v1/src/main/java/org/eclipse/edc/protocol/ids/api/multipart/dispatcher/sender/IdsMultipartSender.java#L163).
This ids:token is not being validated against [IDS rules](https://github.com/eclipse-edc/Connector/blob/main/data-protocols/ids/ids-token-validation/src/main/java/org/eclipse/edc/protocol/ids/token/validation/rule/IdsValidationRule.java#L55)
If the ids:token(DAT token from DAPS) is still part of the response message, then it needs to be validated.
In such a case, I suppose this is different to the verification of a participant's verifiable presentation? Please let me know if the payload of a response message contains ids:token?

**Comment by ndr-brt** [comment]
Closing as we decide to remove the token from the response: https://github.com/eclipse-edc/Connector/issues/2345
