### ISSUE TITLE
Make communication between components extensible

### ISSUE THREAD

**Issue by paullatzelsperger** [eclipse-edc/Connector#2081]
# Feature Request

For the purposes of this issue let's define the term `component` as a synonym for the somewhat loaded term "microservice". By it we refer to deployment units such as the `control-plane`, the `data-plane`, or the `data-plane-selector` or the `federated-catalog`.

Communication between these is now always HTTP/REST, but there may be installations that prefer decoupling the components further by using some sort of event-based messaging system.

For example, a `DataFlowRequest` could be published as outgoing Kafka Topic instead of being sent as HTTP POST.

Users should be able to contribute their favourite communication binding using extensions.

## Which Areas Would Be Affected?
APIs of various components

## Why Is the Feature Desired?
It should be possible to send the same messages (DTOs) over various transport mechanisms such as HTTP/REST, RabbitMQ, Kafka, etc. The only thing that changes is the client implementation and the "server" implementation.

## Solution Proposal
_should be provided in the form of an Architecture Decision Record_

## Type of Issue
story / enhancement

## Checklist

- [x] assigned appropriate label?
- [x] **Do NOT select a milestone or an assignee!**

**Comment by jimmarino** [comment]
Do we need this level of complexity? Abstracting all possible transports will get difficult very quickly. 

Let's keep things simple by stating that if people want this level of flexibility, they should implement their own `DataFlowController`.

**Comment by paullatzelsperger** [comment]
OK, maybe the term `abstract` is a bit misleading, because I did not mean to introduce another level of type abstraction, but rather the possibility to exchange one particular _binding_ (HTTP) with another.
