### ISSUE TITLE
Cleanup: remove old `GET` endpoints from DataManagement API

### ISSUE THREAD

**Issue by paullatzelsperger** [eclipse-edc/Connector#2088]
# Feature Request

In #2084 we provided `POST` endpoints for querying all the various data management APIs, so once that has received widespread adoption, we should remove:
- all the deprecated `@GET` endpoints 
- `QuerySpecDto.getFilter` and `QuerySpecDto.Builder.filter(String)`
- `QuerySpec.Builder.filter(String)`

## Which Areas Would Be Affected?
data management API

## Why Is the Feature Desired?
remove deprecated code

## Solution Proposal
.

## Type of Issue
cleanup

## Checklist

- [ ] assigned appropriate label?
- [x] **Do NOT select a milestone or an assignee!**

**Comment by ndr-brt** [comment]
To be done after milestone 7 release

**Comment by paullatzelsperger** [comment]
> To be done after milestone 7 release

that is why it's in the backlog. we don't have a Milestone 8 yet

**Comment by janpmeyer** [comment]
@paullatzelsperger 

It looks like all APIs will be created new. Is this ticket still needed or can it be closed?

**Comment by paullatzelsperger** [comment]
@janpmeyer we cannot close this, as not all APIs will be created anew, only Asset, PolicyDef and Catalog, and even then, there will be a transitional period where we need to maintain both.

**Comment by paullatzelsperger** [comment]
turns out the new Dataspace Protocol will indeed bring a whole new Management API relying on JSON-LD, so this issue has become obsolete
