### ISSUE TITLE
Missing JsonPropertyName in Prohibition Class

### ISSUE THREAD

**Issue by maximilianschmidt-zf** [eclipse-edc/Connector#2117]
# Bug Report
While I was going through the Policy Code of the EDC I saw that the JsonPropertyName in
the class Prohibition is missing, is it not required or just missing? - see picture:

![image](https://user-images.githubusercontent.com/104348964/196954767-db1b76b5-30b9-4e0d-a7c3-5f18c2e3b8bc.png)

Greetings and thanks in advance!

**Comment by jimmarino** [comment]
Hi, do you mean a missing @JsonTypeName? That could be an oversight on my part. PRs are welcome, and if you are interested, there are tests that verify de/serialization of other policy types that could be used as a guidepost for one. If you have questions, please let me know.

**Comment by paullatzelsperger** [comment]
Will close, since we're using JSON-LD now
