### ISSUE TITLE
Secure communication between components

### ISSUE THREAD

**Issue by wolf4ood** [eclipse-edc/Connector#2138]
# Feature Request

Some components of a connector can be split in multiple machine and they communicate for now 
via Rest API (eg. Remote DPF).  Those communications are mostly without authentication mechanism since they are not supposed
to be exposed publicly. Though it would be nice to be able to configure the authentication between components, which should be separated for the current Auth mechanism for the public APIs

## Which Areas Would Be Affected?
All Internal Controller and clients calls

## Why Is the Feature Desired?
To have a secure communication between components

## Solution Proposed

probably it should be provided in the form of an Architecture Decision Record

## Type of Issue
new feature, improvement

**Comment by paullatzelsperger** [comment]
relates/duplicates #839
