### ISSUE TITLE
Documentation: Publish OpenAPI Spec to Swaggerhub in CI

### ISSUE THREAD

**Issue by paullatzelsperger** [eclipse-edc/Connector#2163]
# Feature Request

In addition to publishing the `openapi.yaml` file in our code base we should give users a way to inspect the API definition visually, i.e. on a pretty website.

We'll thus publish the `openapi.yaml` file to SwaggerHub. An example of how this could look like can be found [here](https://app.swaggerhub.com/apis/beardyinc/edc-rest_api/0.0.1-SNAPSHOT). For this, I manually uploaded the file, but this can be automated through CI.

We should then link to the resulting swagger hub page from our documentation.

## Important notes
- We need to create an EDC account with Swaggerhub. @mspiekermann is that something you could help out with?
- Once we have an always-on MVD deployment, we could have the SwaggerHub page point to it in its `server` property, i.e. users can try out the the DataManagement API live.

## Which Areas Would Be Affected?
Documentation, CI workflows

## Why Is the Feature Desired?
Documentation, visually inspecting the API.

## Solution Proposal
- add a CI job that publishes the `openapi.yaml` to SwaggerHub
- add a link to our documentation pointing to the generated website

## Type of Issue
improvement

**Comment by mspiekermann** [comment]
I'll check and take care of creating the account
