### ISSUE TITLE
Return a `Result` from `ContractValidationService.validateAgreement()`

### ISSUE THREAD

**Issue by ronjaquensel** [eclipse-edc/Connector#2211]
# Feature Request

The `ContractValidationService's` `validateAgreement()` method currently returns only a boolean. Instead, it should return a result to be able to return the reason for a valiation failure.

## Which Areas Would Be Affected?
`core`

## Why Is the Feature Desired?
In #2204 the validation of the agreement was added to the `TransferProcessService`, where it is called in a chain of operations. Not having any error messages returned if the validation fails makes it hard for users to understand why a transfer could not be initiated.

**Comment by juliapampus** [comment]
Corrresponding task: write (or rewrite, depends on what currently exists) corresponding unit tests for the ValidationService, which then check which error messages/results are returned if something fails during the validation of the agreement. The goal of the change is to get the corresponding information out as a user.
