### ISSUE TITLE
Leverage null-checks of not nullable objects to managers

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-edc/Connector#2225]
# Feature Request

Currently we don't ensure on the `ContractNegotiation`/`TransferProcess` managers that objects that actually are mandatory for the process, e.g. the `policy` for a `TransferProcess` cannot be null, however now the collaborators (like the `manifestGenerator`) have to check the objects passed.
This seems to be overkill, we must ensure at the manager level that the objects retrieved from the database are valid and processable, otherwise the negotiation/transfer must fail with a fatal error.

## Which Areas Would Be Affected?
managers: contract and transfer

## Why Is the Feature Desired?
refactoring

## Solution Proposal
-

**Comment by lanthoor** [comment]
Hello @ndr-brt, I would like to contribute to this issue. Could you assign this to me, please?

**Comment by ndr-brt** [comment]
hey, thank you! I can't do that, because you're not part of the contributors team, I will assign to myself as a placeholder

**Comment by lanthoor** [comment]
@ndr-brt are there any schema definitions for `ContractNegotiation` or `TransferProcess` that I can check to find out all non-null elements?

**Comment by lanthoor** [comment]
As I understood this issue, it has two parts.
1. Ensure null checks are present in the two `Manager` implementations.
2. Remove the null checks from the collaborators.

To implement this, I would need to know,
- what are the mandatory non-null elements within `ContractNegotiation` and `TransferProcess`
- who all are the collaborators

Is there a document of some sort that describes these or do I have to scan through the code to figure it out?

**Comment by ndr-brt** [comment]
> As I understood this issue, it has two parts.
> 
> 1. Ensure null checks are present in the two `Manager` implementations.
> 2. Remove the null checks from the collaborators.
> 
> To implement this, I would need to know,
> 
> * what are the mandatory non-null elements within `ContractNegotiation` and `TransferProcess`
> * who all are the collaborators
> 
> Is there a document of some sort that describes these or do I have to scan through the code to figure it out?

The code is the document :)
The mandatory non-nullable elements are listed in the respective `Builder.build()` method.
The collaborators are the `Manager`s collaborators.

**Comment by lanthoor** [comment]
@ndr-brt Would you be willing to take a loot at an early draft, please? Just to ensure I'm not deviating from the requirements.

**Comment by ndr-brt** [comment]
> @ndr-brt Would you be willing to take a loot at an early draft, please? Just to ensure I'm not deviating from the requirements.

please reach me on discord, `ndr_brt` is my id

**Comment by lanthoor** [comment]
> > @ndr-brt Would you be willing to take a loot at an early draft, please? Just to ensure I'm not deviating from the requirements.
> 
> please reach me on discord, `ndr_brt` is my id

Unfortunately, I cannot use discord due to organization policies. I've raised a draft PR. Would it be sufficient?
