### ISSUE TITLE
Register embedded data-plane for sync transfer by default

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-edc/Connector#2226]
# Feature Request

Currently, if I build a connector with an embedded data-plane and I try to start a sync transfer using the `data-plane-transfer-sync` method I get:
```
SEVERE 2022-11-22T12:44:06.053856037 TransferProcessManager: Fatal error initiating data transfer: b7e01ab2-7a3d-4c32-8517-62a0f1be43d7. Error details: Failed to resolve proxy url for data request 70e0eea3-2ac3-4107-a456-1aa3e972de5e  Failed to find DataPlaneInstance for proxying data from source: HttpData
```

But if the data-plane is embedded, it should be retrieved by default (like how it's done in the `data-plane-transfer-client`)

## Which Areas Would Be Affected?
transfer

## Why Is the Feature Desired?
simplify test environments and samples

## Solution Proposal
the `DataPlaneTransferSyncExtension` should check if a data-plane instance is defined in the same runtime, if so, it could provide an `EmbeddedDataPlaneTransferProxyResolve` that returns the url of the embedded `/public` endpoint

**Comment by bscholtes1A** [comment]
This was removed here: https://github.com/eclipse-edc/Connector/pull/2321 as it was breaking the Eona-X use-case.  I do not think that hardcoding the public API url is a good option.

**Comment by zub4t** [comment]
Seems like something that I could handle,  Can you assign this one to me ?  @ndr-brt 😊

**Comment by ndr-brt** [comment]
I think it could still have sense, as it is still open. I assigned it to you @zub4t

**Comment by ndr-brt** [comment]
this is provided out of the box from the data plane signaling feature
