### ISSUE TITLE
Make `EndpointDataReferenceReceiverRegistry` return error if no receivers are registered

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-edc/Connector#2228]
# Feature Request

Currently, if no receivers are registered on `EndpointDataReferenceReceiverRegistry`, the transfer process is set to `COMPLETE` but without sending any EDR.
The TransferProcess should fail because at that point data could not be retrieved.

## Which Areas Would Be Affected?
transfer

## Why Is the Feature Desired?
improvement

## Solution Proposal
-

**Comment by juliapampus** [comment]
@majadlymhmd will take care
