### ISSUE TITLE
Rename `http-receiver` extension

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-edc/Connector#2229]
# Feature Request

The `http-receiver` is not really self-explainatory, it could be renamed to `data-plane-transfer-sync-http-edr` or something like this. Maybe it's too verbose, but I was wondering if we need that `data-plane` prefix on the `data-plane-transfer-*` extensions.

## Which Areas Would Be Affected?
extensions

## Why Is the Feature Desired?
comprehensiveness

## Solution Proposal
-

**Comment by bscholtes1A** [comment]
maybe `dpf-transfer` instead of `data-plane-transfer`?
Would shorten a bit...

**Comment by ndr-brt** [comment]
to be honest, I don't think data-plane should be mentioned, it's misleading, building a control-plane but defining `data-plane` (or `dpf` ) dependencies on it... at the end we're talking about providing transfer capabilities to the control plane.
I'd propose:
- `data-plane-transfer-client` -> `transfer-client`
- `data-plane-transfer-sync` -> `transfer-sync`
- `http-receiver` -> `transfer-sync-http-edr-receiver`

**Comment by jimmarino** [comment]
+1. `transfer-sync-http-edr-receiver` is also verbose. How about `transfer-sync-receiver`?
