### ISSUE TITLE
`Trigger-Snapshot` ci job is triggered from all the forks

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-edc/Connector#2256]
# Bug Report

## Describe the Bug
`Trigger-Snapshot` ci job is triggered from all the forks, but it should be triggered only from the `main` branch of the [Connector](https://github.com/eclipse-edc/Connector) repository.

### Expected Behavior
To not have the build triggered by other forks

### Observed Behavior
-

## Steps to Reproduce
-

## Context Information
-

## Detailed Description
-

## Possible Implementation
Make the workflow enable only on upstream `Connector` repository

**Comment by paullatzelsperger** [comment]
as a solution proposal we could add a job to check for the presence of the `EF_JENKINS_[USER|TOKEN|` credential, and only run the trigger job if that is present.
