### ISSUE TITLE
Add support for dynamic HTTP Receiver callback endpoints

### ISSUE THREAD

**Issue by florianrusch-zf** [eclipse-edc/Connector#2265]
# Feature Request

We have the use-case to have multiple client applications on consumer side which will fetch data through the EDC via the HttpProxy method. These are separate application with different use-case based on different data etc. Therefor, they mostly don't know anything about each other.

As far as I know (please correct me if I'm wrong!) we just have the possibility to configure only one specific URL on the EDC (config property `edc.receiver.http.endpoint`) where the information about the DataPlane access (`EndpointDataReference`) will be sent to. This is fine if we have just one client application which is using the EDC.

With having multiple client applications which are independent, we would need the possibility to somehow define the URL where the `EndpointDataReference` (EDR) object will be sent to.

For example:
- Application A wants to get the access to the data, send the `EDR` object to: `https://app-a:8080/callback`
- Application B wants to get the access to the data, send the `EDR` object to: `https://app-b:8080/callback`
- ...

## Which Areas Would Be Affected?
DPF

## Why Is the Feature Desired?
Already described above

## Solution Proposal
One idea could be, that every time a `TransferProcess` will be created by the client, we configure in the `TransferProcessDto` object the URL where the EDC should send the `EDR` to.

But I'm not so deep into this topic, maybe there are better ways to make this dynamically configurable by the client application.

**Comment by jimmarino** [comment]
This sounds like a fanout scenario. Can you detail the concrete scenario and use case behind this? Thx.

**Comment by florianrusch-zf** [comment]
@jimmarino I tried to improve it. Can you have a look at it again? :-)

\cc @ndr-brt

**Comment by jimmarino** [comment]
OK, thanks, this is not a fan-out but support for dynamic callback addresses. When initiating a request, the client can specify an optional callback address. 

I'm going to ask @wolf4ood to take a look.

**Comment by jimmarino** [comment]
Maybe we should rename this to, "Add support for dynamic HTTP Receiver callback endpoints? Registration sounds as if it is done upfront where what we want is request-time behavior.

**Comment by wolf4ood** [comment]
Hi @florianrusch-zf  
I' m working on this [PR](https://github.com/eclipse-edc/Connector/pull/2276) which basically creates a new module for handling dynamic http receiver based on custom properties on TransferProcessDTO.

It's still on draft cause it needs some docs, in case if you have feedback you can check it out 

Thanks
