### ISSUE TITLE
PooledDataSourceConnection sometimes not returning Connections back to the ConnectionPool

### ISSUE THREAD

**Issue by efiege** [eclipse-edc/Connector#2286]
# Bug Report

## Describe the Bug
We have observed that after some time the `PolicyDefinitionApiController` won't return `Policies` anymore. When the `getAllPolicies` method of the controller is called, the EDC waits forever. 

After investigating the issue we found that all connections of the `GenericObjectPool` where taken and not returned back. The EDC gets stuck at this line: https://github.com/eclipse-edc/Connector/blob/c2bc86f0e4eafbf925e145b69ef5de9d3cd0a359/extensions/common/sql/sql-pool/sql-pool-apache-commons/src/main/java/org/eclipse/edc/sql/pool/commons/CommonsConnectionPool.java#L66 and never reaches the catch-block, as all Connections are already taken and not returned to the `GenericObjectPool`.

### Expected Behavior
`PooledDataSourceConnection` always returning Connections or `CommonsConnectionPool` releasing Connections after some time.

### Observed Behavior
Threads waiting forever for a new Connection.

## Steps to Reproduce
To this point we weren't able to reproduce the issue locally.

## Context Information
- Postgres and EDC hosted in Azure
- Using default connection pool settings
  - minIdleConnections: 1
  - maxIdleConnections: 4
  - maxTotalConnections: 8

## Detailed Description
`getStatsString` from the `GenericObjectPool`:
`activeTimes=[68, 51, 49, 48, 51, 48, 572, 131, 53, 51, 46, 49, 53, 119, 127, 116, 125, 56, 54, 56, 47, 48, 47, 46, 47, 47, 49, 52, 49, 47, 50, 47, 49, 49, 50, 48, 48, 46, 47, 48, 51, 47, 48, 47, 47, 95434970, 112, 123, 108, 129, 122, 127, 48, 49, 47, 49, 51, 47, 46, 51, 48, 107, 122, 110, 124, 50, 48, 46, 47, 111, 124], blockWhenExhausted=true, borrowedCount=79, closed=false, createdCount=8, destroyedByBorrowValidationCount=0, destroyedByEvictorCount=0, evictorShutdownTimeoutDuration=PT10S, fairness=false, idleTimes=[30, 142598, 183484, 630982, 183245, 611874, 41764, 15, 16, 30, 9872, 259748, 99866, 10415, 27686, 15, 15, 31, 16, 15, 31, 551836, 10083, 215851, 1572925, 21025, 37442, 14427, 1106441, 18414, 11314608, 4449, 20980, 1334669, 2607, 4832836, 3785, 2872, 57479555, 2087, 1741692, 5692, 2429842, 4907689, 3674, 1777048, 5342593, 5662, 15, 15, 15, 40565, 15, 15, 31, 15, 15, 29, 583269, 334157, 4496, 1496561, 6809, 85024, 436618, 2243, 12166, 15, 14, 30, 15, 15, 30, 5279537, 55971689, 66331, 33003, 15, 15], lifo=true, maxBorrowWaitDuration=PT0.466S, maxTotal=8, maxWaitDuration=PT-0.001S, minEvictableIdleDuration=PT30M, numTestsPerEvictionRun=3, returnedCount=71, softMinEvictableIdleDuration=PT-0.001S, testOnBorrow=true, testOnCreate=true, testOnReturn=true, testWhileIdle=false, durationBetweenEvictionRuns=PT-0.001S, waitTimes=[466, 15, 15, 16, 16, 15, 16, 15, 15, 383, 15, 15, 15, 16, 15, 15, 15, 464, 16, 15, 415, 20, 17, 15, 16, 15, 15, 16, 15, 16, 15, 15, 16, 15, 15, 16, 15, 15, 15, 15, 15, 16, 15, 15, 16, 16, 16, 15, 14, 16, 15, 15, 16, 15, 450, 16, 16, 423, 17, 15, 15, 20, 15, 15, 16, 15, 15, 14, 14, 450, 15, 15, 414, 16, 16, 15, 16, 15, 15], createdCount=8, makeObjectCount=0, maxIdle=4, minIdle=1`

**Comment by jimmarino** [comment]
This is strange because all connector code that accesses a data source connection should do so within a transactional block submitted to `TransactionContext`. In the case of a commit or rollback, the underlying resources should be released, which should return the connection to the pool.

There could be a few possibilities:

1. There is an EDC code path that results in the connection not being closed (and the object pool wrapper not returning the underlying connection to the pool).

2. Extension code in the EDC runtime you are using that does not properly commit or rollback the transaction context

3. A problem with the underlying object pool. For example, are exceptions being thrown during a JDBC operation that invalidates the connection, causing it to be evicted from the pool and the pool not creating a replacement?

Based on this, I have a few questions:

1. What is the exact EDC configuration you are running? Which extensions are loaded? Are there non-EDC custom extensions that use JDBC connections loaded?

2. What sequence is used to trigger this issue? Are JDBC errors being logged during these operations?

3. What happens if you execute many simultaneous requests against a single REST endpoint (if the sequence in Step 2 involved different endpoints)?

**Comment by ndr-brt** [comment]
It could be something related to the new "streaming" functionalities, because now, when a `getAll` call is done, the client needs to close the stream explicitly to close the underlying connection. (ref. https://github.com/eclipse-edc/Connector/tree/main/docs/developer/decision-records/2022-09-29-sql-query-streaming)

We should ensure that we're not leaving any connection open.

**Comment by efiege** [comment]
> What is the exact EDC configuration you are running? Which extensions are loaded? Are there non-EDC custom extensions that use JDBC connections loaded?

In this setup the Control-Plane still uses the M5-extensions:sql dependency (we are working on migrating to M7) and a flyway extension.

> What sequence is used to trigger this issue?

There is no special sequence that we noticed. Assets, Policies and ContractDefinitions have been created using the data-dashboard. Furthermore the data-dashboard has been used to retrieve all available Assets / Policies / ContractDefinitions multiple times. The Catalog is queried using the `catalog?providerUrl=` endpoint and there is a policy rejecting the access:
`Access not granted for contract-definition:  Permission constraints: [Constraint POLICY_EVALUATION_TIME' GT 2022-11-13T23:00:00.000Z',Constraint POLICY_EVALUATION_TIME' LT 2022-11-20T23:00:00.000Z']`

> Are JDBC errors being logged during these operations?

We haven't seen any errors.

> What happens if you execute many simultaneous requests against a single REST endpoint (if the sequence in Step 2 involved different endpoints)?

All other endpoints are responding like expected, even when a lot of requests are sent in parallel.

**Comment by jimmarino** [comment]
@ndr-brt  Why is the data source connection registered with a `Doorkeeper`? The connection is registered as a transaction resource and will be closed when the transaction commits or is rolled back?

**Comment by ndr-brt** [comment]
> @ndr-brt Why is the data source connection registered with a `Doorkeeper`? The connection is registered as a transaction resource and will be closed when the transaction commits or is rolled back?

Actually not, the transaction must be closed explicitly, before introducing the streaming feature it was pretty much closed by instantiating it into a try-with-resource block, sometimes, when the connection is used for more than a query it was closed manually.
Introducing streaming caused the try-with-resource to close connections before the streaming was actually consumed, so it is necessary to close it explicitly when it is consumed. This is well documented.
The `DoorKeeper` is a custom component that takes care of closing `ResultSet` and `Session` every time, while `Connection` only if it is required to.

**Comment by jimmarino** [comment]
In the transaction framework, the underlying pooled connection will be wrapped. With local transactions, this is done with `ConnectionWrapper`, while in JTA transactions, the transaction manager implementation will do this. In both cases, calling close() on the connection wrapper will do nothing. When the transaction completes, the transaction manager (e.g. `LocalTransactionContext`) will free the underlying pooled connection.

With local transactions, as long as the Strem is opened from within a transaction block and `LocalDataSourceRegistry` is used, the connection will be closed. I don't think the DoorKeeper is needed to manage connections. Should we discuss?

**Comment by efiege** [comment]
Additional information: I have had a similiar problem regarding DataplaneInstances locally (not 100% sure if it was the same). I noticed that I had a wrong configuration, where two connector's where using the same database.

Regarding this issue it is maybe possible, that two similiar configured Control-Planes haven been using the same database.

**Comment by ndr-brt** [comment]
@efiege just for the record, did you added a `TransactionContext` implementation (like `local` or `atomikos`)? Or are you dealing with the `noop` default implementation? (That should print a warning log at the startup)

**Comment by efiege** [comment]
We are using the transaction-local-Extension:
`Started Local Transaction`

**Comment by ndr-brt** [comment]
@jimmarino This bug was reported on Catena-X 0.1.2, that uses the EDC nightly build 20220922, so before the introduction of the [stream over sql](https://github.com/eclipse-edc/Connector/pull/2041), so I guess the problem must be hidden somewhere else.

**Comment by ndr-brt** [comment]
seems like `findById` and `findAll` aren't executing the sql code inside a Transaction Block, not sure this is the issue but could be something related

**Comment by SebastianOpriel** [comment]
Just for documentation: Today we faced a similar issue with another EDC instance based on MS8. We hope, that the problem will magically be solved by the PR in MS9.

**Comment by ndr-brt** [comment]
> Just for documentation: Today we faced a similar issue with another EDC instance based on MS8. We hope, that the problem will magically be solved by the PR in MS9.

the bug was fixed after milestone-8 release, anyway you can test it with any nightly release published after Feb 21th, just to avoid surprises after the M9 release
