### ISSUE TITLE
`CommandHandler` does not report validation errors to `CommandRunner`

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-edc/Connector#2340]
# Feature Request

Currently some `CommandHandler`s intentionally throw exceptions to notify validation errors, that are catched by the `CommandRunner`. This makes the error detection harder, because all the errors are seen as unexpected.

## Which Areas Would Be Affected?
command handlers/runners

## Why Is the Feature Desired?
improve error reporting

## Solution Proposal
make `CommandHandler.handle` return a `Result` and make the `CommandRunner` evaluate it, the result would then be returned to the caller (`CommandProcessor`) and logged accordingly.

**Comment by paullatzelsperger** [comment]
is this really a `good first issue`? it touches core elements of the code base and would require a D-R IMO...

**Comment by ndr-brt** [comment]
> is this really a `good first issue`? it touches core elements of the code base and would require a D-R IMO...

it's not a big deal, we forgot to return that `Result` to the `CommandRunner`, it's just a matter to doing it, I don't think it deserves a decision record because it's pretty straightforward change that will make that part adhere to the convention, not a new feature

**Comment by paullatzelsperger** [comment]
I just thought that especially new contributors should provide a written outline _before_ touching code, because we've seen time and again that this would highlight short-comings soon and without spending much time.

**Comment by paullatzelsperger** [comment]
FYI i put this on `Backlog` to avoid it getting stale again

**Comment by ndr-brt** [comment]
this has been already solved at some point
