### ISSUE TITLE
Avoid dependabot version catalog update PRs

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-edc/Connector#2343]
# Feature Request

Everyday we receive a PR from dependabot proposing a new version for the `version-catalog`, that's pretty annoying.

## Which Areas Would Be Affected?
build

## Why Is the Feature Desired?
-

## Solution Proposal
Maybe putting the version as variable in `gradle.properties` will stop it.

**Comment by paullatzelsperger** [comment]
another option would be to either [exclude certain dependencies](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#ignore) (i.e. the version catalog) or generally ignore `-SNAPSHOT` versions (check [here](https://github.blog/changelog/2021-05-21-dependabot-version-updates-can-now-ignore-major-minor-patch-releases/))

**Comment by ndr-brt** [comment]
Seems like the solution provided with https://github.com/eclipse-edc/Connector/pull/2435 is not working
