### ISSUE TITLE
Misleading Error Message when deleting Asset 

### ISSUE THREAD

**Issue by reisman234** [eclipse-edc/Connector#2344]
# Bug

## Describe the Bug
After some testing with the API of the edc, Creating Asset, Policy and Contract Definition and afterwards the negotiation and transfer part.  I wanted to delete the Asset again, because it has an old DataAdress. 
After doing everything backwards, the deletion of the asset fails with an `409 Conflict Error` and with following Message
```
[
    {
        "message": "Object of type Asset already exists with ID = demo-asset-1",
        "type": "ObjectExists",
        "path": null,
        "invalidValue": null
    }
]
```
W.r.t. my action "Delete the Asset", this message is misleading.  

### Expected Behavior

Delete the asset or provide a more detailed error message (e.g. cannot delete because of ...)

### Observed Behavior

I debugged the code and figured out, that it already should throw/provide a more specific error message. The execution returns this `ServiceResult` in the `AssetServiceImpl.java` , but instead it shows the message from an `ObjectExistsExecption` .

```
try (var negotiationsOnAsset = contractNegotiationStore.queryNegotiations(query)) {
    if (negotiationsOnAsset.findAny().isPresent()) {
        return ServiceResult.conflict(format("Asset %s cannot be deleted as it is referenced by at least one contract agreement", assetId));
    }
}
```

**Comment by wolf4ood** [comment]
Hi @reisman234 
thanks for raising this issue indeed the detail of the response is too generic and can be improved.

**Comment by ndr-brt** [comment]
Thanks for the issue, definitely not a bug
