### ISSUE TITLE
Edit typo in readme

### ISSUE THREAD

**Issue by jes14** [eclipse-edc/Connector#2392]
# Feature Request
In the readme, the text file name is different.

## Which Areas Would Be Affected?
to improve documentation

## Why Is the Feature Desired?
The title is different than expected.

## Solution Proposal
In the readme(line 117), replace `test-document.txt` with `text-document.txt`

**Comment by florianrusch-zf** [comment]
@jes14 I can't find `test-document.txt` or even `text-document.txt` in the root [`README.md`](/README.md). Can you point me to the specific place?

**Comment by florianrusch-zf** [comment]
@jes14 I can't find `test-document.txt` or even `text-document.txt` in the root [`README.md`](https://github.com/eclipse-edc/Connector/README.md). Can you point me to the specific place?
