### ISSUE TITLE
Adoption Request: EDC IDS-Broker Extension

### ISSUE THREAD

**Issue by tmberthold** [eclipse-edc/Connector#2404]
# Adoption Request as known friend

## General information
Hello,

we as sovity ([Website](https://sovity.de/) | [Github](https://github.com/sovity) | [Linkedin](https://de.linkedin.com/company/sovity)) are working on providing enterprise-ready EDC Connectors and dataspaces as SaaS.

This project, in its first version, can publish assets offered as IDS-resources to a central IDS-Broker, thus establishing initial EDC and IDS-Broker compatibility. We use the event framework of the EDC for this purpose.

| Title | Description | Contact | Links
| :--- | :--- | :--- | :---
| EDC IDS-Broker Extension | EDC connector extension that can register offered assets in form of IDS-resources to a central IDS-Broker. | contact@sovity.de | [link to repo](https://github.com/sovity/edc-extensions)

## Adoption level

Next, please tell us what level of adoption you intend to provide. _(pick only one)_

- [x] Reference a feature as "friend"
- [ ] Incorporate a feature as core EDC component

**Comment by jimmarino** [comment]
FYI the IDS broker protocol and architecture have been completely re-worked in the next version of the IDS specifications. We will be implementing the new catalog protocol in EDC.

**Comment by tmberthold** [comment]
Are there already links or further info for this, which would be available already now?

**Comment by jimmarino** [comment]
The new protocol work has been ongoing in the IDS working group and IDS-G repository. We are currently developing planning the new IDS work in EDC.

**Comment by juliapampus** [comment]
> Are there already links or further info for this, which would be available already now?

Please take a look at the new `ids-specification` repository in the IDSA org @tmberthold. Disclaimer: This is just a draft version in review process. As an IDSA member, feel free to provide your feedback.
