### ISSUE TITLE
Adoption Request: Silicon Economy EDC

### ISSUE THREAD

**Issue by steffen-biehs** [eclipse-edc/Connector#2453]
# Adoption Request

## General information

Hello,

within the Silicon Economy project, we are using the EDC to securely connect platform services.

Currently, our EDC development is in the early stages. However, further progress is being planned as we integrate the EDC into more projects.

Our repository contains run-configurations and deployment examples for:
- separated control and data plane
- postgreSQL-based persistence
- HTTP data exchange
- docker compose 
- helm charts (OpenShift)
- postman collection for all API interaction (provider and consumer)

| Title | Description | Contact | Links
| :--- | :--- | :--- | :---
| Silicon Economy EDC | The Silicon Economy EDC is a configured version from the Connector of the Eclipse Dataspace Components (EDC). It is used and specialized to easily integrate Silicon Economy components with the IDS. | ids@siliconeconomy.org | [Link to repository](https://git.openlogisticsfoundation.org/silicon-economy/base/ids/silicon-economy-edc)

## Adoption level

Next, please tell us what level of adoption you intend to provide. _(pick only one)_

- [X] Reference a feature as "friend"
- [ ] Incorporate a feature as core EDC component

**Comment by juliapampus** [comment]
Add new row to `known_friends.md`.

**Comment by juliapampus** [comment]
Sorry for the huge delay!
