### ISSUE TITLE
chore: simplify `DataSourceFactory` and `DataSinkFactory` APIs

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-edc/Connector#2498]
# Feature Request

Currently, both `DataSourceFactory` and `DataSinkFactory` define a validation method like this:
```java
@NotNull Result<Boolean> validate(DataFlowRequest request);
```

Although the `Boolean` wrapped type does not mean anything and in fact is not used by anyone. The propose would be to have them represented by a simpler:
```java
@NotNull Result<Void> validate(DataFlowRequest request);
```

## Which Areas Would Be Affected?
data-plane

## Why Is the Feature Desired?
api expressiveness

## Solution Proposal
To make the API not break from day to night, a good approach could be to define a new method with a default behavior like
```java
default @NotNull Result<Void> validateRequest(DataFlowRequest request) {
    return validate(DataFlowRequest request).mapTo();
}
```

then deprecate the `validate` method and suggesting to override the `validateRequest` as the validate will be removed soon.
change the call from `validate` to `validateRequest`

**Comment by Nil2000** [comment]
Hello @ndr-brt, the code you mentioned is to be changed only on `DataSourceFactory` and `DataSinkFactory` and deprecate the `validate`. Also, we need to change the call from `validate` to `validateRequest` wherever used.

**Comment by ndr-brt** [comment]
> Hello @ndr-brt, the code you mentioned is to be changed only on `DataSourceFactory` and `DataSinkFactory` and deprecate the `validate`. Also, we need to change the call from `validate` to `validateRequest` wherever used.

yes, that's what I wrote in the issue
