### ISSUE TITLE
Allow updates on user-generated entities

### ISSUE THREAD

**Issue by paullatzelsperger** [eclipse-edc/Connector#2506]
# Feature Request

There are several use cases where updates on existing entities would be beneficial. Therefor we should create additional REST endpoints to allow `PUT` requests on these entities.

## Which Areas Would Be Affected?
DataManagementApi, various storage implementations for each entity

## Why Is the Feature Desired?
EDC should be opinionated on whether modifying entities is allowed from a business perspective or not. 
Some use cases require this, or would at least benefit from it.

## Solution Proposal
add `PUT` endpoints for the following entities:
- DataAddress
- Asset
- Policy(Definition)
- ContractDefinition

## Sub-tasks:
_The decision-record needs to be created before starting any of the implementation tasks_
- [x] #2507
- [x] #2508
- [x] #2509
- [x] #2510

**Comment by paullatzelsperger** [comment]
CC: @git-masoud does this fit your needs?

**Comment by git-masoud** [comment]
> CC: @git-masoud does this fit your needs? If you like you could pick the policy definition subtask (#2509)
Yes, this fits our needs perfectly. I would be happy to assist with the policy definition subtask.

**Comment by paullatzelsperger** [comment]
> > CC: @git-masoud does this fit your needs? If you like you could pick the policy definition subtask (#2509)
> 
> Yes, this fits our needs perfectly. I would be happy to assist with the policy definition subtask.

cool, then please read this [decision record](https://github.com/eclipse-edc/Connector/tree/main/docs/developer/decision-records/2023-02-22-update-entities) beforehand and feel free to get in touch (discord) in case you have questions.
