### ISSUE TITLE
Endpoint with EDC Version

### ISSUE THREAD

**Issue by DominikPinsel** [eclipse-edc/Connector#2530]
It would be great to have a public endpoint with version of the connector. This would make troubleshooting easier and persons, that did not create the actual deployment, could check the version, too.

<sub>Dominik Pinsel <dominik.pinsel@mercedes-benz.com>, Mercedes-Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/mercedes-benz/foss/blob/master/PROVIDER_INFORMATION.md) </sub>

**Comment by richardtreier** [comment]
Hi,

we had the same issue with our EDC connectors, wanting to know what deployed version we were looking at in a particular instance.

## EDC Connector Backend

We ended up doing writing an extension "last-commit-info":
- https://github.com/sovity/edc-extensions/tree/main/extensions/last-commit-info
- https://github.com/sovity/edc-extensions/packages/1793180

In our [Dockerfile](https://github.com/sovity/edc-extensions/blob/main/connector/Dockerfile) we add the last commit info via a build arg.

That build arg will be filled by our github pipeline: https://github.com/sovity/edc-extensions/blob/main/.github/workflows/docker-image.yml#L33

### EDC Connector UI
We overwrite a statically served file `/assets/config/version.txt` with the last commit info during build time: https://github.com/sovity/edc-ui/blob/main/.github/workflows/build-and-release-image.yaml#L43

**Comment by jimmarino** [comment]
We should distinguish between the "version" and the "commit hash" even though they are obviously associated. 

Either type of information should not be exposed over a _public_ endpoint. It could be exposed via the observability or other management API endpoint, but I'm not sure what the value would be. Specifically, as an end-user, I would be more interested in the _downstream distribution_ version number and not necessarily the core EDC version number. For example, if Project X ships their 2.0 version of EDC, which relies on an EDC build, I would want to know if I am using "Project X" 2.0, not EDC "0.2". 

That aside, in terms of implementation, this can be done in several ways, such as updating the contents of a class during build (simple and works in all deployment contexts) or getting a resource from a classloader. I don't think serving static files is a good idea because this information may be necessary for other contexts (e.g., logged at boot).

**Comment by DominikPinsel** [comment]
I'm thinking of two cases where this would help.

1. When a connector in the field is updated, a person (that did not do the actual update) could access the endpoint so see whether the update did already happen and was successful.
2. In case two connectors have communication issues, the version of the two connectors can be checked for compability without contacting the connector maintainers.

<sub>Dominik Pinsel <dominik.pinsel@mercedes-benz.com>, Mercedes-Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/mercedes-benz/foss/blob/master/PROVIDER_INFORMATION.md) </sub>

**Comment by jimmarino** [comment]
> I'm thinking of two cases where this would help.
> 
> 1. When a connector in the field is updated, a person (that did not do the actual update) could access the endpoint so see whether the update did already happen and was successful.
> 2. In case two connectors have communication issues, the version of the two connectors can be checked for compability without contacting the connector maintainers.
> 
> Dominik Pinsel [dominik.pinsel@mercedes-benz.com](mailto:dominik.pinsel@mercedes-benz.com), Mercedes-Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/mercedes-benz/foss/blob/master/PROVIDER_INFORMATION.md)

These are two distinct cases:

1. The connector "in the field" is not the EDC, it is a downstream distribution that may use EDC *libraries*. That downstream distribution could use a URL-based mechanism to determine if an update worked, but that's not a recommended approach. In this case, relying on K8S or other specialized orchestration infrastructure would be advisable to determine the running "version" of the *downstream* distribution.

2. This use case is different than the connector version. It is the *supported IDS* version(s). This needs to be handled as part of the IDS protocol, not the management layer.

**Comment by DominikPinsel** [comment]
> This use case is different than the connector version. It is the supported IDS version(s). This needs to be handled as part of the IDS protocol, not the management layer.

The IDS version does not give enough information about the connector capabilities. For example the catalog query feature was added at some point, while the IDS version of the EDC stayed the same.

**Comment by jimmarino** [comment]
> > This use case is different than the connector version. It is the supported IDS version(s). This needs to be handled as part of the IDS protocol, not the management layer.
> 
> The IDS version does not give enough information about the connector capabilities. For example the catalog query feature was added at some point, while the IDS version of the EDC stayed the same.

That is not the case. With *releases*, the EDC are versioned and the new IDS Protocol Specifications will be too.
