### ISSUE TITLE
Immutable DataPlaneInstanceStore

### ISSUE THREAD

**Issue by wolf4ood** [eclipse-edc/Connector#2533]
# Feature Request

Implements a static `DataPlaneInstanceStore` that can be configured with `EDC` settings and  be immutable once initialized

## Which Areas Would Be Affected?
Data plane selector

## Why Is the Feature Desired?

For some scenario where the runtime flexibility provided by the `DataPlaneInstanceStore` it's not need,
an implementation of a configurable `DataPlaneInstanceStore` could simplify instances setup, without requiring users to write
custom extensions or some migration mechanism for handling their `DataPlaneInstance` data.

## Solution Proposal

A new extension could be introduced that implements the `DataPlaneInstanceStore` which will be driven by configuration.

At startup time the extension  loads the configuration and it  creates an immutable version of `DataPlaneInstanceStore`. 

The configuration could leverage the same mechanism used in the `DataSource` configuration by partition a certain level of the `Config` for configuring
multiple `DataPlaneInstance`.

**Comment by ndr-brt** [comment]
@wolf4ood given the path we went through with the `DataPlaneSelectorManager`, is this still needed?

**Comment by wolf4ood** [comment]
@ndr-brt 

I don't think it's still valid
