### ISSUE TITLE
Create assertions and matchers for the `Result` framework

### ISSUE THREAD

**Issue by paullatzelsperger** [eclipse-edc/Connector#2557]
# Feature Request

The idea is to provide customized AssertJ assertions for our growing `Result` framework. This would enable us to write more succinct test code. 
For example a fragment like 

```java
assertThat(someResult.succeeded()).isTrue();
assertThat(someResult.getContent()).isEqualTo(expectedObject);
//or:
assertThat(someResult.succeeded()).isFalse();
assertThat(someResult.reason()).isEqualTo(THE_REASON);
assertThat(someResult.getFailureMessages()).containsExactly("foo","bar");
```
could be written as
```java
assertThat(someResult).isSucceeded().isEqualTo(expectedObject);
assertThat(someResult).isFailed().hasMessages("foo", "bar").withReason(THE_REASON);
```
which not only is more compact and fluent, it also avoids tedious repetition or test code.

## Which Areas Would Be Affected?
`Result`, `ServiceResult`, `StoreResult`, `StatusResult`,...

## Why Is the Feature Desired?
Writing more fluent test code, reducing copy-paste-test code

## Solution Proposal / Requirements
Custom assertions are be written for the `AbstractResult` class. We should be able to assert at least the following:
- whether a result is `failed` or `succeeded`
- that the content is equal to a particular object. implicitly verifies `succeeded`
- that a particular `List<String>` matches the failure messages. implicitly verifies `!succeeded`
- that the result failed with a particular `reason()` (only some result types)
- all these assertions should be chainable (cf. `AbstractCompletableFutureAssert`)

## Further notes:
1. method names etc. listed here are "working titles" and may be adapted within reason
2. please provide a written decision record outlining the implementation proposal first
3. please do **not** replace every occurrence in every test with this new assertion semantic. Let's keep the change surface small.

**Comment by ndr-brt** [comment]
closed by #2640
