### ISSUE TITLE
Provider's `TransferProcess` automatic deprovisioning

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-edc/Connector#2563]
### Discussed in https://github.com/eclipse-edc/Connector/discussions/2542

<div type='discussions-op-text'>

<sup>Originally posted by **ndr-brt** March  3, 2023</sup>
Currently the deprovisioning process is completely manual, this means that if no one takes care of it there could a potential lack of provisioned resources that aren't needed anymore.

While I get the need on the consumer side to let the data put in the provisioned resource (like a bucket or so) ready to be consumed, I don't see why the provider couldn't automatically deprovision the transfer resources as soon as it gets completed or terminated.

What do you think about?</div>

**Comment by jimmarino** [comment]
Yes, this was fixed in the new protocol so we should be able to do this.
