### ISSUE TITLE
Separate `DataRequest` from `RemoteMessage`

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-edc/Connector#2564]
# Feature Request

Currently our domain model `DataRequest` class is implementing the `RemoteMessage` interface and it is used to be sent through the protocol communication.
It's always better to separate domain model from protocol model.

## Which Areas Would Be Affected?
transfer process

## Why Is the Feature Desired?
separation of concerns

## Solution Proposal
Introduce a new `TransferRequestMessage` class that will be the same as `DataRequest` at least at first (it could be stripped of unused fields eventually) and putting a transformation layer before sending and after receiving it.

**Comment by jimmarino** [comment]
One way to solve this would be to replace `RemoteMessage` with a `RemoteMessageEnvelope<T>` that encapsulates a payload of type T. The envelope can be sent to a `RemoteMessageDispatcher,` typed to the  `RemoteMessageEnvelope<T>` it handles. 

This would decouple the domain types from the message metadata.

Let's discuss.
