### ISSUE TITLE
Dynamically setting Auth-Headers for the Http-Pull-Transfer

### ISSUE THREAD

**Issue by efiege** [eclipse-edc/Connector#2613]
# Feature Request

The `HttpDynamicEndpointDataReferenceReceiverExtension` offers the possibility to dynamically set the receiver-endpoint using the transfer-process properties. The auth-headers are however just loaded from the environment-variables.

It would be great if those auth-headers could also be dynamically set like in the Http-Push-Transfer:
https://github.com/eclipse-edc/Connector/blob/0babf1f97ea23a38b1214d8e2fd85b26725a1991/extensions/data-plane/data-plane-http/src/main/java/org/eclipse/edc/connector/dataplane/http/params/decorators/BaseCommonHttpParamsDecorator.java#L66-L82

## Which Areas Would Be Affected?
HttpDynamicEndpointDataReferenceReceiverExtension

## Why Is the Feature Desired?
Access credentials for the http-pull-transfer can just be set using environment-variables

## Solution Proposal
- [ ] Add additional properties to the transfer-process (authKey, authCode, secretName)
- [ ] Use the new properties to set the Auth-Headers sent to the Pulling-Backend

Is that something we could contribute?

**Comment by ndr-brt** [comment]
Hey, sorry I missed this issue, could you explain the proposal further?
