### ISSUE TITLE
Refactor PolicyType

### ISSUE THREAD

**Issue by juliapampus** [eclipse-edc/Connector#2614]
# Feature Request

Add some changes to `PolicyType` and cleanup serialization.

```json
"@type": {
   "@policytype": "set"
}
```
should become
```json
"@type": "set"
```

## Which Areas Would Be Affected?
contract, policy, (de)serialization

## Why Is the Feature Desired?
align with ODRL spec

## Solution Proposal

- [ ] Change PolicyType `contract` to `agreement`
- [ ] Remove `@policyType`
- [ ] Check if type is set properly in all places

**Comment by majadlymhmd** [comment]
@juliapampus i am taking care
