### ISSUE TITLE
RemoteMessage for TransferProcess and TransferProcess Object are missing correlationID

### ISSUE THREAD

**Issue by janpmeyer** [eclipse-edc/Connector#2636]
# Feature Request

The new Remote Messages for TransferProcess are missing the field `correlationId`. `TransferCompletionMessage` , `TransferStartMessage` and `TransferTerminationMessage`.

Also the TransferProcess misses an `correlationId` field.

## Which Areas Would Be Affected?
Transfer-SPI, transfer-core, sql-extension

## Why Is the Feature Desired?
Implement dataspace protocol

## Solution Proposal

Add `private String correlationId`

**Comment by juliapampus** [comment]
@ndr-brt Fine for you or did we miss something?

**Comment by ndr-brt** [comment]
Fine, I created them without thinking about their content because I just needed placeholders to verify theit dispatch in the tests.
