### ISSUE TITLE
'HttpDataSource' can't transfer binary data

### ISSUE THREAD

**Issue by efiege** [eclipse-edc/Connector#2646]
# Bug Report

## Describe the Bug
When binary data is sent using the provider-push-transfer the data is modified by the `HttpDataSource` such that calculated checksums are not the same for the sent and received data.

### Expected Behavior
Binary data can be transfered such that the checksums of sent and received data are equal.

### Observed Behavior
Checksums of sent and received data are not the same.

## Context Information
Related: https://github.com/eclipse-edc/Connector/discussions/2360

## Detailed Description
The issue is caused by converting the received response into a string (applying the encoding) and then reading the bytes from the string:

https://github.com/eclipse-edc/Connector/blob/8126bcdc292980f9fd9b1372b108aa982229b29a/extensions/data-plane/data-plane-http/src/main/java/org/eclipse/edc/connector/dataplane/http/pipeline/HttpDataSource.java#L51-L56

**Comment by jimmarino** [comment]
The current implementation is not a bug and is part of the design. The HTTP sink/source is intended for small string-based document transfers, e.g., "events," not streaming binary data. The suggested approach assumes the default Java platform encoding, which is not guaranteed to be correct. 

The recommended approach is to use a binary-efficient protocol for data transfers via an extension to the DPF or a custom data plane.
