### ISSUE TITLE
Contract offer timing issue

### ISSUE THREAD

**Issue by tuncaytunc-zf** [eclipse-edc/Connector#2650]
# Bug Report

## Describe the Bug
Sometimes the start and end timestamps returned in contract offer by querying the catalog do not precisely reflect the validity stored in the underlying contract definition.

### Expected Behavior
The same timestamp should be used to calculate the contract end and the contract start

### Observed Behavior
If the calculation of the contract end takes some milliseconds this will lead to wrong contract end date.

## Steps to Reproduce
1. If you query query the catalog by using the endpoint `/catalog/request` you may see some milliseconds of difference between `contractStart` and `contractEnd`

## Context Information
Used Control Plane Adapter extension 

- Used version [e.g. EDC v1.0.0]
current version

## Detailed Description
Here some examples by calling the endpoint `/catalog/request`

"contractStart": "2023-03-24T10:38:29.99Z",
"contractEnd": "2024-03-23T10:38:29.989Z"

 "contractStart": "2023-03-24T10:39:26.96Z",
"contractEnd": "2024-03-23T10:39:26.959Z"

"contractStart": "2023-03-24T10:40:12.604Z",
"contractEnd": "2024-03-23T10:40:12.603Z"

## Possible Implementation
When calculating the contract end (adding the validity) the same timestamp should be used as basis as by contract start in  `ContractOfferResolverImpl.java`

**Comment by ndr-brt** [comment]
@tuncaytunc-zf can this be closed?
