### ISSUE TITLE
dataspace protocol: transfer process should handle missing data destinations

### ISSUE THREAD

**Issue by juliapampus** [eclipse-edc/Connector#2728]
# Feature Request

`TransferProcessProtocolServiceImpl::notifyRequested` should be able to handle missing `dataDestination`/`dataAddress` in `TransferRequestMessage`. Same goes for start actions, see #2727.

## Which Areas Would Be Affected?
transfer process (protocol) service

## Why Is the Feature Desired?
The [spec](https://github.com/International-Data-Spaces-Association/ids-specification/blob/main/transfer/transfer.process.protocol.md#1-transferrequestmessage) states that `dataAddress` is optional, citing
> must only be provided if the dct:format requires a push transfer.

`DataAddressValidatorImpl::validate` will fail with an empty data destination.

## Solution Proposal

Either, add null check to protocol service method, e.g.:
```java
    @Override
    @WithSpan
    @NotNull
    public ServiceResult<TransferProcess> notifyRequested(TransferRequestMessage message, ClaimToken claimToken) {
        var dataAddress = message.getDataDestination();
        if (dataAddress != null) { // NOTE: optional property according to spec
            var validDestination = dataAddressValidator.validate(message.getDataDestination());
            if (validDestination.failed()) {
                return ServiceResult.badRequest(validDestination.getFailureMessages());
            }
        }

        ...
    }
```

Or, add null check to `DataAddressValidatorImpl::validate`.

I think the first approach would be cleaner than allowing null values in a validator.

**Comment by ndr-brt** [comment]
I agree on adding the nullcheck to the `notifyRequested` method.

**Comment by ndr-brt** [comment]
whops, wrong button :)
