### ISSUE TITLE
refactor: merge callback addresses in ContractRequestMessage

### ISSUE THREAD

**Issue by juliapampus** [eclipse-edc/Connector#2732]
# Feature Request

Unify `connectorAddress` and `callbackAddress` in `ContractRequestMessage`.

## Which Areas Would Be Affected?
spi

## Why Is the Feature Desired?
We should only use one callback property and decide on its type. 

## Solution Proposal

Rename `connectorAddress` in `RemoteMessage` to align with the DSP.

Decide whether this should be a `List<CallbackAddress>`, `List<String>`, or `String`.

Although currently not included in all message examples of the DSP, this should be an optional property for each message type, as we are supporting async communication.

**Comment by ndr-brt** [comment]
according to the specification, this should be a single value, not a `List`.
I would avoid using the `CallbackAddress` type because it addresses a different requirement. a simple `String callbackAddress` will work fine.
