### ISSUE TITLE
dataspace protocol: Add data type field to TransferRequestMessage

### ISSUE THREAD

**Issue by janpmeyer** [eclipse-edc/Connector#2739]
# Feature Request

The [spec](https://github.com/International-Data-Spaces-Association/ids-specification/blob/main/transfer/message/schema/transfer-request-message-schema.json) of the dataspace-protocol the field `dct-format` required, while the dataAddress field is optional. Because of this difference i would suggest to add an field like "destinationType" or "dctFormat" to the TransferRequestMessage.

Also it could be a nice to have field to extract a pull or push Transfer from the format field and have also an additional field of TransferType, just for nicer Code. 

## Which Areas Would Be Affected?

TransferRequestMessage

## Why Is the Feature Desired?

The fields of the TransferRequestMessage should have the same fields as the [spec](https://github.com/International-Data-Spaces-Association/ids-specification/blob/main/transfer/message/schema/transfer-request-message-schema.json) of the dataspace protocol.

## Solution Proposal

Add additional fields to TransferRequestMessage.

**Comment by janpmeyer** [comment]
@ndr-brt @juliapampus What are your opinions on this?

**Comment by jimmarino** [comment]
These should be treated as JSON-LD extensible types, not hardcoded on the message. See my comments [here](https://github.com/eclipse-edc/Connector/discussions/2730). 

My concern with the draft PRs so far is the message dispatcher delegates appear to be using POJOs to serialize to a JSON format that looks like JSON-LD but is not actually JSON-LD. I could be misunderstanding the state of the PRs, but the runtime must understand and process JSON-LD natively. This entails deserializing and serializing to JSON-P structures on ingress and egress and performing JSON-LD expansion and compaction. The dispatcher delegates should transform to JSON-P structures, use Titanium to perform compaction, and properly insert a JSON-LD @context.

**Comment by juliapampus** [comment]
Relates #2728
