### ISSUE TITLE
protocol: extract JSON-LD context creation

### ISSUE THREAD

**Issue by ronjaquensel** [eclipse-edc/Connector#2763]
# Feature Request

Currently, many of the `dsp` classes that perform JSON-LD compaction(e.g. delegates, controllers) contain their own method for creating the JSON-LD context. This should be extracted to be shared by all these classes.

## Which Areas Would Be Affected?
dsp

## Why Is the Feature Desired?
To not have duplicated code

**Comment by ndr-brt** [comment]
this is already resolved, now the context is created by the `JsonLd` service
