### ISSUE TITLE
Dataspace-Protocol: Missing attributes code and reason in TransferTerminationMessage and ContractNegotiationTerminationMessage

### ISSUE THREAD

**Issue by janpmeyer** [eclipse-edc/Connector#2764]
# Feature Request

The request message `TransferTerminationMessage` misses the attributes code and reason like the [spec](https://docs.internationaldataspaces.org/dataspace-protocol/transfer-process/transfer.process.protocol#5.-transferterminationmessage) has.

The request message `ContractNegotiationTerminationMessage` misses the attribute code like the [spec](https://docs.internationaldataspaces.org/dataspace-protocol/contract-negotiation/contract.negotiation.protocol#6.-contractnegotiationterminationmessage) defines.

## Which Areas Would Be Affected?
control-plane, dsp-specification

## Why Is the Feature Desired?
support the dataspace protocol

## Solution Proposal
Add the fields `code` and `reason` to the `TransferTerminationMessage`.

Add the field `code` to the `TransferTerminationMessage`.

Also we have to look on the discussion in #2729 and look how the reason attribute should look like in the future.

**Comment by janpmeyer** [comment]
@jimmarino @ndr-brt 

Any thoughts on this topic, or are you fine with this approach?

**Comment by ndr-brt** [comment]
Fine with it, please check also https://github.com/eclipse-edc/Connector/issues/2729 because it could overlap with this issue
