### ISSUE TITLE
Create a runtime service for jsonld `expand` and `compact` 

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-edc/Connector#2783]
# Feature Request

Currently the two operations are made through two static methods, but this requires the module where they are defined (`json-ld`) to be added as a dependency on every module where they are needed, same for `titanium-ld`.

An idea to avoid this would be to provide an interface at the spi level like:
```java
interface JsonLd {
    JsonObject expand(JsonObject object);
    JsonObject compact(JsonObject object, JsonObject context);
}
```

the implementation and service registration would be located in a dedicated extension.

## Which Areas Would Be Affected?
spi

**Comment by jimmarino** [comment]
Todo notes from the discussion:

1. Create JsonLD Service in Json-ld
2. Move TypeUtil into Json LD service
3. Move transformers out to a separate module and instantiate them there (not in `dsp-transform`)
4. Remove `dsp-transform` module as it is no longer needed

**Comment by ndr-brt** [comment]
> Todo notes from the discussion:
> 
> 1. Create JsonLD Service in Json-ld
> 2. Move TypeUtil into Json LD service
> 3. Move transformers out to a separate module and instantiate them there (not in `dsp-transform`)
> 4. Remove `dsp-transform` module as it is no longer needed

Point 3-4 still to be done, will rename this issue accordingly

**Comment by ndr-brt** [comment]
#2883
