### ISSUE TITLE
dsp: create dsp-transform-spi

### ISSUE THREAD

**Issue by juliapampus** [eclipse-edc/Connector#2805]
# Feature Request

Create new module `dsp-transform-spi`. 

## Which Areas Would Be Affected?
dsp transform

## Why Is the Feature Desired?
Negotiation and transfer controllers have a suspect dependecy on `dsp-transform`. 

## Solution Proposal
Create `dsp-transform-spi`. Move `TypeUtil`.

**Comment by jimmarino** [comment]
Do they depend on common implementations such as "utility" functions, service interfaces, or both? If they depend on only implementations, this should be a common library module, not an SPI.

**Comment by juliapampus** [comment]
> Do they depend on common implementations such as "utility" functions, service interfaces, or both? If they depend on only implementations, this should be a common library module, not an SPI.

only utility functions for the moment, valid comment

**Comment by jimmarino** [comment]
The utility functions should be moved out into a core json-ld-util module along with `JsonLdUtil`. They should not be at the DSP layer.

**Comment by jimmarino** [comment]
Per the commiter discussion today, we decided on to handle this in #2783. I think this issue can be closed.
