### ISSUE TITLE
dataspace protocol: Add missing fields to DSP-Transfer-Process-Transformer

### ISSUE THREAD

**Issue by janpmeyer** [eclipse-edc/Connector#2806]
# Feature Request

Solve TODOs in DSP-Transfer-Process-Transformer following up the PRs #2759, #2786 and PR #2777.

Add `dataAddress` to JsonObjectFromTransferStartMessageTransfomer and JsonObjectToTransferStartMessageTransfomer.

Add `code` and `reason` to JsonObjectFromTransferStartMessageTransfomer and JsonObjectToTransferStartMessageTransfomer.

## Which Areas Would Be Affected?
DSP-Transfer-Process-Transformer

## Why Is the Feature Desired?
Remove TO-DOs

## Solution Proposal
Add missing fields

**Comment by paullatzelsperger** [comment]
@janpmeyer I'm working ona PR for a `JsonObject[To|From]DataAddress`, because I need that for #2767. Will post the link here as soon as it's ready.
