### ISSUE TITLE
dataspace-protocol (TransferTerminationMessage): Add Nullcheck for code field

### ISSUE THREAD

**Issue by janpmeyer** [eclipse-edc/Connector#2810]
# Feature Request

In the spec of the `TransferTerminationMessage` the field code is required. So in the `TransferTerminationMessage.Builder` it is needed to do a Nullcheck.

## Which Areas Would Be Affected?
`TransferTerminationMessage`, `TransferProcessManagerImpl`

## Why Is the Feature Desired?
Get align with the dataspace-protocol spec

## Solution Proposal
Right now their is no list of error codes. So the Nullcheck in the `TransferTerminationMessage.Builder` should be added after such a list exist.

**Comment by jimmarino** [comment]
It should not be required for an implementation to provide a code. We may need to fix this in the message schema and discuss at the spec level
