### ISSUE TITLE
Restore callbacks in Contract negotiation phases

### ISSUE THREAD

**Issue by wolf4ood** [eclipse-edc/Connector#2815]
# Feature Request
The callbacks in the CN were removed by this [PR](https://github.com/eclipse-edc/Connector/pull/2752). 

Restore them and refactor the `ContractNegotiationService`

## Which Areas Would Be Affected?
contract negotiation

## Why Is the Feature Desired?
currently the callbacks on CN are not working

**Comment by ndr-brt** [comment]
aren't we mixing up things?
the callback address in the `ContractOffer` is the one that should be referred for sending the protocol message, and it's a different scope than the `callbackAddresses`, that are meant to send callbacks to a client on the single connector side, they shouldn't be sent to the counter part, did I understood that in the wrong way?

**Comment by wolf4ood** [comment]
Yeah, indeed there was a mix up and the `callbackAddresses` where removed from `ContractRequestMessage` on that PR mention because they don't make sense in the protocol context. The main issue is that in the service layer `ContractNegotiationService` we were using `ContractRequestMessage` and  we should not take types that implements `RemoteMessage`. In this PR i will create a separated types for service layer which will incorporate back the `callbackAddresses`
