### ISSUE TITLE
Data Plane Instance Store NPE

### ISSUE THREAD

**Issue by IanPUiUk** [eclipse-edc/Connector#2846]
# Bug Report

## Describe the Bug
When using data-plane-instance-store-sql component I get an NPE when starting the connector

### Expected Behavior
It should start without an NPE

### Observed Behavior

```
Caused by: java.lang.NullPointerException
        at java.base/java.util.Objects.requireNonNull(Objects.java:221)
        at org.eclipse.edc.connector.dataplane.selector.store.sql.SqlDataPlaneInstanceStore.<init>(SqlDataPlaneInstanceStore.java:45)
        at org.eclipse.edc.connector.dataplane.selector.store.sql.SqlDataPlaneInstanceStoreExtension.dataPlaneInstanceStore(SqlDataPlaneInstanceStoreExtension.java:58)
        ... 25 more

```

## Steps to Reproduce

1. Add the data plane instance store sql plugin to a connector in the build file...
`    implementation("${edcGroupId}:data-plane-instance-store-sql:${edcVersion}")`
2. Build the connector
3. Start it
4. Get an NPE

## Context Information
Windows 11
Java 17

## Possible Implementation

Method `org.eclipse.edc.connector.dataplane.selector.store.sql.SqlDataPlaneInstanceStoreExtension#dataPlaneInstanceStore` makes a call to create a new instance store...

```
        return new SqlDataPlaneInstanceStore(dataSourceRegistry, getDataSourceName(context), transactionContext, statements, context.getTypeManager().getMapper());
```

I think instead of passing in raw field `statements` it should be calling the (unused) method `private DataPlaneInstanceStatements getStatementImpl()`, so it should be 

```
        return new SqlDataPlaneInstanceStore(dataSourceRegistry, getDataSourceName(context), transactionContext, getStatementsImpl(), context.getTypeManager().getMapper());
```

**Comment by wolf4ood** [comment]
Hi @IanPUiUk 

Thanks for raising this, 

I've provided a fix in this [PR](https://github.com/eclipse-edc/Connector/pull/2848), once it's approved and merged it will be available in snapshots
