### ISSUE TITLE
`TransferProcessManager` not Processing `TransferProcesses` anymore

### ISSUE THREAD

**Issue by efiege** [eclipse-edc/Connector#2869]
# Bug Report

## Describe the Bug
We observed that the `TransferProcessManager` has not been processing `TransferProcesses` anymore.

### Expected Behavior
`TransferProcessManager` periodically trying to transition `TransferProcesses` to their next state.

### Observed Behavior
- `TransferProcesses` getting stuck in INITIAL-State.
- `StateMachineManager-transfer-process` thread not sending requests to the database anymore
- `StateMachineManager-transfer-process` thread still alive and no exceptions in the logs
- On first data-transfer a PSQLException I/O error occured (see Detailed Description)
- After restarting the connector all stuck `TransferProcesses` where moved to their next state

## Steps to Reproduce
-

## Context Information
- Milestone-8

## Detailed Description
Stacktrace occuring on the the first data-transfer attempt after the `TransferProcessManager` is not sending requests to the database anymore: 
`
org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend. at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:383) at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490) at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408) at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:181) at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:170) at org.eclipse.edc.sql.pool.commons.CommonsConnectionPool$PooledConnectionObjectFactory.isConnectionValid(CommonsConnectionPool.java:134) at org.eclipse.edc.sql.pool.commons.CommonsConnectionPool$PooledConnectionObjectFactory.validateObject(CommonsConnectionPool.java:124) at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:343) at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:223) at org.eclipse.edc.sql.pool.commons.CommonsConnectionPool.getConnection(CommonsConnectionPool.java:66) at org.eclipse.edc.sql.datasource.ConnectionPoolDataSource.getConnection(ConnectionPoolDataSource.java:43) at org.eclipse.edc.transaction.local.DataSourceResource.getConnection(DataSourceResource.java:89) at org.eclipse.edc.sql.store.AbstractSqlStore.getConnection(AbstractSqlStore.java:47) at org.eclipse.edc.connector.store.sql.transferprocess.store.SqlTransferProcessStore.lambda$processIdForDataRequestId$4(SqlTransferProcessStore.java:99) at org.eclipse.edc.transaction.local.LocalTransactionContext.execute(LocalTransactionContext.java:74) at org.eclipse.edc.connector.store.sql.transferprocess.store.SqlTransferProcessStore.processIdForDataRequestId(SqlTransferProcessStore.java:96) at org.eclipse.edc.connector.transfer.process.TransferProcessManagerImpl.initiateRequest(TransferProcessManagerImpl.java:257) at org.eclipse.edc.connector.transfer.process.TransferProcessManagerImpl.initiateProviderRequest(TransferProcessManagerImpl.java:177) at org.eclipse.edc.connector.service.transferprocess.TransferProcessServiceImpl.lambda$initiateTransfer$6(TransferProcessServiceImpl.java:148) at java.base/java.util.Optional.map(Optional.java:260) at org.eclipse.edc.connector.service.transferprocess.TransferProcessServiceImpl.lambda$initiateTransfer$7(TransferProcessServiceImpl.java:148) at org.eclipse.edc.transaction.local.LocalTransactionContext.execute(LocalTransactionContext.java:74) at org.eclipse.edc.connector.service.transferprocess.TransferProcessServiceImpl.initiateTransfer(TransferProcessServiceImpl.java:145) at org.eclipse.edc.protocol.ids.api.multipart.handler.ArtifactRequestHandler.handleRequest(ArtifactRequestHandler.java:161) at org.eclipse.edc.protocol.ids.api.multipart.controller.MultipartController.lambda$request$1(MultipartController.java:139) at java.base/java.util.Optional.map(Optional.java:260) at org.eclipse.edc.protocol.ids.api.multipart.controller.MultipartController.request(MultipartController.java:139) at jdk.internal.reflect.GeneratedMethodAccessor268.invoke(Unknown Source) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.base/java.lang.reflect.Method.invoke(Method.java:568) at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52) at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:134) at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:177) at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:219) at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:81) at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:478) at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:400) at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81) at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:261) at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) at org.glassfish.jersey.internal.Errors.process(Errors.java:292) at org.glassfish.jersey.internal.Errors.process(Errors.java:274) at org.glassfish.jersey.internal.Errors.process(Errors.java:244) at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265) at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:240) at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:697) at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394) at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346) at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:358) at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:311) at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205) at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764) at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:529) at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221) at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1380) at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176) at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484) at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174) at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1302) at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129) at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:192) at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122) at org.eclipse.jetty.server.Server.handle(Server.java:563) at org.eclipse.jetty.server.HttpChannel.lambda$handle$0(HttpChannel.java:505) at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:762) at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:497) at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282) at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314) at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100) at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53) at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:421) at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:390) at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:277) at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:139) at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411) at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:933) at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1077) at java.base/java.lang.Thread.run(Thread.java:833) Caused by: java.net.SocketException: Connection reset by peer at java.base/sun.nio.ch.NioSocketImpl.implWrite(NioSocketImpl.java:420) at java.base/sun.nio.ch.NioSocketImpl.write(NioSocketImpl.java:440) at java.base/sun.nio.ch.NioSocketImpl$2.write(NioSocketImpl.java:826) at java.base/java.net.Socket$SocketOutputStream.write(Socket.java:1035) at java.base/sun.security.ssl.SSLSocketOutputRecord.deliver(SSLSocketOutputRecord.java:345) at java.base/sun.security.ssl.SSLSocketImpl$AppOutputStream.write(SSLSocketImpl.java:1298) at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81) at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142) at org.postgresql.core.PGStream.flush(PGStream.java:709) at org.postgresql.core.v3.QueryExecutorImpl.sendSync(QueryExecutorImpl.java:1528) at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:354) ... 78 more
`

**Comment by ndr-brt** [comment]
Could you add some details as the connector configuration (especially the connection pool part)? We're not able to replicate it.
I suggest to upgrade to `0.0.1-milestone-9` and try again.
