### ISSUE TITLE
dataspace-protocol: switch EndToEnd tests protocol from ids to dsp  

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-edc/Connector#2881]
# Feature Request

Currently the e2e tests are using the old IDS protocol through the `ids` module, they shoud be switched to the new Dataspace Protocol (http binding) using the module `dsp`.

## Which Areas Would Be Affected?
system-tests

## Why Is the Feature Desired?
dataspace-protocol

## Solution Proposal
_If possible, provide a (brief!) solution proposal._

**Comment by ndr-brt** [comment]
Opened a WIP branch: https://github.com/Think-iT-Labs/EDC-Connector/tree/2881-switch-end-to-end-tests-to-dsp
Waiting for #2884 to continue

**Comment by jimmarino** [comment]
@ndr-brt Can we also wait for this #2877?

**Comment by jimmarino** [comment]
@ndr-brt we also need to fix #2895 before this will work. I plan to do that after #2889, and #2890 but feel free to take #2895 if it is blocking you.
