### ISSUE TITLE
dsp: `JsonObjectToContractAgreementMessageTransformer` fails mapping `ContractAgreement`

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-edc/Connector#2919]
# Bug Report

## Describe the Bug
An exception is thrown at line 59 because the object is not a `JsonObject` but a `JsonArray` that has the `JsonObject` as first item:
https://github.com/eclipse-edc/Connector/blob/4f76a8cd9db77678d44f2f0edfee9b896ab8664f/data-protocols/dsp/dsp-negotiation/dsp-negotiation-transform/src/main/java/org.eclipse.edc.protocol.dsp.negotiation.transform/to/JsonObjectToContractAgreementMessageTransformer.java#L59

### Expected Behavior
_A clear and concise description of what you expected to happen._

### Observed Behavior
_A clear and concise description of what happened instead._

## Context Information
_Add any other context about the problem here._

- Used version [e.g. EDC v1.0.0]
- OS: [e.g. iOS, Windows]
- ...

## Detailed Description
_If applicable, add screenshots and logs to help explain your problem._

## Possible Implementation
_You already know the root cause of the erroneous state and how to fix it? Feel free to share your thoughts._

**Comment by jimmarino** [comment]
.cf also the comment by @ndr-brt: 

https://github.com/eclipse-edc/Connector/pull/2932#discussion_r1189970983_

**Comment by jimmarino** [comment]
@ndr-brt I think this has been resolved, can you verify?
