### ISSUE TITLE
dsp: `ContractValidationServiceImpl` checks fields not used in DSP

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-edc/Connector#2920]
# Feature Request

Currently it checks for mandatory attributes (only `providerId`), but it is not present in the DSP contract offer
https://github.com/eclipse-edc/Connector/blob/4f76a8cd9db77678d44f2f0edfee9b896ab8664f/core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/validation/ContractValidationServiceImpl.java#L78

Same happens for contract validity fields:
https://github.com/eclipse-edc/Connector/blob/4f76a8cd9db77678d44f2f0edfee9b896ab8664f/core/control-plane/contract-core/src/main/java/org/eclipse/edc/connector/contract/validation/ContractValidationServiceImpl.java#L116

## Which Areas Would Be Affected?
_e.g., DPF, CI, build, transfer, etc._

## Why Is the Feature Desired?
_Are there any requirements?_

## Solution Proposal
_If possible, provide a (brief!) solution proposal._

**Comment by juliapampus** [comment]
Should be covered by resolving #2758

**Comment by jimmarino** [comment]
I removed this in 6447d3a14fd5f822cf0ff8d458ae52ef8bccad36 as it only checked the provider id
