### ISSUE TITLE
Policy-Definition-Api tests fail if system locale is not English

### ISSUE THREAD

**Issue by mf-isst** [eclipse-edc/Connector#2934]
# Bug Report

## Describe the Bug
The policy-definition-api tests `PolicyDefinitionRequestDtoValidationTest` and `PolicyDefinitionUpdateDtoValidationTest` fail because they assume an error message is generated in English and compare the desired output to the returned message. 
The actual generated error message depends on the system locale and is therefore generated in the host system's set language.

### Expected Behavior
Error message generated in English at all times and the test succeeds.

### Observed Behavior
Generated error message incorrect if system's locale is set to something other than English.

## Steps to Reproduce
Run `./gradlew clean build` from the root directory for a full build or just execute the respective test task with `./gradlew clean :extensions:control-plane:api:management-api:policy-definition-api:test`

## Possible Implementation
Either obtain the locale specific String for the comparison or temporarily override the locale inside the respective tests

**Comment by paullatzelsperger** [comment]
Will close as the associated PR has no right to exist at all.
