### ISSUE TITLE
Implement JSON-LD validation on protocol endpoints (=controllers)

### ISSUE THREAD

**Issue by jimmarino** [eclipse-edc/Connector#2936]
This issue serves as an umbrella issue for work post-M-9 to refactor and make more consistent DSP controller validation if possible.

## Tasks
- [x] Catalog controller
- [x] Negotiation controller
- [ ] Transfer controller

**Comment by paullatzelsperger** [comment]
renamed to better reflect the task: add the JSON-LD validation, that is currently in place on the API side, also to the protocol side.
