### ISSUE TITLE
`DataAddress` created by `ConsumerPullTransferDataFlowController` doesn't have namespaced properties

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-edc/Connector#2975]
# Bug Report

## Describe the Bug
the `DataAddress` created from the `EndpointDataReference` in `ConsumerPullTransferDataFlowController` does not have namespaced properties, this causes the compaction to "lose" them.

**Comment by wolf4ood** [comment]
I will fix this in this PR since I was touching those classes anyway

https://github.com/eclipse-edc/Connector/pull/2965

**Comment by wolf4ood** [comment]
Fixed here https://github.com/eclipse-edc/Connector/pull/2965
