### ISSUE TITLE
Improve `MinikubeIntegrationTest`

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-edc/Connector#3003]
# Feature Request

Currently we're testing the connector Helm Chart using an e2e test that deploys everything to minikube and runs an e2e test on it.
This is maybe too much, because we should test that the Helm Chart is working, all the rest is already tested in other e2e tests.
We should test charts in the "helm way": https://helm.sh/docs/topics/chart_tests/

## Which Areas Would Be Affected?
_e.g., DPF, CI, build, transfer, etc._

## Why Is the Feature Desired?
_Are there any requirements?_

## Solution Proposal
_If possible, provide a (brief!) solution proposal._

**Comment by jimmarino** [comment]
@ndr-brt is this issue still relevant?

**Comment by ndr-brt** [comment]
nope, will close it
