### ISSUE TITLE
Management-api DTO validation are not executed on `v2`

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-edc/Connector#3011]
# Feature Request

Passing to the `JsonObject` management-api endpoints, the Jakarta validation we used to validate the DTOs is not in place anymore, so we should invoke it explicitly once the incoming `Dto` is created.

## Which Areas Would Be Affected?
management api

## Why Is the Feature Desired?
validation

## Solution Proposal
_If possible, provide a (brief!) solution proposal._

## Checklist
- [x] Asset
- [x] ContractDefinition
- [x] ContractAgreement
- [x] PolicyDefinition
- [x] ContractNegotiation
- [x] TransferProcess
- [ ] QuerySpecDto

**Comment by jimmarino** [comment]
Do we need this anymore after this release? I'd like to get the management API to do a single pass transformation from Json-Ld to types rather then the two-phase transformation it does now. In that event, I think we should just perform our own validation so it is consistent with the protocol error reporting.

**Comment by ndr-brt** [comment]
Yes, that makes sense as well, the point is that currently there's no validation, this was an issue to describe the lack of validation, as soon as it will be in place again we can close this
