### ISSUE TITLE
dsp(contract-api): refactor tests

### ISSUE THREAD

**Issue by juliapampus** [eclipse-edc/Connector#3028]
# Feature Request

Refactor `DspCatalogApiControllerIntegrationTest` and `DspCatalogApiControllerTest`.

## Which Areas Would Be Affected?
dsp-catalog

## Why Is the Feature Desired?
Align with `dsp-negotiation` and `dsp-transform`. Remove test dependency `:data-protocols:dsp:dsp-catalog:dsp-catalog-transform`.

## Solution Proposal
Make use of `RestControllerTestBase`. Unify test classes.

**Comment by paullatzelsperger** [comment]
already handled implicitly in another PR
