### ISSUE TITLE
EventSubscriber not bound to type

### ISSUE THREAD

**Issue by FlorianWege-IESE** [eclipse-edc/Connector#3071]
# Summary

The [EventSubscriber](https://github.com/eclipse-edc/Connector/blob/main/spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/EventSubscriber.java) interface is not bound to a specific type of event, thus not featuring type-safety.

## Detailed Description
The [EventSubscriber](https://github.com/eclipse-edc/Connector/blob/main/spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/EventSubscriber.java) functional interface features a generic method "[on](https://github.com/eclipse-edc/Connector/blob/e7784fc3762ef9478e2de42704689fbec8491905/spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/EventSubscriber.java#LL26C9-L26C9)" instead of the interface itself being generic and the method respectively being type-bound, which means you can call the "on" method with any kind of event (EventEnvelope) on the same EventSubscriber object instance.

```java
public interface EventSubscriber {
    /**
     * Add custom logic for every event happened
     *
     * @param event the event happened
     */
    <E extends Event> void on(EventEnvelope<E> event);
}
```

In the [EventRouter](https://github.com/eclipse-edc/Connector/blob/main/spi/common/core-spi/src/main/java/org/eclipse/edc/spi/event/EventRouter.java) class, the (in milestone-9 revisioned) signatures of the register methods make the user state the kind (class) of the event listened to, but since the EventSubscriber is not typed, you can register any EventSubscriber and have no type-safety:

```java
<E extends Event> void registerSync(Class<E> eventKind, EventSubscriber subscriber);
```

This makes implementations of EventSubscriber interface used in EventRouter look like this:

```java
eventRouter.registerSync(ContractNegotiationAgreed.class, new EventSubscriber() {
    @Override
    public <E extends Event> void on(EventEnvelope<E> event) {
        handleContractNegotiationAgreed((ContractNegotiationAgreed) event.getPayload());
    }
});
```
where you need to explicitly cast the event.

It makes sense to have EventSubscribers tied to a specific kind of event. If it needed to subscribe to any event, it could still be typed `EventSubscriber<Event>`.

## Possible Implementation

Have the EventSubscriber generic like:

```java
public interface EventSubscriber<E extends Event> {
    /**
     * Add custom logic for every event happened
     *
     * @param event the event happened
     */
    void on(EventEnvelope<E> event);
}
```

and change the signatures in EventRouter accordingly:

```java
<E extends Event> void registerSync(Class<E> eventKind, EventSubscriber<E> subscriber);
<E extends Event> void register(Class<E> eventKind, EventSubscriber<E> subscriber);
```

**Comment by ndr-brt** [comment]
`EventSubscriber` in fact has no control on the event passed, because it's up to the `EventRouter` to choose the events and pass them to the subscriber. Add the `E` as the subscriber generic type will force the `EventRouter` to have an explicit cast.
That is causing many compiler warnings, so, though maybe it's not that clean, but it's more correct from the language perspective.

**Comment by FlorianWege-IESE** [comment]
The way this is solved currently, the explicit cast along with validation is pushed to and multiplied in the consumers, which will need to inspect the event, potentially causing runtime errors there. When an `EventSubscriber` is defined in one place and registered elsewhere, refactoring will compiletime-silently break things. It makes sense to solve this centrally in the `EventRouter` where the shortcoming of the language can be isolated (it is an implementation detail and can be reduced to one suppressed warning site) and where the responsibility fits. Moreover, it seems like very bad style to have the same `EventSubscriber` be able to react to any event, which are also likely to change. If this is necessary in some cases, it can still be achieved through the type hierarchy.
