### ISSUE TITLE
Google Cloud Storage extension is missing in extensions/README.md

### ISSUE THREAD

**Issue by dsdinter** [eclipse-edc/Connector#3085]
# Bug Report

## Describe the Bug
Google Cloud Storage extension is missing in https://github.com/eclipse-edc/Connector/blob/main/extensions/README.md

### Expected Behavior
Google Cloud Storage extension should be also listed in the data plane section https://github.com/eclipse-edc/Connector/blob/main/extensions/README.md

### Observed Behavior
It is missing:
Data Plane
[API](https://github.com/eclipse-edc/Connector/blob/main/extensions/data-plane/data-plane-api)
[Azure Storage](https://github.com/eclipse-edc/Connector/blob/main/extensions/data-plane/data-plane-azure-storage)
[Data Factory](https://github.com/eclipse-edc/Connector/blob/main/extensions/data-plane/data-plane-azure-data-factory)
[HTTP](https://github.com/eclipse-edc/Connector/blob/main/extensions/data-plane/data-plane-http)
[S3](https://github.com/eclipse-edc/Connector/blob/main/extensions/data-plane/data-plane-aws-s3)
[Tests](https://github.com/eclipse-edc/Connector/blob/main/extensions/data-plane/data-plane-integration-tests)

## Steps to Reproduce
Open browser in https://github.com/eclipse-edc/Connector/blob/main/extensions/README.md

## Context Information
NA

## Detailed Description
NA
## Possible Implementation
Include the existing reference https://github.com/eclipse-edc/Connector/tree/main/extensions/data-plane/data-plane-google-storage

**Comment by ndr-brt** [comment]
thanks for the issue, definitely not a bug

**Comment by ndr-brt** [comment]
Closing this as the GCP related extensions have been moved out from the `Connector` repository, now they're here:
https://github.com/eclipse-edc/Technology-Gcp
