### ISSUE TITLE
The scope is not set on tokenParameters

### ISSUE THREAD

**Issue by tuncaytunc-zf** [eclipse-edc/Connector#3094]
# Bug Report

## Describe the Bug
The scope parameter is not set on tokenParameters

### Expected Behavior
The scope parameter needs to be set otherwise DAPS will not work

### Observed Behavior
You get an `access_denied` error from DAPS

## Steps to Reproduce
1. When you query the catalog where two connectors are involved.

## Context Information
_Add any other context about the problem here._

- Used version [e.g. EDC v1.0.0]
- edc `0.0.1-milestone-9`

## Detailed Description
_If applicable, add screenshots and logs to help explain your problem._

## Possible Implementation
The scope needs to be set in `DspHttpRemoteMessageDispatcherImpl.java` when initializing the `tokenParameters`.

**Comment by paullatzelsperger** [comment]
Previously the `scope` parameter got set by the `DynamicAttributeTokenService`. That class was located in the IDS modules, and they got removed from the code base.

What we need here is three things:
1. a pluggable way to add the `scope` parameter to the request on egress (`DspHttpRemoteMessageDispatcherImpl`)
2. a pluggable way to verify the token on ingress. We already have that, it's called `TokenValidationService` and delegates out to `ValdationRule`s.
3. an extension that plugs in both the token decorator on egress and the `DapsValidationRule` (formerly called `IdsValidationRule`) on ingress
