### ISSUE TITLE
[contract definition] Error when retrieving a single contract definition 

### ISSUE THREAD

**Issue by AhmedGrati** [eclipse-edc/Connector#3137]
# Bug Report

## Describe the Bug
When trying to fetch a contract definition by ID, the `edc:criteria` is returned as an object, while It should be an array of objects.

### Expected Behavior
When getting a contract definition by ID, I expect this object:
```json
{
  "@id": "contract",
  "@type": "edc:ContractDefinition",
  "edc:accessPolicyId": "example-access-policy-id",
  "edc:contractPolicyId": "example-contract-policy-id",
  "edc:criteria": [{
    "@type": "edc:CriterionDto",
    "edc:operandLeft": "edc.asset",
    "edc:operandRight": "test",
    "edc:operator": "equals"
  }],
  "@context": {
    "dct": "https://purl.org/dc/terms/",
    "edc": "https://w3id.org/edc/v0.0.1/ns/",
    "dcat": "https://www.w3.org/ns/dcat/",
    "odrl": "http://www.w3.org/ns/odrl/2/",
    "dspace": "https://w3id.org/dspace/v0.8/"
  }
}
```

### Observed Behavior
In reality, the EDC connector is returning an `edc:criteria` as a single object. e.g:

```json
{
  "@id": "contract",
  "@type": "edc:ContractDefinition",
  "edc:accessPolicyId": "example-access-policy-id",
  "edc:contractPolicyId": "example-contract-policy-id",
  "edc:criteria": {
    "@type": "edc:CriterionDto",
    "edc:operandLeft": "edc.asset",
    "edc:operandRight": "test",
    "edc:operator": "equals"
  },
  "@context": {
    "dct": "https://purl.org/dc/terms/",
    "edc": "https://w3id.org/edc/v0.0.1/ns/",
    "dcat": "https://www.w3.org/ns/dcat/",
    "odrl": "http://www.w3.org/ns/odrl/2/",
    "dspace": "https://w3id.org/dspace/v0.8/"
  }
}
```

## Steps to Reproduce
1. Create a contract definition with the following object as the body of the request:
```json
{
  "@id": "contract",
  "accessPolicyId": "example-access-policy-id",
  "contractPolicyId": "example-contract-policy-id",
  "@context": {},
  "criteria": [
    {
      "operandLeft": "edc.asset",
      "operandRight": "test",
      "operator": "equals"
    }
  ]
}
```
2. Fetch that specific contract definition, using the route `/contractdefinitions/contract`, and you should see the following response:
```json
{
  "@id": "contract",
  "@type": "edc:ContractDefinition",
  "edc:accessPolicyId": "example-access-policy-id",
  "edc:contractPolicyId": "example-contract-policy-id",
  "edc:criteria": {
    "@type": "edc:CriterionDto",
    "edc:operandLeft": "edc.asset",
    "edc:operandRight": "test",
    "edc:operator": "equals"
  },
  "@context": {
    "dct": "https://purl.org/dc/terms/",
    "edc": "https://w3id.org/edc/v0.0.1/ns/",
    "dcat": "https://www.w3.org/ns/dcat/",
    "odrl": "http://www.w3.org/ns/odrl/2/",
    "dspace": "https://w3id.org/dspace/v0.8/"
  }
}
```

## Context Information
N/A

## Detailed Description
The creation of contract definition
<img width="1164" alt="Screen Shot 2023-06-01 at 1 30 07 PM" src="https://github.com/eclipse-edc/Connector/assets/48932084/139a8551-54b4-4686-9e31-b5a57697263f">

The fetching of the previously created contract definition
<img width="1158" alt="Screen Shot 2023-06-01 at 1 30 39 PM" src="https://github.com/eclipse-edc/Connector/assets/48932084/2ee53bf5-a24c-4479-98aa-100726bc8cbb">

When I create a contract definition with multiple criteria, the response of the `GET` request of a single contract definition, would have an array of objects in the `edc:criteria`, which is the desired response. Therefore there's an inconsistency in the API response when trying to `GET` a single contract definition.

## Possible Implementation
N/A.

**Comment by wolf4ood** [comment]
Hi @AhmedGrati 

this happens because of the compaction process as stated in the [json-ld](https://www.w3.org/TR/json-ld-api/#the-jsonldoptions-type) spec. The default configuration of the option `compactArrays` is true in the spec and in the library that we use. Unfortunately it's not possible yet to override that configuration. I would label this issue as `enhancement` and make it configurable.

In case you are interested in contributing [this](https://github.com/eclipse-edc/Connector/blob/e457da2a18dfc0c749aa1357c05e24447a693105/extensions/common/json-ld/src/main/java/org/eclipse/edc/jsonld/JsonLdExtension.java#L89) is the entry point for the jsonld extension. and [here](https://github.com/eclipse-edc/Connector/blob/e457da2a18dfc0c749aa1357c05e24447a693105/extensions/common/json-ld/src/main/java/org/eclipse/edc/jsonld/TitaniumJsonLd.java#L87) where the compact happens.

Thanks

**Comment by jimmarino** [comment]
I'm not sure we want to make this configurable. We probably should support one way or the other.

**Comment by tarunsamanta2k20** [comment]
I'd like to work on it.

**Comment by wolf4ood** [comment]
If we want to have a fixed solution i would prefer the not compressed one always :)

**Comment by jimmarino** [comment]
> I'd like to work on it.

Of course, I don't think anyone is arguing to create a broken solution. As it currently is, it works per the Json-LD spec, although it may not be developer-friendly, and we may want to change it.

**Comment by ndr-brt** [comment]
Another advice could be to always expand json-ld before evaluating it, because as a client you cannot take for granted a specific server compaction configuration.

**Comment by AhmedGrati** [comment]
@ndr-brt any update on this?

**Comment by ndr-brt** [comment]
nobody had the time to do this, we're eventually waiting for community contributions
