### ISSUE TITLE
OpenApi: Inconsistency between documentation and API behavior for PolicyDefinition

### ISSUE THREAD

**Issue by Nazdroth** [eclipse-edc/Connector#3139]
# Bug Report

## Issue Description
The OpenAPI specification for the create policy endpoint does not align with the expected payload structure. The provided example payload in the documentation does not match the payload that actually works. Additionally, the `odrl:action` field does not correctly handle the `odrl:constraint` property, as it only considers `odrl:includedIn` and `odrl:type` properties while ignoring the `odrl:constraint` array. This discrepancy causes confusion and may lead to incorrect implementation by users.

## Current Behavior
The example payload provided in the documentation ([swagger](https://app.swaggerhub.com/apis/eclipse-edc-bot/management-api/0.1.1-SNAPSHOT#/PolicyDefinitionRequestDto)) is as follows:

```json
{
  "@context": {
    "@vocab": "https://w3id.org/edc/v0.0.1/ns/",
    "odrl": "http://www.w3.org/ns/odrl/2/"
  },
  "@type":"PolicyDefinition",
  "@id": "{{POLICY_ID}}",
  "policy": {
    "odrl:permission": [
      {
        "odrl:action": {
          "odrl:constraint": {
             "odrl:edctype": ""
          },
          "odrl:includedIn": "in",
          "odrl:type" : "USE"
        },
        "odrl:constraint": [
          {
            "odrl:edctype": "",
          }]
      }
    ],
    "odrl:prohibition": [],
    "odrl:obligation": []
  }
}
```
### API response
```json
[
  {
    "message": "Constraint property 'http://www.w3.org/ns/odrl/2/leftOperand' was missing",
    "type": "InvalidRequest",
    "path": null,
    "invalidValue": null
  }
]
```

However, the payload that actually works is as follows:
### Working Payload
```json
{
  "@context": {
    "@vocab": "https://w3id.org/edc/v0.0.1/ns/",
    "odrl": "http://www.w3.org/ns/odrl/2/"
  },
  "@type":"PolicyDefinition",
  "@id": "{{POLICY_ID}}",
  "policy": {
    "odrl:permission": [
      {
        "odrl:action": {
	    "odrl:constraint": {
                  "odrl:leftOperand": "POLICY_EVALUATION_TIME",
                  "odrl:operator": "LT",
                  "odrl:rightOperand": "2023-06-01T12:00:00.000XXX"
              },
	      "odrl:includedIn": "in",
	      "odrl:type" : "USE"
	},
        "odrl:constraint": [
           {
            "odrl:leftOperand": "BusinessPartnerNumber",
            "odrl:operator": "EQ",
            "odrl:rightOperand":  "BPN"
          }]
      }
    ],
    "odrl:prohibition": [],
    "odrl:obligation": []
  }
}
```
### Get Policy response
```json
{
  "@id": "12345",
  "@type": "edc:PolicyDefinition",
  "edc:createdAt": 1685623406845,
  "edc:policy": {
    "@id": "9b3aff8e-d6ea-4f77-ac1f-1295d0461586",
    "@type": "odrl:Set",
    "odrl:permission": {
      "odrl:action": {
        "odrl:type": "USE",
        "odrl:includedIn": "in"
      },
      "odrl:constraint": {
        "odrl:leftOperand": "BusinessPartnerNumber",
        "odrl:operator": "EQ",
        "odrl:rightOperand": "BPN"
      }
    },
    "odrl:prohibition": [],
    "odrl:obligation": []
  },
  "@context": {
    "dct": "https://purl.org/dc/terms/",
    "edc": "https://w3id.org/edc/v0.0.1/ns/",
    "dcat": "https://www.w3.org/ns/dcat/",
    "odrl": "http://www.w3.org/ns/odrl/2/",
    "dspace": "https://w3id.org/dspace/v0.8/"
  }
}
```

## Expected Behavior
The documentation should provide an accurate example of the expected payload structure for the create policy endpoint.
- `odrl:action` should handle properly `odrl:constraint` or it should be removed from the openAPI spec
- `odrl:constraint` schema should be updated in openAPI spec

## Steps to Reproduce (if applicable)
Access the create policy endpoint using the documented example payload.
Observe the incorrect behavior or error response.

**Comment by paullatzelsperger** [comment]
@Nazdroth thanks for raising this. I took the liberty of removing the bug label, as it is really an improvement request regarding documentation.
PRs welcome!
