### ISSUE TITLE
management api: Create asset payload inconsistent with the rest of the API entities

### ISSUE THREAD

**Issue by NabilHouidi** [eclipse-edc/Connector#3151]
I didn't know whether this counted as an bug or not, so I am opening a blank issue.

While working with the `POST` `/management/v2/assets` endpoints,
I tried creating an **asset** with a **pre-configured** `id`,
this is the accepted payload
```json
{
  "@context": {
    "@vocab": "https://w3id.org/edc/v0.0.1/ns/"
  },
  "@type": "AssetEntryDto",
  "asset": {
    "@id": "some-id",
    "properties": {
      "name": "asset-name"
    }
  },
  "dataAddress": {
    "type": "asset-address-type",
    "keyName": "asset-key-name"
  }
}
```
Notice how the `@id` is nested under `asset` and not at top level.

This is inconsistent with the other management entities (example, policies) and with the swagger documentation.

So I am just wondering whether this was intentional or an omission during the move to json-ld.

**Comment by ndr-brt** [comment]
Thanks for opening this issue, I noticed this detail.
The historical detail is that `DataAddress` and `Asset` are considered two different entities, and in fact when we call the `POST` enpoint we're not passing an `Asset` but what we called `AssetEntry`, that's an wrapper object.
I can't see the reason for keeping `Asset` and `DataAddress` separated anymore, I can take care of this refactoring.
