### ISSUE TITLE
.gitignore Improvement after build and tests

### ISSUE THREAD

**Issue by Wilhelmsson177** [eclipse-edc/Connector#3157]
# Bug Report

## Describe the Bug
Not really a bug, but after executing a full build and running tests, a 100+ files are created and untracked.

### Expected Behavior
If unnecessary (built) files should not be part of the repository, these should be ignored generally, otherwise these files might unintentionally get committed.

### Observed Behavior
After executing a full build and running tests, a 100+ files are created and untracked.

## Steps to Reproduce
1. gradle build
2. check git status

## Context Information

- Used version current main
- OS: Windows

## Detailed Description
I do not know if some of the generated *.ServiceExtension files should be committed in the first place.

## Possible Implementation
Update .gitignore

**Comment by jimmarino** [comment]
- What specific files are untracked? 
- Which build command was executed?
- Which commit hash or tag are you building?

**Comment by Wilhelmsson177** [comment]
-  These are the untracked files
    - ```
        core/common/boot/bin/main/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
        core/common/boot/bin/main/META-INF/services/org.slf4j.spi.SLF4JServiceProvider
        core/common/boot/bin/test/mockito-extensions/org.mockito.plugins.MockMaker
        core/common/connector-core/bin/main/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
        core/common/connector-core/bin/test/ec-privatekey.pem
        core/common/connector-core/bin/test/rsa-privatekey.pem
        core/common/junit/bin/test/META-INF/services/org.eclipse.edc.spi.system.MonitorExtension
        core/control-plane/catalog-core/bin/main/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
        core/control-plane/contract-core/bin/main/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
        core/control-plane/control-plane-aggregate-services/bin/main/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
        core/control-plane/control-plane-core/bin/main/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
        core/control-plane/transfer-core/bin/main/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
        core/data-plane-selector/data-plane-selector-core/bin/main/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
        core/data-plane/data-plane-framework/bin/main/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
        data-protocols/dsp/dsp-api-configuration/bin/main/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
        data-protocols/dsp/dsp-catalog/dsp-catalog-api/bin/main/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
        data-protocols/dsp/dsp-catalog/dsp-catalog-http-dispatcher/bin/main/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
        data-protocols/dsp/dsp-catalog/dsp-catalog-transform/bin/main/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
        data-protocols/dsp/dsp-http-core/bin/main/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
        data-protocols/dsp/dsp-negotiation/dsp-negotiation-api/bin/main/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
        data-protocols/dsp/dsp-negotiation/dsp-negotiation-http-dispatcher/bin/main/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
        data-protocols/dsp/dsp-negotiation/dsp-negotiation-transform/bin/main/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
        data-protocols/dsp/dsp-transfer-process/dsp-transfer-process-api/bin/main/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
        data-protocols/dsp/dsp-transfer-process/dsp-transfer-process-http-dispatcher/bin/main/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
        data-protocols/dsp/dsp-transfer-process/dsp-transfer-process-transform/bin/main/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension      
        data-protocols/dsp/dsp-transform/bin/main/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
        extensions/common/api/api-core/bin/main/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
        extensions/common/api/api-observability/bin/main/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
        extensions/common/api/control-api-configuration/bin/main/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
        extensions/common/api/management-api-configuration/bin/main/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
        extensions/common/auth/auth-basic/bin/main/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
        extensions/common/auth/auth-tokenbased/bin/main/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
        extensions/common/configuration/configuration-filesystem/bin/main/META-INF/services/org.eclipse.edc.spi.system.ConfigurationExtension
        extensions/common/configuration/configuration-filesystem/bin/test/edc-configuration.properties
        extensions/common/events/events-cloud-http/bin/main/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
        extensions/common/http/jersey-core/bin/main/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
        extensions/common/http/jersey-micrometer/bin/main/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
        extensions/common/http/jetty-core/bin/main/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
        extensions/common/http/jetty-micrometer/bin/main/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
        extensions/common/iam/decentralized-identity/identity-did-core/bin/main/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
        extensions/common/iam/decentralized-identity/identity-did-core/bin/test/private_secp256k1.pem
        extensions/common/iam/decentralized-identity/identity-did-core/bin/test/public_secp256k1.pem
        extensions/common/iam/decentralized-identity/identity-did-crypto/bin/test/private_p256.pem
        extensions/common/iam/decentralized-identity/identity-did-crypto/bin/test/public_p256.pem
        extensions/common/iam/decentralized-identity/identity-did-service/bin/main/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
        extensions/common/iam/decentralized-identity/identity-did-service/bin/test/dids.json
        extensions/common/iam/decentralized-identity/identity-did-test/bin/testFixtures/edc-test-keystore.jks
        extensions/common/iam/decentralized-identity/identity-did-test/bin/testFixtures/readme-keystore.txt
        extensions/common/iam/decentralized-identity/identity-did-web/bin/main/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
        extensions/common/iam/decentralized-identity/identity-did-web/bin/test/did.json
        extensions/common/iam/iam-mock/bin/main/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
        extensions/common/iam/oauth2/oauth2-client/bin/main/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
        extensions/common/iam/oauth2/oauth2-core/bin/main/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
        extensions/common/iam/oauth2/oauth2-core/bin/test/cert.pem
        extensions/common/iam/oauth2/oauth2-core/bin/test/jwks_response.json
        extensions/common/iam/oauth2/oauth2-daps/bin/main/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
        extensions/common/iam/oauth2/oauth2-daps/bin/test/config/clients.yml
        extensions/common/iam/oauth2/oauth2-daps/bin/test/config/omejdn.yml
        extensions/common/iam/oauth2/oauth2-daps/bin/test/config/scope_mapping.yml
        extensions/common/iam/oauth2/oauth2-daps/bin/test/empty-vault.properties
        extensions/common/iam/oauth2/oauth2-daps/bin/test/keys/Njg6OTk6MkU6RDQ6MTM6MkQ6RkQ6M0E6NjY6NkI6ODU6REU6RkI6OTg6MkU6MkQ6RkQ6RTc6ODM6RDc=.cert
        extensions/common/iam/oauth2/oauth2-daps/bin/test/keys/signing_key.pem
        extensions/common/iam/oauth2/oauth2-daps/bin/test/keystore.p12
        extensions/common/json-ld/bin/main/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
        extensions/common/json-ld/bin/main/document/odrl.jsonld
        extensions/common/json-ld/bin/test/test-context.jsonld
        extensions/common/metrics/micrometer-core/bin/main/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
        extensions/common/monitor/monitor-jdk-logger/bin/main/META-INF/services/org.eclipse.edc.spi.system.MonitorExtension
        extensions/common/sql/sql-lease/bin/test/schema.sql
        extensions/common/sql/sql-pool/sql-pool-apache-commons/bin/main/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
        extensions/common/transaction/transaction-atomikos/bin/main/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
        extensions/common/transaction/transaction-local/bin/main/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
        extensions/common/vault/vault-filesystem/bin/main/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
        extensions/common/vault/vault-filesystem/bin/test/edc-test-keystore.jks
        extensions/common/vault/vault-filesystem/bin/test/readme-keystore.txt
        extensions/common/vault/vault-filesystem/bin/test/test-vault.properties
        extensions/common/vault/vault-hashicorp/bin/main/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
        extensions/control-plane/api/control-plane-api-client/bin/main/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
        extensions/control-plane/api/control-plane-api/bin/main/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
        extensions/control-plane/api/management-api/asset-api/bin/main/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
        extensions/control-plane/api/management-api/catalog-api/bin/main/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
        extensions/control-plane/api/management-api/contract-agreement-api/bin/main/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
        extensions/control-plane/api/management-api/contract-definition-api/bin/main/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
        extensions/control-plane/api/management-api/contract-negotiation-api/bin/main/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
        extensions/control-plane/api/management-api/policy-definition-api/bin/main/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
        extensions/control-plane/api/management-api/transfer-process-api/bin/main/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
        extensions/control-plane/callback/callback-event-dispatcher/bin/main/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
        extensions/control-plane/callback/callback-http-dispatcher/bin/main/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
        extensions/control-plane/callback/callback-static-endpoint/bin/main/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
        extensions/control-plane/provision/provision-http/bin/main/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
        extensions/control-plane/provision/provision-oauth2/provision-oauth2-core/bin/main/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
        extensions/control-plane/store/sql/asset-index-sql/bin/main/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
        extensions/control-plane/store/sql/contract-negotiation-store-sql/bin/main/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
        extensions/control-plane/store/sql/policy-definition-store-sql/bin/main/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
        extensions/control-plane/store/sql/transfer-process-store-sql/bin/main/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
        extensions/control-plane/transfer/transfer-data-plane/bin/main/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
        extensions/control-plane/transfer/transfer-data-plane/bin/test/ec-pubkey.pem
        extensions/control-plane/transfer/transfer-data-plane/bin/test/rsa-pubkey.pem
        extensions/control-plane/transfer/transfer-pull-http-dynamic-receiver/bin/main/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
        extensions/control-plane/transfer/transfer-pull-http-receiver/bin/main/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
        extensions/data-plane-selector/data-plane-selector-api/bin/main/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
        extensions/data-plane-selector/data-plane-selector-client/bin/main/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
        extensions/data-plane-selector/store/sql/data-plane-instance-store-sql/bin/main/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
        extensions/data-plane/data-plane-api/bin/main/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
        extensions/data-plane/data-plane-client/bin/main/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
        extensions/data-plane/data-plane-http-oauth2-core/bin/main/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
        extensions/data-plane/data-plane-http/bin/main/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
        extensions/data-plane/data-plane-kafka/bin/main/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
        extensions/data-plane/store/sql/data-plane-store-sql/bin/main/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
        spi/common/core-spi/bin/test/mockito-extensions/org.mockito.plugins.MockMaker
        spi/common/core-spi/bin/test/serialized_asset.json
        spi/common/core-spi/bin/test/testCert.pem
        system-tests/e2e-transfer-test/backend-service/bin/main/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
        system-tests/e2e-transfer-test/runner/bin/test/certs/cert.pem
        system-tests/e2e-transfer-test/runner/bin/test/certs/cert.pfx
        system-tests/e2e-transfer-test/runner/bin/test/certs/key.pem
        system-tests/e2e-transfer-test/runner/bin/test/consumer-vault.properties
        system-tests/e2e-transfer-test/runner/bin/test/provider-vault.properties
```
- build command: `.\gradlew build`
- branch: main (730ca919841a507c0eb99f7a59a258ffe3f63a67)

**Comment by jimmarino** [comment]
This does not look like an issue with the EDC build. It could be that an IDE is creating these files.

**Comment by ndr-brt** [comment]
the `/bin` folder IIRC is created by Eclipse IDE, definitely not a bug related to the EDC, the advice is to configure your IDE properly.
