### ISSUE TITLE
bug: `ContractAgreement` validity is not longer asserted when validating token received by Data Plane 

### ISSUE THREAD

**Issue by bscholtes1A** [eclipse-edc/Connector#3160]
# Bug Report

## Describe the Bug
From https://github.com/eclipse-edc/Connector/pull/2950, the contract validity is no longer checked when validating the token received in input of the Data Plane public API. 

See [`ContractValidationRule.java`](https://github.com/eclipse-edc/Connector/blob/9a8722a18fa396de99eaa721830bd4604cb6cc93/extensions/control-plane/transfer/transfer-data-plane/src/main/java/org/eclipse/edc/connector/transfer/dataplane/validation/ContractValidationRule.java#L51)

### Expected Behavior
Token validation should fail if contract is expired.

### Observed Behavior
Token validation is successful even if contract is expired.

## Possible Implementation
After discussion with @ndr-brt, maybe we want take opportunity of this issue to plug the `PolicyEngine` in the Data Plane? 
However, it would require that the contract agreement information can be retrieved from the Data Plane, which was avoided as per initial design.

**Comment by jimmarino** [comment]
Can't the token validity always be less than the contract validity, i.e., ensure the token validity is not greater than the contract validity? If the token duration is short enough, this should be OK for most cases.

**Comment by jimmarino** [comment]
> > Can't the token validity always be less than the contract validity, i.e., ensure the token validity is not greater than the contract validity? If the token duration is short enough, this should be OK for most cases.
> 
> This can be an approach, but even that requires to be discussed a bit as for now there is not method computing the contract end date except the `ContractExpiryCheckFunction`, which only computes this date internally and return a boolean.

A utility method could do this by delegating to a Policy evaluator or walking the Policy tree. Let's discuss.

**Comment by veronikasiska** [comment]
I encountered a case where the contract negotiation was finalised from the consumer side, but terminated from the provider side, due to a mismatch in the client ID and the connector ID in the contract negotiation request ("Invalid client credentials: Invalid counter-party identity"). Still, the file transfer was completed successfully.

Could this be due to the same bug?

**Comment by Julian-Marco** [comment]
> I encountered a case where the contract negotiation was finalised from the consumer side, but terminated from the provider side, due to a mismatch in the client ID and the connector ID in the contract negotiation request ("Invalid client credentials: Invalid counter-party identity"). Still, the file transfer was completed successfully.
> 
> Could this be due to the same bug?

Can you explain what you mean by "client ID" in this case? I'm facing a similar issue at the moment. One connector is running on an AKS while the other is running on a Bare-Metal-Server. From the consumer side, it looks like this: 

```` 
DEBUG 2023-11-06T14:47:51.176645052 [CONSUMER] ContractNegotiation 993ea65b-cb9b-4b73-9d0e-f7220a0696b9 is now in state INITIAL.
DEBUG 2023-11-06T14:47:51.286058471 [CONSUMER] ContractNegotiation 993ea65b-cb9b-4b73-9d0e-f7220a0696b9 is now in state REQUESTING.
DEBUG 2023-11-06T14:47:51.289638773 ContractNegotiation: ID 993ea65b-cb9b-4b73-9d0e-f7220a0696b9. [Consumer] Send ContractRequestMessage message
DEBUG 2023-11-06T14:47:51.357199274 ContractNegotiation: ID 993ea65b-cb9b-4b73-9d0e-f7220a0696b9. [Consumer] Send ContractRequestMessage message
DEBUG 2023-11-06T14:47:51.361007287 [CONSUMER] ContractNegotiation 993ea65b-cb9b-4b73-9d0e-f7220a0696b9 is now in state REQUESTED.
DEBUG 2023-11-06T14:47:52.165729201 DSP: Incoming ContractAgreementMessage for class org.eclipse.edc.connector.contract.spi.types.negotiation.ContractNegotiation process: 993ea65b-cb9b-4b73-9d0e-f7220a0696b9
DEBUG 2023-11-06T14:47:52.172570941 [CONSUMER] ContractNegotiation 993ea65b-cb9b-4b73-9d0e-f7220a0696b9 is now in state AGREED.
DEBUG 2023-11-06T14:47:52.30725099 [CONSUMER] ContractNegotiation 993ea65b-cb9b-4b73-9d0e-f7220a0696b9 is now in state VERIFYING.
DEBUG 2023-11-06T14:47:52.310754987 ContractNegotiation: ID 993ea65b-cb9b-4b73-9d0e-f7220a0696b9. [consumer] send ContractAgreementVerificationMessage
DEBUG 2023-11-06T14:47:52.346247325 ContractNegotiation: ID 993ea65b-cb9b-4b73-9d0e-f7220a0696b9. [consumer] send ContractAgreementVerificationMessage
DEBUG 2023-11-06T14:47:52.350331371 [CONSUMER] ContractNegotiation 993ea65b-cb9b-4b73-9d0e-f7220a0696b9 is now in state VERIFIED.
DEBUG 2023-11-06T14:47:53.104750927 DSP: Incoming ContractNegotiationEventMessage for class org.eclipse.edc.connector.contract.spi.types.negotiation.ContractNegotiation process: 993ea65b-cb9b-4b73-9d0e-f7220a0696b9
DEBUG 2023-11-06T14:47:53.119447444 DSP: Service call failed: Invalid client credentials: Invalid counter-party identity
```` 

And from the provider side: 

````
DEBUG 2023-11-06T14:47:51.336359923 DSP: Incoming ContractRequestMessage for class org.eclipse.edc.connector.contract.spi.types.negotiation.ContractNegotiation process
DEBUG 2023-11-06T14:47:51.337835928 [PROVIDER] ContractNegotiation 5df554f0-969d-4a12-a775-d75716081b28 is now in state REQUESTED.
DEBUG 2023-11-06T14:47:52.080870289 [PROVIDER] ContractNegotiation 5df554f0-969d-4a12-a775-d75716081b28 is now in state AGREEING.
DEBUG 2023-11-06T14:47:52.08113369 ContractNegotiation: ID 5df554f0-969d-4a12-a775-d75716081b28. [Provider] send agreement
DEBUG 2023-11-06T14:47:52.196521935 ContractNegotiation: ID 5df554f0-969d-4a12-a775-d75716081b28. [Provider] send agreement
DEBUG 2023-11-06T14:47:52.196668035 [PROVIDER] ContractNegotiation 5df554f0-969d-4a12-a775-d75716081b28 is now in state AGREED.
DEBUG 2023-11-06T14:47:52.328720544 DSP: Incoming ContractAgreementVerificationMessage for class org.eclipse.edc.connector.contract.spi.types.negotiation.ContractNegotiation process: 993ea65b-cb9b-4b73-9d0e-f7220a0696b9
DEBUG 2023-11-06T14:47:52.329398146 [PROVIDER] ContractNegotiation 5df554f0-969d-4a12-a775-d75716081b28 is now in state VERIFIED.
DEBUG 2023-11-06T14:47:53.08355715 [PROVIDER] ContractNegotiation 5df554f0-969d-4a12-a775-d75716081b28 is now in state FINALIZING.
DEBUG 2023-11-06T14:47:53.083812751 ContractNegotiation: ID 5df554f0-969d-4a12-a775-d75716081b28. [Provider] send finalization
DEBUG 2023-11-06T14:47:53.133926044 ContractNegotiation: ID 5df554f0-969d-4a12-a775-d75716081b28. [Provider] send finalization
SEVERE 2023-11-06T14:47:53.134029945 ContractNegotiation: ID 5df554f0-969d-4a12-a775-d75716081b28. Fatal error while [Provider] send finalization. Error details: {"@type":"dspace:ContractNegotiationError","dspace:code":"400","dspace:reason":"Invalid client credentials: Invalid counter-party identity","dspace:processId":"993ea65b-cb9b-4b73-9d0e-f7220a0696b9","@context":{"dct":"https://purl.org/dc/terms/","edc":"https://w3id.org/edc/v0.0.1/ns/","dcat":"https://www.w3.org/ns/dcat/","odrl":"http://www.w3.org/ns/odrl/2/","dspace":"https://w3id.org/dspace/v0.8/"}}
DEBUG 2023-11-06T14:47:53.134145845 [PROVIDER] ContractNegotiation 5df554f0-969d-4a12-a775-d75716081b28 is now in state TERMINATED.
````

I never encountered this issue before. Both connectors are running on `v0.3.0`.

**Comment by FlorianFehrleIEE** [comment]
Is there anything new regarding this bug?
I am sitting on a project, where I need exactly this missing functionality, which leads to stalling of the project at the moment.

**Comment by ndr-brt** [comment]
wouldn't this be superseded by data-plane signaling? (https://github.com/eclipse-edc/Connector/issues/3704)

**Comment by jimmarino** [comment]
> wouldn't this be superseded by data-plane signaling? (#3704)

Yes, it should be.
