### ISSUE TITLE
ODRL policy transformation from json-ld fails on operator enum

### ISSUE THREAD

**Issue by FlorianWege-IESE** [eclipse-edc/Connector#3167]
# Bug Report

## Describe the Bug
The ODRL constraint transformer currently fails when trying to match expanded operator ids with the Java enum constants and with the case-sensitivity (e.g. matching "GT" instead of "gt").

### Expected Behavior
In accordance with the other context-aware transformation logic, the transformer should match the expanded forms to the Java enum constants correctly.

### Observed Behavior
An IllegalArgumentException is thrown: e.g. `No enum constant org.eclipse.edc.policy.model.Operator.http://www.w3.org/ns/odrl/2/gt`

## Steps to Reproduce
1. Make a consumer that accepts contract negotiation requests like in Transfer Sample 01: https://github.com/eclipse-edc/Samples/tree/main/transfer/transfer-01-file-transfer
2. Change the contractoffer.json to
```json
{
  "@context": {
    "edc": "https://w3id.org/edc/v0.0.1/ns/"
  },
  "@type": "NegotiationInitiateRequestDto",
  "connectorId": "provider",
  "consumerId": "consumer",
  "providerId": "provider",
  "connectorAddress": "http://localhost:8282/protocol",
  "protocol": "dataspace-protocol-http",
  "offer": {
    "offerId": "1:test-document:3a75736e-001d-4364-8bd4-9888490edb58",
    "assetId": "test-document",
    "policy": {
      "@context": [
        "http://www.w3.org/ns/odrl.jsonld",
        {
          "dc": "http://purl.org/dc/terms/",
          "ids": "https://w3id.org/idsa/core/",
          "idsc": "https://w3id.org/idsa/code/"
        }
      ],
      "@type": "Offer",
      "permission": [
        {
          "action": "use",
          "assigner": "http://example.com/party/my-party",
          "constraint": [
            {
              "leftOperand": "dateTime",
              "operator": "gt",
              "rightOperand": [
                {
                  "@type": "xsd:datetimeStamp",
                  "@value": "2023-06-12T10:11:00Z"
                }
              ]
            }
          ],
          "target": "http://my-party"
        }
      ],
      "profile": "http://example.com/odrl:profile",
      "uid": "https://w3id.org/idsa/autogen/contract/complex-policy-access"
    }
  }
}
```
including a policy with at least one constraint with an operator.
3. As described in the README.md of Transfer Sample 01, make a request to initiate a contract negotiation to call the `initiateContractNegotiation` method of the `ContractNegotiationApiController`, add some breakpoints there and particularly break on `java.lang.IllegalArgumentException`.

## Context Information
EDC version: https://github.com/eclipse-edc/Connector/releases/tag/v0.1.0

## Detailed Description
JSON-LD works with contexts, prefixing keys and certain values when expanding (and restructuring them, but that's already taken care of in the transformer). So for example, `"operator": "gt"` in the above policy becomes `"http://www.w3.org/ns/odrl/2/operator": [{"@id": "http://www.w3.org/ns/odrl/2/gt"}]`.

"http://www.w3.org/ns/odrl/2/gt" is the correct long id in the ODRL 2 vocabulary that should be matched against but, currently, the transformer would only work if the operator value after expansion was "GT" because it directly maps to the Java enum constant names.

## Possible Implementation
The problem lies here:

https://github.com/eclipse-edc/Connector/blob/e2e84ceeb88c1a981bd75848e5d9e8d0d1e6a1e4/extensions/common/json-ld/src/main/java/org/eclipse/edc/jsonld/transformer/to/JsonObjectToConstraintTransformer.java#L80

The code uses Java's java.lang.Enum.valueOf method, which requires the exact case-sensitive constant name. That condition must either be met with a preceding compaction/normalization or just match the long identifiers directly, e.g.,

```java
ODRL_GT_OPERATOR = ODRL_SCHEMA + "gt";
ODRL_LT_OPERATOR = ODRL_SCHEMA + "lt";
...

switch (s) {
    case ODRL_GT_OPERATOR: {
        return Operator.GT;
    }
    case ODRL_LT_OPERATOR: {
        return Operator.LT;
    }
    ...
}
```

**Comment by ndr-brt** [comment]
You're right, in fact ODRL defines the operator in lower case (or, better, snake case): 
https://www.w3.org/TR/odrl-vocab/#term-Operator
