### ISSUE TITLE
Move `runtime-metamodel` to its own repository

### ISSUE THREAD

**Issue by paullatzelsperger** [eclipse-edc/Connector#3181]
# Feature Request

The `runtime-metamodel` is currently embedded as module in the `GradlePlugins` repository, from where it should be relocated to its new home https://github.com/eclipse-edc/runtime-metamodel

## Which Areas Would Be Affected?
GradlePlugins, build, release

## Why Is the Feature Desired?
break dependency cycle, decouple Gradle plugins from the runtime metamodel

## Solution Proposal
move the code, adapt the build

**Comment by ndr-brt** [comment]
can this be closed?
