### ISSUE TITLE
Tests failed 

### ISSUE THREAD

**Issue by Silhim** [eclipse-edc/Connector#3191]
# Bug Report

## Describe the Bug
Tried to build the 0.1.0 edc connector but the  task :core:control-plane:catalog-core:test failed

- Used version edc v0.1.0
- OS: Ubuntu 22.04 LTS
- Java: openjdk version "17.0.7" 2023-04-18
- Javac: 17.0.7

## Detailed Description
```
root@vm2:/home/operation/edc_v0.1.0/Connector# ./gradlew build
Invalid Java installation found at '/usr/lib/jvm/openjdk-11' (Common Linux Locations). It will be re-checked in the next build. This might have performance impact if it keeps failing. Run the 'javaToolchains' task for more details.
Invalid Java installation found at '/usr/lib/jvm/openjdk-17' (Common Linux Locations). It will be re-checked in the next build. This might have performance impact if it keeps failing. Run the 'javaToolchains' task for more details.

> Task :core:control-plane:catalog-core:test
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended

DatasetResolverImplPerformanceTest > oneAssetPerDefinition(DatasetResolver, ContractDefinitionStore, AssetIndex, PolicyDefinitionStore) FAILED
    java.lang.AssertionError:
    Expecting actual:
      2.063462924S
    to be less than:
      1S
        at org.eclipse.edc.connector.catalog.DatasetResolverImplPerformanceTest.queryDatasetsIn(DatasetResolverImplPerformanceTest.java:108)
        at org.eclipse.edc.connector.catalog.DatasetResolverImplPerformanceTest.oneAssetPerDefinition(DatasetResolverImplPerformanceTest.java:76)

-----------------------------------------------------------------
|  Results: FAILURE (21 tests, 20 passed, 1 failed, 0 skipped)  |
-----------------------------------------------------------------


21 tests completed, 1 failed

> Task :core:control-plane:catalog-core:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':core:control-plane:catalog-core:test'.
> There were failing tests. See the report at: file:///home/operation/edc_v0.1.0/Connector/core/control-plane/catalog-core/build/reports/tests/test/index.html

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 39s
377 actionable tasks: 1 executed, 376 up-to-date
```

**Comment by ndr-brt** [comment]
definitely not a bug, the test is working both on our CI and on my local machine, and I guess it's the same for the other committers.
The issue could stay though to justify a separate label for the performance test, it wasn't introduced at the time for time constraints, but it could be the right moment to do so.
This won't solve the performance issue on your machine, but it will not run the test by default with the `./gradlew build` command

**Comment by paullatzelsperger** [comment]
I would be very cautious with performance tests of any sort. unless there is a defined test harness, and clearly formulated expectations, they are virtually pointless.

For example, saying "1000 requests take 3.4 seconds" has no meaning at all, unless we clearly define the test hardware and network setup, and unless there is a requirement that states "must be able to handle X amount of requests in Y amount of time, on Z type of hardware/network".

**Comment by Silhim** [comment]
Well, can I somehow skip the test?

**Comment by ndr-brt** [comment]
you can add the `@Disabled` annotation on it

**Comment by paullatzelsperger** [comment]
we will remove this specific test in a future PR, as we don't need it anymore

**Comment by ndr-brt** [comment]
After an agreement in the committer group, the test has been removed.
