### ISSUE TITLE
Problem when constructing `ContractId`s containing colons ":"

### ISSUE THREAD

**Issue by paullatzelsperger** [eclipse-edc/Connector#3211]
# Bug Report

## Describe the Bug
Having Assets where the `id` contains the ":" colon character causes problems during contract negotiation, causing the negotiation instance not to be found.

### Expected Behavior
(see link below)

### Observed Behavior
(see link below)

## Steps to Reproduce, Context Information
https://github.com/eclipse-tractusx/tractusx-edc/issues/484

## Detailed Description
`ContractId` instances are constructed in the form `<CONTRACT_DEF_ID>:<ASSET_ID>:<UUID>` using ":" as delimiter character and are parsed accordingly. If either the contract definition id or the asset id contains a colon ":" character, that would throw off the parsing algorithm.

## Possible Implementations
- make the delimiter configurable, default to ":"
- make `ContractIds` opaque, e.g. base64 encode the parts (<-- probably the best solution)

**Comment by ndr-brt** [comment]
I also agree on making the ContractId parts opaque with encoding, at that point we could remove the `:` validation on `ContractDefinition`. I can take care of this
