### ISSUE TITLE
Released 0.1.0 Jars Depend on `runtime-metamodel` in Version 0.1.0-SNAPSHOT

### ISSUE THREAD

**Issue by efiege** [eclipse-edc/Connector#3213]
# Bug Report

## Describe the Bug
The released 0.1.0 jars currently depend on the runtime-metamodel in version 0.1.0-SNAPSHOT. The SNAPSHOT- version does not seem to be available at the moment.

Here is an example output of the `gradle dependencies` task:
+--- org.eclipse.edc:data-plane-selector-core:0.1.0
|    +--- org.eclipse.edc:util:0.1.0 (*)
|    +--- org.eclipse.edc:data-plane-selector-spi:0.1.0 (*)
|    +--- org.eclipse.edc:connector-core:0.1.0 (*)
|    +--- org.eclipse.edc:boot:0.1.0 (*)
|    +--- org.jetbrains:annotations:24.0.1
|    +--- com.fasterxml.jackson.core:jackson-core:2.14.2 -> 2.15.1 (*)
|    +--- com.fasterxml.jackson.core:jackson-annotations:2.14.2 -> 2.15.1 (*)
|    +--- com.fasterxml.jackson.core:jackson-databind:2.14.2 -> 2.15.1 (*)
|    +--- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.14.2 -> 2.15.1 (*)
|    \--- org.eclipse.edc:runtime-metamodel:0.1.0-SNAPSHOT (*)

### Expected Behavior
Using runtime-metamodel in version 0.1.0 in the dependend jars.

**Comment by ndr-brt** [comment]
this was fixed with 0.1.1
