### ISSUE TITLE
DSP: catalog/datasets/{id} endpoint is not implemented

### ISSUE THREAD

**Issue by matgnt** [eclipse-edc/Connector#3220]
I couldn't find the endpoint in latest main branch. According to the spec, this is a mandatory endpoint:

https://github.com/International-Data-Spaces-Association/ids-specification/blob/main/catalog/catalog.binding.https.md#24-the-catalogdatasetsid-endpoint

It is especially important in cases we already know the asset / dataset id, e.g. from a AAS registry.

--
Matthias Binzer

**Comment by ndr-brt** [comment]
This is planned to be implemented during milestone 10

**Comment by matgnt** [comment]
Can you say something about timing of milestone 10? And which product-edc (tractus-x) this will end up?
Thanks,
Matthias

**Comment by ndr-brt** [comment]
The timing for Milestone 10 will be announced in the next days.

Talking about this issue, the Dataset id will be the same of the asset, and it could be used to retrieve the dataset with this endpoint.
