### ISSUE TITLE
Create Fluent Query API for AssetIndex etc.

### ISSUE THREAD

**Issue by paullatzelsperger** [eclipse-edc/Connector#323]
This is an improvement of the current `Criterion` that is used to submit queries. 

## Problem statement
The main problem with the Criterion API is that the user has to supply valid operators and operands. Valid as in "valid in the database's dialect". So the query syntax is dependent on the DB implementation.

For example, submitting an `"IN"`-query to an SQL-style DB would require the right-hand operand to be a valid list of values complete with brackets and commas, resulting in `someValue IN ('value1', 'value2', ...'valueN')`. 
In addition, the user needs to know the data type of the left-hand operand, because that influences, whether the single quotation marks are necessary or not.

## Proposition
In order to improve on that I propose an explicit query API with the following properties:
- offers a small but specific set of operands (e.g. `equals`, `in`, `gt`, `lt`, `geq`, `leq`)
- type safety: the type of the left-hand operand is known either through a schema or through a parameter, thus we can validate the operator and the right-hand operator
- fluent
- extensible: there is a possibility to supply "raw" queries, that are not checked and that is tunneled through to the data store more or less directly.
- serializable: makes it possible to transmit a query easily over the wire

### String Equals
```java
var query = QueryBuilder.newQuery()
                         .where("someProp").havingType(String.class)
                         .eq("someValue").build();
```

### String in 
```java
var query = QueryBuilder.newQuery()
                         .where("someProp").havingType(String.class)
                         .in("value1", "value2", "value3")
                         .build();
```
### Greater-Than with Schema
```java
org.eclipse.dataspaceconnector.spi.types.domain.schema.Schema schema = ...; //obtain Schema, e.g. from JSON Schema
var query = QueryBuilder.newQuery()
                         .where("someProp").havingSchema(schema)
                         .gt(420)
                         .build();
```

**Comment by jimmarino** [comment]
Nice and succinct +1
