### ISSUE TITLE
DSP catalog dataset @id fields are newly created for each request / response

### ISSUE THREAD

**Issue by matgnt** [eclipse-edc/Connector#3231]
![image](https://github.com/eclipse-edc/Connector/assets/198707/45b7725e-f024-4c1f-8c01-8cb8524a7fdb)

I think the DSP spec does not have this in mind with dataset ids. Also it makes caching almost impossible.
There is even an endpoint to fetch information for a specific dataset id.
https://github.com/International-Data-Spaces-Association/ids-specification/blob/main/catalog/catalog.binding.https.md#24-the-catalogdatasetsid-endpoint

(Version 0.1.0)

Can someone confirm this?

Thanks

--
Matthias Binzer

**Comment by ndr-brt** [comment]
This is not a bug, the `/dataset` endpoint is a missing feature that is supposed to be implemented in the milestone 10.

**Comment by matgnt** [comment]
Will the changing dataset ids disappear with the implementation of the new `/dataset` endpoint?

**Comment by ndr-brt** [comment]
To be honest IDK, this feature has not been discussed yet

**Comment by matgnt** [comment]
Reading the discussion again, the original report is about endpoint `/catalog/request`

We also rely on static dataset ids with other concepts where we put this dataset id into e.g. a AAS (asset administration shell) registry.

Does your comment here:
https://github.com/eclipse-edc/Connector/issues/3220#issuecomment-1609545232

mean that this will be changed, meaning make it static dataset ids, in milestone 10?
