### ISSUE TITLE
DSP dataset hasPolicy is supposed to be a list

### ISSUE THREAD

**Issue by matgnt** [eclipse-edc/Connector#3233]
Similar to issue #3232 also `hasPolicy` is an object, but should be a list.

DSP spec refs:
https://github.com/International-Data-Spaces-Association/ids-specification/blob/main/catalog/catalog.protocol.md#311-odrlhaspolicy
and see discussion here:
https://github.com/International-Data-Spaces-Association/ids-specification/issues/76

Version 0.1.0

**Comment by ndr-brt** [comment]
In the compacted form, for the ODRL specs, `hasPolicy` could be also just a string, please refer to the ODRL model https://www.w3.org/TR/odrl-model/

**Comment by matgnt** [comment]
I put this on the list to be discussed in the DSP meeting:
https://github.com/International-Data-Spaces-Association/ids-specification/issues/125

I didn't know this jsonld feature and I slowly understand why EUid Wallet and framework wants solutions wihtout jsonld ;-)

Thanks for the explanation!

Matthias

**Comment by matgnt** [comment]
@ndr-brt same here, also this is impacted by the decision in the spec meeting:

https://github.com/International-Data-Spaces-Association/ids-specification/issues/125#issuecomment-1612624447

It's not yet in the spec, but just as a heads-up
