### ISSUE TITLE
DSP: processId vs id in /negotiations/{id}/agreement endpoint

### ISSUE THREAD

**Issue by matgnt** [eclipse-edc/Connector#3241]
To my understanding, the `{id}` in the endpoint should be the value from the `CrontractRequestMessage` `@id` field, but it seems EDC expects the `processId`.

https://github.com/International-Data-Spaces-Association/ids-specification/blob/main/negotiation/contract.negotiation.binding.https.md#331-post

Can you please double check? Maybe this required some more clarifications in the spec, too.

Thanks

--
Matthias Binzer

**Comment by ndr-brt** [comment]
That endpoint is still not implemented in EDC, I think this issue should eventually be opened on the ids-specification repository.

To my understanding, it is correct though, because the `processId` identifies the negotiation id, while the `@id` in the `ContractRequestMessage` is the id of the message.

**Comment by matgnt** [comment]
It is implemented already and mandatory for the negotiation process. I think I'm talking about this endpoint here:
https://github.com/eclipse-edc/Connector/blob/e2e84ceeb88c1a981bd75848e5d9e8d0d1e6a1e4/data-protocols/dsp/dsp-negotiation/dsp-negotiation-api/src/main/java/org/eclipse/edc/protocol/dsp/negotiation/api/controller/DspNegotiationApiController.java#L274

**Comment by matgnt** [comment]
See @jimmarino comment here:
https://github.com/International-Data-Spaces-Association/ids-specification/issues/106#issuecomment-1571395535

But I agree, this is not very clear in the spec itself.

**Comment by ndr-brt** [comment]
> It is implemented already and mandatory for the negotiation process. I think I'm talking about this endpoint here:
> 
> https://github.com/eclipse-edc/Connector/blob/e2e84ceeb88c1a981bd75848e5d9e8d0d1e6a1e4/data-protocols/dsp/dsp-negotiation/dsp-negotiation-api/src/main/java/org/eclipse/edc/protocol/dsp/negotiation/api/controller/DspNegotiationApiController.java#L274

whoops, I missed that.
anyway this is not an EDC issue.

**Comment by matgnt** [comment]
No worries ;-)

On the matter, I think it is an EDC issue. The spec currently does NOT say that the `processId` is to be used here, it only talks about `id`. Or maybe I miss this part. Can you point me to the spec saying this?

**Comment by ndr-brt** [comment]
in the example in the specs you linked the id in the url path is equal to the `processId`:
https://github.com/International-Data-Spaces-Association/ids-specification/blob/main/negotiation/contract.negotiation.binding.https.md?plain=1#L224-L231

**Comment by matgnt** [comment]
Good point! I think this needs to be discussed in the IDS meeting. If you are right, we also should reflect this in the title of the section

https://github.com/International-Data-Spaces-Association/ids-specification/blob/d58a9ff0bec98d48825ed98325d45d316e17c834/negotiation/contract.negotiation.binding.https.md?plain=1#L216

```
### 3.3 The consumer `negotiations/:id/agreement` resource
```
vs.
```
### 3.3 The consumer `negotiations/:processId/agreement` resource
```

As pointed out in the original issue in the spec
https://github.com/International-Data-Spaces-Association/ids-specification/issues/106
I think the usage of the different id fields needs to be explained more in detail.

Based on @jimmarino reply there and what I read out from the section title and other text, I would still say `@id` is the correct one, but let's see what the others think about this.
