### ISSUE TITLE
TransferTerminationMessage sent even if no transfer process in remote connector was started

### ISSUE THREAD

**Issue by FlorianWege-IESE** [eclipse-edc/Connector#3247]
# Bug Report

## Describe the Bug

The code of [TransferProcessManagerImpl](https://github.com/eclipse-edc/Connector/blob/main/core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/process/TransferProcessManagerImpl.java) sends the termination message to remote connector even if no transfer process was created on the remote connector.

### Expected Behavior

If the transfer process did not reach a state where it sent a `TransferStartMessage` to the remote connector and was brought to `TERMINATED` state by early failure, there should be no `TransferTerminationMessage` sent to the remote connector either.

### Observed Behavior

A `TransferTerminationMessage` is sent to the remote connector, which yields an exception like
```
SEVERE 2023-06-29T15:53:06.7742266 org.eclipse.edc.spi.http.EdcHttpClientException: Server response to Request{method=POST, url=http://localhost:8282/protocol/transfers/9d717b80-ded7-4bfa-9b06-394be9a0b5ee/termination, headers=[Content-Type:application/json, Authorization:{"region":"eu","audience":"http://localhost:8282/protocol","clientId":"consumer"}]} was not successful but was 400: {"@context":{"@vocab":"https://w3id.org/edc/v0.0.1/ns/"},"@type":"https://w3id.org/dspace/v0.8/TransferError","https://w3id.org/dspace/v0.8/code":"400","https://w3id.org/dspace/v0.8/reason":["TransferProcess with DataRequest id 9d717b80-ded7-4bfa-9b06-394be9a0b5ee not found"],"https://w3id.org/dspace/v0.8/processId":"9d717b80-ded7-4bfa-9b06-394be9a0b5ee"}
```

## Steps to Reproduce

1. Set up the [transfer-01-file-transfer sample](https://github.com/eclipse-edc/Samples/tree/main/transfer/transfer-01-file-transfer) with a policy and change `managedResources` in `filetransfer.json` to `true`. This will make the consumer evaluate the policy in the initial step of the transfer process.
2. Make sure that the policy evaluation returns a failure result or just stop at https://github.com/eclipse-edc/Connector/blob/299951343985fc8296bf29920feefe1d770cf0e9/core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/process/TransferProcessManagerImpl.java#L305 in a debugger and make `manifestResult` failed so it takes the failure branch.
3. Wait for the scheduler to run the `processTerminating` handler method.
4. In the `processTerminating` handler method, it should send the `TransferTerminationMessage`.

## Context Information

EDC version: v0.1.2

## Detailed Description

A transfer process can be aborted by different means, which will first transition the state machine of the transfer process to the `TERMINATING` state before `TERMINATED` in order to clean up. There are different processors for the various states in `TransferProcessManagerImpl`. The one for `TERMINATING` tries to distinguish the cases whether the remote connector was notified of the transfer process yet or not. If there was no such notification, the state can be advanced right to `TERMINATED` and nothing else needs to be done, otherwise the code will send a termination message to the remote connector and react to the outcome of that.

## Possible Implementation

https://github.com/eclipse-edc/Connector/blob/299951343985fc8296bf29920feefe1d770cf0e9/core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/process/TransferProcessManagerImpl.java#L554

Since the `processTerminating` handler method would only be run when the process is in `TERMINATING` state, the comparison of the current state of the transfer process against the `REQUESTED` state is ineffective.

In lieu of that, have a second state variable remember if the remote connector was notified separately or know the previous state before it changed to `TERMINATING`?

**Comment by jimmarino** [comment]
We should not need additional state data or have transitions dependent on prior states, as that will indicate an error in the state machine design. Why can't the consumer transition directly to terminated?

**Comment by ndr-brt** [comment]
As soon as the `CONSUMER` reaches the `REQUESTED` state, it means that the `PROVIDER` has been already notified about the transfer, we just need to handle errors prior to the `REQUESTED` transitioning the transfer directly to `TERMINATED` without sending a message, in this case the fix needs to be made here:
https://github.com/eclipse-edc/Connector/blob/299951343985fc8296bf29920feefe1d770cf0e9/core/control-plane/transfer-core/src/main/java/org/eclipse/edc/connector/transfer/process/TransferProcessManagerImpl.java#L309

I can take care of this
