### ISSUE TITLE
DSP: TransferRequestMessage contains a processId, but should not (at least not according to the spec)

### ISSUE THREAD

**Issue by matgnt** [eclipse-edc/Connector#3253]
This is similar to #3241 in the negotiation process, but I think the messages and spec description is more clear in the transfer process.

https://github.com/International-Data-Spaces-Association/ids-specification/blob/d58a9ff0bec98d48825ed98325d45d316e17c834/transfer/transfer.process.protocol.md?plain=1#L102

```
Providers must include a `processId` property in the `TransferProcess` with a value set to the `@id` of the corresponding `TransferRequestMessage`.
```

Also, the examples for the `TransferRequestMessage` do NOT contain such a `processId` field.

EDC in the role of a consumer DOES add a `processId` to the `TransferRequestMessage` and consequently of course also expects the `TransferStartMessage` to contain exactly that as the `processId`

Independent of whether this is good or not in the spec, I think EDC is not compliant here right now.

Example EDC request message: (EDC 0.1.0 / product-edc 0.4.1)
```
{
    "@id": "9beead35-1136-4cf0-bb1a-12bd876efbfe",
    "@type": "dspace:TransferRequestMessage",
    "dspace:agreementId": "02e00787-08d2-4dc2-adfd-98a336170fda:3b3dd386-cb06-4906-9bf0-c2951a6ae381:ab910320-4d31-49be-808b-cb512464efb7",
    "dct:format": "HttpProxy",
    "dspace:callbackAddress": "http://consumer-control-plane:8282/api/v1/dsp",
    "dspace:processId": "ffe09988-97bc-433e-9755-893509e4987c",
    "@context": {
        "dct": "https://purl.org/dc/terms/",
        "tx": "https://w3id.org/tractusx/v0.0.1/ns/",
        "edc": "https://w3id.org/edc/v0.0.1/ns/",
        "dcat": "https://www.w3.org/ns/dcat/",
        "odrl": "http://www.w3.org/ns/odrl/2/",
        "dspace": "https://w3id.org/dspace/v0.8/"
    }
}
```

--
Matthias Binzer

**Comment by ndr-brt** [comment]
definitely a leftover in the specs, the message `@id` represents the message itself (mainly for idempotency), while the `processId` represents the whole process, and it's shared between the two parts.
This issue should be opened on the [ids-specification](https://github.com/International-Data-Spaces-Association/ids-specification) repo.
