### ISSUE TITLE
Avoid temporary file when loading cached Json-LD schema document

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-edc/Connector#3284]
# Feature Request

Currently to load a cached document for the jsonld service, we copy the file from the classpath to a temporary place: 
https://github.com/eclipse-edc/Connector/blob/60957b2fc5b9a63497cf08157b70fc05a56406b7/extensions/common/json-ld/src/main/java/org/eclipse/edc/jsonld/JsonLdExtension.java#L104-L117

this could be avoided passing the URI directly

## Which Areas Would Be Affected?

json-ld service

## Why Is the Feature Desired?

simplification

ref @wolf4ood

**Comment by bscholtes1A** [comment]
This means that in tests going through this code we will fetch a file from an URL?

**Comment by ndr-brt** [comment]
> This means that in tests going through this code we will fetch a file from an URL?

no, the cache behavior will continue to be the same, but currently (as shown in the code fragment in the issue description) to load the cached document, a temporary file is created, but it is an unnecessary step that could be avoided.
