### ISSUE TITLE
`Binder` in `JerseyRestService` binds resource instances from other contexts

### ISSUE THREAD

**Issue by pneuschwander** [eclipse-edc/Connector#3312]
# Bug Report

## Describe the Bug

`Binder` in `JerseyRestService` binds resource instances from other contexts.

### Expected Behavior

`Binder` in `JerseyRestService` binds resource instances only from the correct (single) context.

### Observed Behavior

`Binder` in `JerseyRestService` binds resource instances from other contexts.

## Context Information

Bug in EDC version 0.1.3 still present, observed with sovity edc community edition connector version 4.0.1 that is using EDC in a 0.0.1 version.

I noticed ` The /check/* endpoint has been moved under the 'management' context, please update your url accordingly, because this endpoint will be deleted in the next releases` in the logs even though that they use the check endpoint on the management API in the docker image.

=> The wrong ObservabilityApiController instance (that one of the default context with the deprecated=true parameter) was bound to the management context/servlet.

## Detailed Description

``` java
private class Binder extends AbstractBinder {

        @Override
        protected void configure() {
            controllers.forEach((key, value) -> value.forEach(c -> bind(c).to((Class<? super Object>) c.getClass())));
        }
    }
```

https://github.com/eclipse-edc/Connector/blob/main/extensions/common/http/jersey-core/src/main/java/org/eclipse/edc/web/jersey/JerseyRestService.java#L116

`controllers` is the Map<String, List<Object>> that holds the resources of all the contexts. The Key of the entries is the contextAlias.

The logic of the binder binds resources of any context but should only bind the resources of the correct, single context.

## Possible Implementation

We could provide the resources/controllers of the context to the binder via ctor parameter in this line easily: https://github.com/eclipse-edc/Connector/blob/main/extensions/common/http/jersey-core/src/main/java/org/eclipse/edc/web/jersey/JerseyRestService.java#L91

as the resources/controllers are available as `controllers` in this scope. We could have an attribute `List<Object> controllers` in the `Binder` class and make it a static inner class as we would no longer use the controllers-Map from the outer class.

Or we could provide the contextAlias via ctor parameter to the Binder and change the implementation to only consider those entries of `controllers.get(contextAlias).forEach` in this line: https://github.com/eclipse-edc/Connector/blob/main/extensions/common/http/jersey-core/src/main/java/org/eclipse/edc/web/jersey/JerseyRestService.java#L116

**Comment by efiege** [comment]
Just for clarification: Version 4.0.1 does not include the latest changes of the core-EDC. It still uses the milestone-8-Extensions, as we are currently migrating to the 0.1.3 version.

**Comment by ndr-brt** [comment]
thanks for reporting, PR is on the way
