### ISSUE TITLE
permit Titanium JsonLD `compactArrays` property configuration

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-edc/Connector#3323]
# Feature Request

As reported in various issues as:
- https://github.com/eclipse-edc/Connector/issues/3137
- https://github.com/eclipse-edc/Connector/issues/3232
- https://github.com/eclipse-edc/Connector/issues/3233
(this issue will supersede them)

Seems that it would be useful for some users to have the jsonld array not compacted by default when they have a single entry.
To solve this, we could set `compactArrays` to false by default, leaving the possibility to enable it with a configuration setting.

However, just for the record, the rule of thumb is to always expand a json-ld before processing it, because the compaction process can have different outputs.

## Which Areas Would Be Affected?

json-ld extension

**Comment by juliapampus** [comment]
As [decided in the DSP group](https://github.com/International-Data-Spaces-Association/ids-specification/issues/125#issuecomment-1612624447), an array with only one item should never be compacted to an object on the DSP layer. Thus, the current behaviour needs to be changed, and the requested configuration should only apply to EDC-specific APIs.

**Comment by florianrusch-zf** [comment]
Still an open point. We discovered this also in the catalog regarding the `distribution` field. We received an object instead of an array. We also looked into the swagger documentation, where is pointed out, that the `distribution` should be an array, also if only one object is within the array.

From the [swagger docu for 0.5.3](https://app.swaggerhub.com/apis/eclipse-tractusx-bot/tractusx-edc/0.5.3#/Catalog/requestCatalog):
```json
"dcat:distribution": [
      {
        "@type": "dcat:Distribution",
        "dct:format": {
          "@id": "HttpData"
        },
        "dcat:accessService": "5e839777-d93e-4785-8972-1005f51cf367"
      }
    ]
```

From an 0.5.3 EDC catalog request:
```json
            "dcat:distribution": {
                "@type": "dcat:Distribution",
                "dct:format": {
                    "@id": "HttpProxy"
                },
                "dcat:accessService": "812ea4ba-d691-4926-a191-d34f25780032"
            },
```

**Comment by ndr-brt** [comment]
@florianrusch-zf in fact the two representation you pasted are equivalent for the json-ld specs. the committer group decided that this issue is not so important to be put in a milestone, the general suggestion is to always expand the json-ld response body before processing (as this [typescript client](https://github.com/Think-iT-Labs/edc-connector-client) and this [java client](https://github.com/Think-iT-Labs/edc-connector-client-java) do).

anyway, we're open for contributions, feel free to provide one.
