### ISSUE TITLE
Vulnearable base image in readme

### ISSUE THREAD

**Issue by SebastianOpriel** [eclipse-edc/Connector#3333]
https://github.com/eclipse-edc/Connector/blob/de80081d547c66f127dd32e1a8b27d9fca2d4410/extensions/common/api/api-observability/README.md?plain=1#L61

https://hub.docker.com/layers/library/openjdk/17.0.1-jdk-slim/images/sha256-565d3643a78a657ca03e85c110af9579a07e833d6bcc14f475249c521b5c5d74

**Comment by bearn01d** [comment]
Besides: _"This image is officially deprecated and all users are recommended to find and use suitable replacements ASAP."_

Apart from Early Access builds, this image is deprecated for some time now. eclipse-temurin is an official image that can be used as a replacement and is available as -jre and -jdk, based on the needs (also suggested on the openjdk image page).

In my projects I experienced no noteworthy issues after switching.

**Comment by paullatzelsperger** [comment]
we will remove the lines for the recommended base image and the `RUN` command.
