### ISSUE TITLE
Global DataSource configuration

### ISSUE THREAD

**Issue by jimmarino** [eclipse-edc/Connector#3337]
# Feature Request

We should provide the ability to set global data source settings for all JDBC-related extensions. If data source settings are not configured for a particular extension, it can default to global settings, if available:

edc.datasource.global.name=
edc.datasource. global.user=
edc.datasource. global.password=
edc.datasource. global.url=

Note we should add a Decision Record to document this.

## Which Areas Would Be Affected?

All JDBC features

## Why Is the Feature Desired?

Ease-of-use

**Comment by ndr-brt** [comment]
maybe it could be called `default` as we did with web contexts.
