### ISSUE TITLE
rename `providerUrl` and `connectorAddress` to `counterPartyAddress` on management api

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-edc/Connector#3343]
# Feature Request

Currently there are multiple way of calling the same field: `counterPartyAddress` as it was called in the internal domain model (`RemoteMessage` included) is also called `providerUrl` and `connectorAddress`.

## Which Areas Would Be Affected?

management api

## Why Is the Feature Desired?

consistency

## Solution Proposal

we should need to avoid breaking changes, printing a log in the case the old name is used, as done in #3342

**Comment by saschaisele-zf** [comment]
Will start working on this issue next.
@ndr-brt you can assign me here.
Getting the contributer role in this repo might be beneficial for me in the future so I can do this myself.
