### ISSUE TITLE
`StoreResult` supports the `map()` operator but fails with an exception

### ISSUE THREAD

**Issue by paullatzelsperger** [eclipse-edc/Connector#3353]
# Bug Report

## Describe the Bug

Attempting to invoke `StoreResult#map()` fails with an `UnsupportedOperationException`, because the `map()` operator internally invokes `AbstractResult#newInstance()`, which by default throws that exception and `StoreResult` does not override it.

### Expected Behavior

`StoreResult#map()` works like `ServiceResult#map()` for example

## Context Information

_Add any other context about the problem here._

- Used version: EDC `0.2.0`, bug is still present in `0.2.1-SNAPSHOT` (Aug 3, 2023)

## Detailed Description

_If applicable, add screenshots and logs to help explain your problem._

## Possible Implementation

- override `AbstractResult#newInstance()`

**Comment by ndr-brt** [comment]
maybe the time has come to make that method abstract so then every extender class will be forced to provide their own implementation
