### ISSUE TITLE
Policy ID can be null

### ISSUE THREAD

**Issue by florianrusch-zf** [eclipse-edc/Connector#3361]
# Bug Report
## Describe the Bug

When creating a policy definition, it is possible to pass a blank string consisting of only whitespaces. This leads to the creation of a policy without any ID which of course again leads to multiple issues, e.g. it's not possible to fetch or manipulate this specific policy.

### Expected Behavior

No possibility of creating a policy with blank id field.

## Steps to Reproduce

1. Create a policy POST /policydefinitions with blank id (only whitespaces)
2. Fetch the policy list -> null on id field

![image](https://github.com/eclipse-edc/Connector/assets/97295414/5f3812b2-c63b-4e39-9e8f-7fd582465210)

## Context Information

Discovered by using the Management API in version 0.1.3

## Possible Implementation

- Trim all whitespaces from **ALL** fields
- Correct validation

## Additional

I haven't check if also other endpoints/resources are affected by this bug (e.g. asset, contract definition, ...). Maybe it's valuable to double check them as well while implementing the fix.

**Comment by ndr-brt** [comment]
This has already been fixed in version 0.2.0 with the introduction of the request validation: 
https://github.com/eclipse-edc/Connector/pull/3189

**Comment by florianrusch-zf** [comment]
Okay, we will double check with the newest version in the next days

**Comment by wolf4ood** [comment]
@florianrusch-zf  can this be closed? 

I tried with >= `0.2.0` and works as expected with a validation error

**Comment by ndr-brt** [comment]
Closing it as it has been verified to be fixed.
