### ISSUE TITLE
Extensible property in Policy are not readable

### ISSUE THREAD

**Issue by wolf4ood** [eclipse-edc/Connector#3385]
# Bug Report

## Describe the Bug

Policies supports additional/custom properties in the field `Policy#extensibleProperties`, which can be populated via management API with post like this

```json
{
  "@context": {
  },
  "@type": "PolicyDefinitionRequest",
  "@id": "{{POLICY_ID}}",
  "policy": {
    "@type": "Set",
    "@context": "http://www.w3.org/ns/odrl.jsonld",
    "custom": "test",
    "permission": [
      {
        "action": "use",
        "constraint": [
          {
            "leftOperand": "foo",
            "operator": "eq",
            "rightOperand": "bar"
          }
        ]
      }
    ]
  }
}
```

But then it's not possible to read again the custom properties in PolicyDefinition API and  ContractAgreement API

### Expected Behavior

Be able to read the custom properties via PolicyDefinition API and ContractAgreement API

## Possible Implementation

The  `JsonObjectFromPolicyTransformer` does not transform the field `Policy#extensibleProperties`

**Comment by jimmarino** [comment]
This is a really old feature. Is there a need for it now?

**Comment by wolf4ood** [comment]
We actually  support writing but not reading, if it's a feature it's not working as expected :sweat_smile: 
Yes someone asked if they could attach properties to policies

**Comment by gkirtzou** [comment]
Hello, 
are there any plans for adding the functionality of retrieving the data stored in the extensible properties? It would be especially useful, for policies deriving from standards licences.
