### ISSUE TITLE
refactor: remove `TransferProcess` `connectorId`

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-edc/Connector#3396]
# Feature Request

Currently, both `TransferRequest` and `DataRequest` objects contain this `connectorId` that's actually not used by anyone, it's not needed, because the counter-party id it's stored in the `ContractAgreement`, so `connectorId` can be removed

## Which Areas Would Be Affected?

transfer process

## Why Is the Feature Desired?

cleanup

## Solution Proposal

_If possible, provide a (brief!) solution proposal._

**Comment by salmansharifov** [comment]
Hi @ndr-brt Can I take over this issue? T

**Comment by ndr-brt** [comment]
sure! I just assigned it to you. thanks

**Comment by ndr-brt** [comment]
@magork the issued was assigned to @salmansharifov , why don't sync with him first?

**Comment by magork** [comment]
Hi This is my first time when I contribute. I am expecting that what I have done is not enough and still should do further changes. Hi @salmansharifov could we connect?

**Comment by ndr-brt** [comment]
As I wrote in the PR, I suggest to read through the [CONTRIBUTING](https://eclipse-edc.github.io/docs/#/submodule/GitHub/CONTRIBUTING) guide, as a rule of thumb this is something should be done before starting contributing to every project.

**Comment by salmansharifov** [comment]
Hi @magork , if you have already working branch, you can create pr.

**Comment by magork** [comment]
Hi @salmansharifov Sorry to answer late but I where on a trip and I didn't have my laptop. 
So I forked the project and made some changes in those classes but jobs are failing. Could we connect and discuss in more detail the required changes which are needed?

**Comment by ndr-brt** [comment]
Hey @salmansharifov are you gonna work on it? otherwise I will remove the assignment
