### ISSUE TITLE
Change contract dates to UTC epoch date

### ISSUE THREAD

**Issue by juliapampus** [eclipse-edc/Connector#341]
Dates should be UTC epoch date. At least in the following classes: `ContractNegotiationManagerImpl`, `ProviderContractNegotiationManagerImpl`, `ContractValidationServiceImpl`, `ContractValidationServiceImplTest`, `ArtifactRequestHandler`

**Comment by jimmarino** [comment]
- ContractOffer ZonedDateTime fields need to be converted to UTC timestamps

- IdsContractRequestToContractOfferTransformer and IdsResourceCatalogToDataCatalogTransformer need to convert received XMLGregorianCalendar to UTC, not zoned date times

- Cleanup dead ZonedDateTime imports (e.g. ContractAgreement)

- Seeing that IDS uses XMLGregorianCalendar, ContractOffer and ContractAgreement should have millisecond resolution, not day resolution. The corresponding fields need to be updated and renamed; 

- Update ContractValidationServiceImplTest, TestFunctions, InMemoryContractNegotiationStoreTest for consistency

@juliapampus do you have this underway or can I submit a PR?

**Comment by juliapampus** [comment]
You can open a PR if you want @jimmarino

**Comment by juliapampus** [comment]
ContractOfferFromIdsContractOfferOrRequestTransformer
