### ISSUE TITLE
Missing Headers to use for querying a backend (Proxypass headerParams)

### ISSUE THREAD

**Issue by kris-mart** [eclipse-edc/Connector#3413]
# Bug Report

## Describe the Bug

We need to pass non-static header-params to the sourcesystem similar to path.
In IDS it was implemented.

### Expected Behavior

_A clear and concise description of what you expected to happen._
Similar to IDS (https://github.com/FraunhoferISST/DataspaceConnector/blob/main/src/main/java/io/dataspaceconnector/common/net/QueryInput.java) there should be a option to pass headers to be proxied.

### Observed Behavior

In BaseSourceHttpParamsDecorator there is only Method, Path, Params, ContentType, Body proxied.

## Steps to Reproduce

Try to pass dynamic header parameter to source-system.

## Possible Implementation

Simple solution for BaseSourceHttpParamsDecorator.decorate would look like this:
		if (request.getProperties().containsKey("**headerParams**")) {
			for (String entry : request.getProperties().get("**headerParams**").split(",")) {
				int indexSep = entry.indexOf("=");
				**params.header**(entry.substring(0, indexSep).trim(), entry.substring(indexSep + 1).trim());
			}
		}

**Comment by jimmarino** [comment]
This is not a bug. 

The DPF should not by default randomly pass parameters like this on all requests. If you want this behavior, you can implement a custom `HttpParamsDecorator` and register it with `HttpRequestParamsProvider`.

**Comment by paullatzelsperger** [comment]
@kris-mart To be extra-crystal-clear on this: such a customization would need to be hosted in your fork of EDC or your downstream repo.
Blindly forwarding/tunneling HTTP headers through the data plane can have several adverse side effects, security and degradation of service are only the most obvious ones.

**Comment by bjungs** [comment]
Hello all!

I've come across a similar use-case but in my case I've setup an `HttpProxy` destination and would like to forward the headers from the proxied request down to the destination.

This behavior seems to be controlled by the `DataPlanePublicApiController` toself though the `DataFlowRequestSupplier` component (`createProps` method). Is there a way for me to extend this behavior to include the header I need?

**Comment by jimmarino** [comment]
> Hello all!
> 
> I've come across a similar use-case but in my case I've setup an `HttpProxy` destination and would like to forward the headers from the proxied request down to the destination.
> 
> This behavior seems to be controlled by the `DataPlanePublicApiController` itself through the `DataFlowRequestSupplier` component (`createProps` method). Is there a way for me to extend this behavior to include the header I need?

Hi, if you want to do this, create your own controller/API to convert headers from an expected form to properties on the `DataAddress`.
