### ISSUE TITLE
Possibly wrong example body in API specification for registering dataplanes

### ISSUE THREAD

**Issue by Julian-Marco** [eclipse-edc/Connector#3421]
# Bug Report

## Describe the Bug

Given the current API specificiation (https://app.swaggerhub.com/apis/eclipse-edc-bot/management-api/0.2.1#/Dataplane%20Selector/addEntry), the endpoint for registering new dataplanes is /management/v2/dataplanes. There is also an example JSON body given that looks like this: 

```
{
  "@id": "your-dataplane-id",
  "url": "http://somewhere.com:1234/api/v1",
  "allowedSourceTypes": [
    "source-type1",
    "source-type2"
  ],
  "allowedDestTypes": [
    "your-dest-type"
  ]
}
```

Sending the POST request with the given body (or any other body) yields a 400 error though, which apparently means that the body was malformed. 

![error](https://github.com/eclipse-edc/Connector/assets/93761466/76e6721a-8218-4841-85da-225a9d264b3b)

So there could either be an error in the underlying implementation or the example body given is wrong. 

Can someone help me out?

**Comment by ndr-brt** [comment]
it surely miss the `@context` part, mandatory in a json-ld object

**Comment by Julian-Marco** [comment]
You're right, thanks! So the example body should actually look more like this: 

```
{
  "@context": {
   "edc": "https://w3id.org/edc/v0.0.1/ns/"
  },
  "@id": "your-dataplane-id",
  "url": "http://somewhere.com:1234/api/v1",
  "allowedSourceTypes": [
    "source-type1",
    "source-type2"
  ],
  "allowedDestTypes": [
    "your-dest-type"
  ]
}
```
