### ISSUE TITLE
Asset query service - JSON

### ISSUE THREAD

**Issue by galanisd** [eclipse-edc/Connector#3423]
# Bug Report

## Describe the Bug

Asset query service does not work in all cases when the property_value is a JSON.
See example in https://github.com/eclipse-edc/Connector/discussions/3416

### Expected Behavior

See https://github.com/eclipse-edc/Connector/discussions/3416

### Observed Behavior

See https://github.com/eclipse-edc/Connector/discussions/3416

## Steps to Reproduce

See https://github.com/eclipse-edc/Connector/discussions/3416

## Context Information

_Add any other context about the problem here._

- Used version -> EDC v0.2.1

## Detailed Description

See https://github.com/eclipse-edc/Connector/discussions/3416

**Comment by arnoweiss** [comment]
I've observed the same behavior.

**Comment by ndr-brt** [comment]
I think the best way to solve this would be to switch the asset properties from the dedicated table we have to a `properties` and `privateProperties` json column in the asset table, this way we would enable querying nesting objects.

Currently a maybe good enough workaround would be to use the `LIKE` operator, as the json is serialized as a string.
