### ISSUE TITLE
Make log level of slf4j logger configurable

### ISSUE THREAD

**Issue by iwasakims** [eclipse-edc/Connector#3451]
# Feature Request

## Which Areas Would Be Affected?

boot, monitor

## Why Is the Feature Desired?

We can not get log of underlying libraries using slf4j if the log level is equal to or smaller than INFO [since the log level of slf4j logger is hard coded](https://github.com/eclipse-edc/Connector/blob/7c109a8696404759700bb43e20b61c9bb9afb188/core/common/boot/src/main/java/org/eclipse/edc/boot/monitor/MonitorProvider.java#L67C26-L142).

It is inconvenient for developing modules depending on libraries using slf4j. [Technology-Aws](https://github.com/eclipse-edc/Technology-Aws) depending on AWS SDK is the example.

We can not temporalily use another binding like slf4j-simple if [MonitorProvider](https://github.com/eclipse-edc/Connector/blob/7c109a8696404759700bb43e20b61c9bb9afb188/core/common/boot/src/main/java/org/eclipse/edc/boot/monitor/MonitorProvider.java) is in the classpath. Since the MonitorProvider is provided by org.eclipse.edc:boot, most of the code depending on EDC could be affected.

```
S3DataPlaneIntegrationTest STANDARD_ERROR
    SLF4J: Class path contains multiple SLF4J providers.
    SLF4J: Found provider [org.eclipse.edc.boot.monitor.MonitorProvider@47c64cfe]
    SLF4J: Found provider [org.slf4j.simple.SimpleServiceProvider@6ce90bc5]
    SLF4J: See https://www.slf4j.org/codes.html#multiple_bindings for an explanation.
    SLF4J: Actual provider is of type [org.eclipse.edc.boot.monitor.MonitorProvider@47c64cfe]
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
```

## Solution Proposal

Making the log level of slf4j logger configurable [as done for slf4j-simple](https://www.slf4j.org/apidocs/org/slf4j/simple/SimpleLogger.html).

Making the feature opt-in could be an option. If the feature is enabled by loading the extension, EDC Config is available on `initialize`. Modules not loading BaseRuntime (e.g. Technology-AWS) can use alternative slf4j binding during development.

**Comment by paullatzelsperger** [comment]
AFAIR the `MonitorProvider` was added a long time ago to satisfy some transitive dependency. Do we even need it anymore or can we remove it? 
That would mean that people can just register their downstream implementation of a `Monitor`, e.g. an `Slf4jMonitor`.

**Comment by iwasakims** [comment]
I submitted #3463 which removes the `MonitorProvider` from the code path of `BaseRuntime`. The SLF4J-Monitor bridge feature still could be  useful for users of  existing monitor like `LoggerMonitorExtension` to make log destination settings simple.

**Comment by iwasakims** [comment]
I'm updating the PR to remove the bridge then.

> That's the reason why PRs should only raised once issues are out of triage: getting clarity on the desired implementation.

Seeing the code change should be effective to make the issue clear and affected scope clear in this case. I needed some action before the issue is auto-closed without update for a week.
