### ISSUE TITLE
JSON-LD "@context" using slightly different URLs than DCAT3

### ISSUE THREAD

**Issue by richardtreier** [eclipse-edc/Connector#3458]
# Bug Report

## Describe the Bug

Hello, we are currently experiencing slight discrepancies between the produced `"@context"` objects and the DCAT 3 Specification.

These discrepancies are unproblematic for human readers of the API Responses, but become problem when trying to read the JSON-LD semantically.

We bumped into this issue during our migration of asset metadata to the DCAT standard and are thus handling JSON-LD semantically, rather than just accessing json properties randomly, such as "dcat:version".

If I understand correctly, the namespaces are just a document-specific shorthand and not reserved terms unlike the expanded terms.

### Expected Behavior

The DCAT 3 Vocabulary definition page [defines some namespace URLs](https://www.w3.org/TR/vocab-dcat-3/#normative-namespaces):

For example: `http://www.w3.org/ns/dcat#` for `dcat`.

### Observed Behavior

API results from the EDC Connector return slightly different URLs in their `"@context"` objects: [`Namespaces.java`](https://github.com/eclipse-edc/Connector/blob/main/spi/common/json-ld-spi/src/main/java/org/eclipse/edc/jsonld/spi/Namespaces.java#L23)

For example:  `https://www.w3.org/ns/dcat/` for `dcat`

Here the trailling `#` became a `/` while the protocol was changed to `https`.

This would mean that `http://www.w3.org/ns/dcat#version` would become `https://www.w3.org/ns/dcat/version` and that `http://www.w3.org/ns/dcat#dataset` is currently `https://www.w3.org/ns/dcat/dataset`.

## Steps to Reproduce

Catalog API Response, for example.

## Detailed Description

After having asked on the issue in the Bi-weekly Discord call I was recommended to open an issue.

**Comment by VladimirAlexiev** [comment]
@ndr-brt The `dct` namespace is also wrong.
See https://github.com/sovity/edc-ce/discussions/1077, 
or more detail at https://github.com/underpin-project/model/blob/main/dcat#dataspace-catalog-response (with saved files, conversion commands, images)

**Comment by ndr-brt** [comment]
@VladimirAlexiev could you file a proper issue/discussion?
