### ISSUE TITLE
The HashiCorp Vault Secret resolution only returns a Secret or Null

### ISSUE THREAD

**Issue by awellnitz-materna** [eclipse-edc/Connector#3462]
As a developer, it's easy to get stuck here because if the access token to the Vault lacks permissions or is incorrect, it either returns a Secret or nothing.
https://github.com/eclipse-edc/Connector/blob/258a31190a9c837606c2e327fe4dd5e54f3f1921/extensions/common/vault/vault-hashicorp/src/main/java/org/eclipse/edc/vault/hashicorp/HashicorpVault.java#L42

In the case of a 403 error, it would also be helpful to pass along this message so that you can handle the respective errors afterward.

What are your thoughts on this?

**Comment by jimmarino** [comment]
The vault implementation should send a message to the `Monitor` indicating the type of problem but continue to return null or the value.

**Comment by alexohneander** [comment]
I will provide a **PR** for this. @ndr-brt

**Comment by awellnitz-materna** [comment]
I will provide a PR for this. @ndr-brt
