### ISSUE TITLE
Gradle refresh fails in IntelliJ

### ISSUE THREAD

**Issue by hamidonos** [eclipse-edc/Connector#3464]
# Bug Report

When the rootProject.name property doesn't match the root directory name IntelliJ fails to update/refresh the project.

java.lang.IllegalStateException: Module entity with name: connector should be available

### Expected Behavior

Gradle Refresh works

### Environment

- OS: MacOS

## Possible Implementation

change the rootProject.name property to 'Connector' instead of 'connector' 
or change project name to 'connector'

**Comment by hamidonos** [comment]
preferably we change the repository name to 'connector' as names should be lowercase anyway
tho I'm not sure if this will break anything elsewhere

**Comment by jimmarino** [comment]
We are not going to rename the repository. This sounds like a local configuration problem and not something caused by EDC as many of us use IntelliJ. Please check your local configuration and if you have to, check the repository out using a different directory name.
