### ISSUE TITLE
field transferProcessApiClient was not provided

### ISSUE THREAD

**Issue by Julian-Marco** [eclipse-edc/Connector#3465]
# Bug Report

## Describe the Bug

When building our current EDC based the latest release version ``v0.3.0``, I encounter the following error: 

``INFO 2023-09-22T11:29:22.385916547 Initialized FS Configuration
SEVERE 2023-09-22T11:29:22.601488109 Error booting runtime: The following injected fields were not provided: Field "transferProcessApiClient" of type [interface org.eclipse.edc.connector.api.client.spi.transferprocess.TransferProcessApiClient] required by org.eclipse.edc.connector.dataplane.framework.DataPlaneFrameworkExtension
org.eclipse.edc.spi.system.injection.EdcInjectionException: The following injected fields were not provided:
Field "transferProcessApiClient" of type [interface org.eclipse.edc.connector.api.client.spi.transferprocess.TransferProcessApiClient] required by org.eclipse.edc.connector.dataplane.framework.DataPlaneFrameworkExtension
        at org.eclipse.edc.boot.system.DependencyGraph.of(DependencyGraph.java:102)
        at org.eclipse.edc.boot.system.ExtensionLoader.loadServiceExtensions(ExtensionLoader.java:119)
        at org.eclipse.edc.boot.system.runtime.BaseRuntime.createExtensions(BaseRuntime.java:151)
        at org.eclipse.edc.boot.system.runtime.BaseRuntime.boot(BaseRuntime.java:201)
        at org.eclipse.edc.boot.system.runtime.BaseRuntime.boot(BaseRuntime.java:84)
        at org.eclipse.edc.boot.system.runtime.BaseRuntime.main(BaseRuntime.java:72)
``

Everything works fine on the former version ``v0.2.1`` though. So I suppose there are some inconsistencies between the respective modules. I guess it has something to do with one of these (from our build.gradle.kts):

````
implementation("$edcGroupId:data-plane-core:$edcVersion")
implementation("$edcGroupId:data-plane-api:$edcVersion")

implementation("$edcGroupId:data-plane-selector-core:$edcVersion")
implementation("$edcGroupId:data-plane-selector-client:$edcVersion")
implementation("$edcGroupId:data-plane-selector-api:$edcVersion")

implementation("$edcGroupId:transfer-data-plane:$edcVersion")
```` 

Does the error message hint at something being wrong with the data-plane-framework artifact? Because this is indeed still tagged with the older version: 

https://central.sonatype.com/artifact/org.eclipse.edc/data-plane-framework

**Comment by wolf4ood** [comment]
Hi @Julian-Marco thanks for raising this. 

You should add `control-plane-api-client` as deps in your dataplane distribution. Previously the component had some default implementation which has been removed [here](https://github.com/eclipse-edc/Connector/pull/3440)

**Comment by Julian-Marco** [comment]
Thank you very much, now it works!
