### ISSUE TITLE
Swaggerhub create asset v3 example not working as is

### ISSUE THREAD

**Issue by saschaisele-zf** [eclipse-edc/Connector#3476]
## Describe the bug

When using the Swaggerhub example for the asset creation on the v3 API you will get a `400 Bad Request` response.
Error message says `DataAddress of type HttpData must contain a valid baseUrl: null`

### To Reproduce

Try to create an asset with the following sample:
```JSON
{
  "@context": {
    "edc": "https://w3id.org/edc/v0.0.1/ns/"
  },
  "@id": "asset-id",
  "properties": {
    "key": "value"
  },
  "privateProperties": {
    "privateKey": "privateValue"
  },
  "dataAddress": {
    "type": "HttpData"
  }
}
```

### Expected behavior

A `201` response and an created asset.

## Possible Implementation

Add the `"baseUrl": "URL"` to the sample to make it valid.

```JSON
{
  "@context": {
    "edc": "https://w3id.org/edc/v0.0.1/ns/"
  },
  "@id": "5",
  "properties": {
    "key": "value"
  },
  "privateProperties": {
    "privateKey": "privateValue"
  },
  "dataAddress": {
    "type": "HttpData",
    "baseUrl": "https://jsonplaceholder.typicode.com/todos"
  }
}
```

**Comment by wolf4ood** [comment]
Hey @saschaisele-zf 

thanks for raising this. If you have some time could you please provide a fix for this? :)
