### ISSUE TITLE
Adoption Request: Extend Contract Definition entity with Private Properties

### ISSUE THREAD

**Issue by mohannad-ezzo** [eclipse-edc/Connector#3490]
# Adoption Request

Adding private properties to contract definition entity.

## General information

Extending contract definition entity with the map privateProperties. Additionally, adjust the affected transformers and contract definition API managements accordingly. The functionality would support in-memory and postgres as a store.

## Adoption level

Next, please tell us what level of adoption you intend to provide. _(pick only one)_

- [ ] Reference a feature as "friend"
- [X ] Incorporate a feature as core EDC component

## Adoption in EDC core

_If you chose to add your feature as a core EDC component, please answer the following questions._

### Why should this contribution be adopted?
This feature is similar to what is currently available for Asset entity. Therefore, the required contribution for the contract definition to enable the private properties looks very similar.

### Could it be achieved with existing functionality? If not, why?
No. This is a completely new field withing the contract definition entity. 

### Are there multiple use cases or applications who will benefit from the contribution?
Yes, same as Asset entity.

### Can it be achieved without introducing third-party dependencies? If not, which ones?
Yes

### Would this feature limit platform independence in any way? If so, how and why?
No

### Is it going to be a self-contained feature, or would it cut across the entire code base?
a self-contained feature.

Reference items:
https://github.com/eclipse-edc/Connector/discussions/2592#discussioncomment-7162109

**Comment by mohannad-ezzo** [comment]
Is there any update for this issue?
Changes are introduced in the branch https://github.com/mohannad-ezzo/Connector/tree/feat-contract-def-private-prop and ready to create a pull request.

**Comment by ndr-brt** [comment]
Ok, let's open the PR, we will review that. thanks.
