### ISSUE TITLE
Release Approach Link is dead

### ISSUE THREAD

**Issue by egekorkan** [eclipse-edc/Connector#3598]
# Bug Report

## Describe the Bug

Clicking at release approach at https://github.com/eclipse-edc/Connector/blob/main/README.md#releases returns a non-existing page.

### Expected Behavior

That hyperlink should point to one of the following:

- https://github.com/eclipse-edc/docs/tree/main/developer/decision-records/2023-01-26-release-process
- https://github.com/eclipse-edc/docs/blob/main/developer/decision-records/2023-05-17-release-process/README.md
- https://github.com/eclipse-edc/docs/blob/main/developer/decision-records/2022-11-28-release-management/README.md

On a second thought, none of them are guiding enough. I would actually expect a document, ideally not dated, that shows the latest state of the release approach.

### Observed Behavior

Directing to an 404 page

## Steps to Reproduce

1. Go to https://github.com/eclipse-edc/Connector/blob/main/README.md
2. Scroll to Releases
3. Click on `release approach`

## Context Information

I do not have knowledge about how the development of EDC is happening, I am purely a user.

## Possible Implementation

Listed in Observed Behavior

**Comment by ndr-brt** [comment]
the release document was moved here: https://github.com/eclipse-edc/docs/blob/main/developer/releases.md
could you please provide a PR to update the link?

**Comment by egekorkan** [comment]
@ndr-brt I have opened #3608 Thanks for pointing me to the correct location as well.
