### ISSUE TITLE
Feature Request: Add capability to search/query policies for given privateProperties filter value

### ISSUE THREAD

**Issue by suh-rao** [eclipse-edc/Connector#3623]
# Feature Request
Once we allow storing of privateProperties as JSON in policyDefinition table , we need to allow user to search for policies for given privatePropertie in filter expression of api policydefinitions/request.
This feature request is for search/query based on privateProperties value given in filter expression.

## Which Areas Would Be Affected?
policydefinition

## Why Is the Feature Desired?
This feature is similar to what is currently available for Asset entity. Therefore, the required contribution for the policy definition to enable the private properties looks very similar.

## Solution Proposal
Similar to asset query by privateProperties

**Comment by suh-rao** [comment]
Please reopen this issue and assign it to me. https://github.com/eclipse-edc/Connector/pull/3691 Opened for same

**Comment by ndr-brt** [comment]
please link this issue in the pr using the `Closes` word, so at merge this will be closed automatically
