### ISSUE TITLE
Build failures in extensions related to jsonLdExtensions

### ISSUE THREAD

**Issue by rohrbachd** [eclipse-edc/Connector#3672]
# Bug Report

## Describe the Bug

The following unit tests fail under windows 

1. :extensions:common:json-ld:test 
2. :extensions:common:api:management-api-configuration:test 
3. :extensions:control-plane:api:management-api:contract-negotiation-api:test 
4. :extensions:control-plane:api:management-api:policy-definition-api:test

Please note the first bug was reported in issue `[3408](https://github.com/eclipse-edc/Connector/issues/3408)` and there is a pull request out: #3670 

Furthermore, it looks like all the issues are connected especially 2-4. The problem is with 
`JsonLd jsonLd = new JsonLdExtension().createJsonLdService(testServiceExtensionContext())`

and later in the test code
`var expanded = jsonLd.expand(jsonObject);`

which will return `null` for `expanded.content` and `There was a problem encountered loading a remote context [code=LOADING_REMOTE_CONTEXT_FAILED].` for `expanded.failure.message`

This can be observed in `ManagementApiSchemaTest` 

```
    void contractAgreementExample() throws JsonProcessingException {
        var jsonObject = objectMapper.readValue(CONTRACT_AGREEMENT_EXAMPLE, JsonObject.class);
        var expanded = jsonLd.expand(jsonObject);

        assertThat(expanded).isSucceeded().satisfies(content -> {
            assertThat(content.getString(ID)).isNotBlank();
            assertThat(content.getJsonArray(TYPE).getString(0)).isEqualTo(CONTRACT_AGREEMENT_TYPE);
            assertThat(content.getJsonArray(CONTRACT_AGREEMENT_ASSET_ID).getJsonObject(0).getString(VALUE)).isNotBlank();
            assertThat(content.getJsonArray(CONTRACT_AGREEMENT_PROVIDER_ID).getJsonObject(0).getString(VALUE)).isNotBlank();
            assertThat(content.getJsonArray(CONTRACT_AGREEMENT_CONSUMER_ID).getJsonObject(0).getString(VALUE)).isNotBlank();
            assertThat(content.getJsonArray(CONTRACT_AGREEMENT_SIGNING_DATE).getJsonObject(0).getJsonNumber(VALUE).longValue()).isGreaterThan(0);
            assertThat(content.getJsonArray(CONTRACT_AGREEMENT_POLICY).getJsonObject(0)).isNotNull();
        });
    }
```

what fails is 
`assertThat(expanded).isSucceeded()`

### Expected Behavior
Unit tests should pass when building Connector using 
`./gradlew build`

the following will build successfully 
`./gradlew build -x :extensions:common:json-ld:test -x :extensions:common:api:management-api-configuration:test -x :extensions:control-plane:api:management-api:contract-negotiation-api:test -x :extensions:control-plane:api:management-api:policy-definition-api:test`

### Observed Behavior
**:extensions:common:json-ld:test** 
see `[3408](https://github.com/eclipse-edc/Connector/issues/3408)`

 **:extensions:common:api:management-api-configuration:test** 
```
java.lang.AssertionError: Expected result to be succeeded, but it was failed: There was a problem encountered loading a remote context [code=LOADING_REMOTE_CONTEXT_FAILED].
	at org.eclipse.edc.connector.api.management.configuration.ManagementApiSchemaTest.contractAgreementExample(ManagementApiSchemaTest.java:78)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
```

```
java.lang.AssertionError: Expected result to be succeeded, but it was failed: There was a problem encountered loading a remote context [code=LOADING_REMOTE_CONTEXT_FAILED].
	at org.eclipse.edc.connector.api.management.configuration.ManagementApiSchemaTest.policyExample(ManagementApiSchemaTest.java:132)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
```

 **:extensions:control-plane:api:management-api:contract-negotiation-api:test** 
```
java.lang.AssertionError: Expected result to be succeeded, but it was failed: There was a problem encountered loading a remote context [code=LOADING_REMOTE_CONTEXT_FAILED].
	at org.eclipse.edc.connector.api.management.contractnegotiation.ContractNegotiationApiTest.contractRequestExample(ContractNegotiationApiTest.java:76)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
```

 **:extensions:control-plane:api:management-api:policy-definition-api:test**
```
java.lang.AssertionError: Expected result to be succeeded, but it was failed: There was a problem encountered loading a remote context [code=LOADING_REMOTE_CONTEXT_FAILED].
	at org.eclipse.edc.connector.api.management.policy.PolicyDefinitionApiTest.policyDefinitionInputExample(PolicyDefinitionApiTest.java:62)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
```

```
java.lang.AssertionError: Expected result to be succeeded, but it was failed: There was a problem encountered loading a remote context [code=LOADING_REMOTE_CONTEXT_FAILED].
	at org.eclipse.edc.connector.api.management.policy.PolicyDefinitionApiTest.policyDefinitionOutputExample(PolicyDefinitionApiTest.java:79)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
```

## Steps to Reproduce

1. check out on windows system (assume gradle and java is installed) 
2. cd into directory using command 
3.  ./gradlew build

## Context Information

- OS: Windows
- Gradle: 8.4
- Java: 17

**Comment by ndr-brt** [comment]
solved by #3670
