### ISSUE TITLE
Assets data is not in format "edc :dataAddress"

### ISSUE THREAD

**Issue by tuanphampmt** [eclipse-edc/Connector#3679]
When I request to api /management/v3/assets/request, the returned assets do not contain "edc:"
`` {
        "@id": "urn:uuid:9f53d26f-853e-4315-bd34-3bee13d0feb9",
        "@type": "Asset",
        "properties": {
            "description": "IRS EDC Test Asset",
            "id": "urn:uuid:9f53d26f-853e-4315-bd34-3bee13d0feb9"
        },
        "dataAddress": {
            "@type": "DataAddress",
            "proxyPath": "true",
            "type": "HttpData",
            "proxyMethod": "false",
            "proxyQueryParams": "false",
            "proxyBody": "false",
            "baseUrl": "http://irs-provider-backend:8080/data/urn:uuid:8f4da0a6-b5da-4a25-af5a-4b888c141b55"
        },
        "@context": {
            "@vocab": "https://w3id.org/edc/v0.0.1/ns/",
            "edc": "https://w3id.org/edc/v0.0.1/ns/",
            "tx": "https://w3id.org/tractusx/v0.0.1/ns/",
            "odrl": "http://www.w3.org/ns/odrl/2/"
        }
    }``
I want the returned data to contain "edc:"
For example:
` {
        "@id": "urn:uuid:9f53d26f-853e-4315-bd34-3bee13d0feb9",
        "@type": "Asset",
        "edc:properties": {
            "edc:description": "IRS EDC Test Asset",
            "edc:id": "urn:uuid:9f53d26f-853e-4315-bd34-3bee13d0feb9"
        },
        "dataAddress": {
            "@type": "DataAddress",
            "edc:proxyPath": "true",
            "edc:type": "HttpData",
            "edc:proxyMethod": "false",
            "edc:proxyQueryParams": "false",
            "edc:proxyBody": "false",
            "edc:baseUrl": "http://irs-provider-backend:8080/data/urn:uuid:8f4da0a6-b5da-4a25-af5a-4b888c141b55"
        },
        "@context": {
            "@vocab": "https://w3id.org/edc/v0.0.1/ns/",
            "edc": "https://w3id.org/edc/v0.0.1/ns/",
            "tx": "https://w3id.org/tractusx/v0.0.1/ns/",
            "odrl": "http://www.w3.org/ns/odrl/2/"
        }
    }`

**Comment by ndr-brt** [comment]
I already responded in [the tractus-x repository](https://github.com/eclipse-tractusx/tractusx-edc/issues/893#issuecomment-1835706919).
Please do not open the same issue in different repositories.
