### ISSUE TITLE
Support filter expressions for numbers

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-edc/Connector#3688]
# Feature Request

Currently if we try to filter an asset by a numeric field with postgresql database, e.g.:
```json
{
    "@context": {
        "odrl": "http://www.w3.org/ns/odrl/2/"
    },
    "@type": "QuerySpec",
    "offset": 0,
    "limit": 10,
    "filterExpression": [
        {
            "operandLeft": "https://w3id.org/edc/v0.0.1/ns/month",
            "operator": "=",
            "operandRight": 12
        }
    ]
}
```

we'll receive this error:
```
SEVERE 2023-12-05T10:59:28.1771974 JerseyExtension: Unexpected exception caught
org.eclipse.edc.spi.persistence.EdcPersistenceException: org.postgresql.util.PSQLException: ERROR: operator does not exist: text = double precision
  Hint: No operator matches the given name and argument types. You might need to add explicit type casts.
```

It would be nice to have numbers supported as [it was done for boolean](https://github.com/eclipse-edc/Connector/blob/bdd6a2a425301676ebd72827f5ec6412935270e4/extensions/common/sql/sql-core/src/main/java/org/eclipse/edc/sql/translation/JsonFieldMapping.java#L43-L45).

## Which Areas Would Be Affected?

postgres statement building

## Why Is the Feature Desired?

_Are there any requirements?_

## Solution Proposal

_If possible, provide a (brief!) solution proposal._

**Comment by bmg13** [comment]
Is this issue still applicable? I believe it was fixed in here: https://github.com/eclipse-edc/Connector/commit/703502f7be7d8bd8bc1951bb81df4397bfa4a5c0#diff-7a903fa35f24513d25fd5919768a14e2aafcb26b3e0e2d84487b189a13c022f8R51

**Comment by ndr-brt** [comment]
Works for `int` but not for `float/double`

**Comment by bmg13** [comment]
I see, can you please assign to me?
the idea would be to have a if() for each type (adding one for double here).
