### ISSUE TITLE
`POST /v3/assets` parses arbitrary json as properties

### ISSUE THREAD

**Issue by arnoweiss** [eclipse-edc/Connector#3701]
### Discussed in https://github.com/eclipse-edc/Connector/discussions/3693

<div type='discussions-op-text'>

<sup>Originally posted by **arnoweiss** December  6, 2023</sup>

#### 1. "Unknown data must be a property"
Here's an invalid `POST /v3/assets` request (look for the "whatever"-key):
```json
{
  "@context": {
    "edc": "https://w3id.org/edc/v0.0.1/ns/",
    "cx-common": "https://w3id.org/catenax/ontology/common#",
    "cx-taxo": "https://w3id.org/catenax/taxonomy#",
    "dct": "https://purl.org/dc/terms/"
  },
  "@id": "assetId",
  "properties": {
    "dct:type": {
      "@id": "assetType"
    },
    "cx-common:version": "assetVersion"
  },
  "privateProperties": {},
  "whatever": "data",
  "dataAddress": {
    "@type": "DataAddress",
    "type": "HttpData",
    "baseUrl": "https://myback.end/data",
    "oauth2:tokenUrl": "https://mytoken.server/token",
    "oauth2:clientSecretKey": "myTokenKey",
    "proxyQueryParams": "true",
    "proxyPath": "false",
    "proxyMethod": "true"
  }
}
```
For this request, the expected response would be HTTP 400, explaining that the presence of json-key "whatever" isn't known and thus rejected.

This however isn't how the API behaves. Any unknown data on the top-level of the json-hierarchy is accepted, parsed as Map<String, Object> and stored as a Property. It is therefore visible to consumers via the catalog. That poses the risk that an Admin accidentally places dataAddress- or privateProperty-data on the top level exposing sensitive information. For an ordinary REST-API a fixed JSON-schema for the Asset object with `additionalAttributes: false` could probably do the job.

</div>

**Comment by paullatzelsperger** [comment]
`whatever` will get stripped out during JSON-LD expansion, because there is no `context` for it, which happens on ingress, so it is in fact no there anymore when the request hits the controller.

**Comment by arnoweiss** [comment]
For v0.5.1 and v0.5.2 this behavior definitely persists as originally explained.

Even if the expansion strips non-contextualized json-properties on the top-level, the problem would still occur if the `whatever` key had context (by either setting a `@vocab` or explicitly prefixing it `edc:whatever`).

**Comment by ndr-brt** [comment]
I don't think it should return a 400, the api should ignore all the "root-level" unknown properties (as it is the common behavior for unknown properties), and only the ones contained in the `properties` object should be considered.

**Comment by arnoweiss** [comment]
That's fine as well. What really matters is that the current unexpected behavior (top-level key-value pair --> property) stops.

**Comment by arnoweiss** [comment]
Retried with eclipse-edc/Connector 0.5.1, issue persists
