### ISSUE TITLE
Add configuration extension to read values from `Vault`

### ISSUE THREAD

**Issue by paullatzelsperger** [eclipse-edc/Connector#3712]
# Feature Request

Some configuration values are in fact secrets, such as JDBC config values, client secrets for cloud providers, etc.

The configuration mechanism should read values from the `Vault` if they are not found in the system props or env vars.

## Which Areas Would Be Affected?

EDC Core, Configuration

## Why Is the Feature Desired?

Security

## Solution Proposal

_If possible, provide a (brief!) solution proposal._

**Comment by paullatzelsperger** [comment]
sure, but since this requires changes to the very core of the runtimes, please provide a written implementation proposal beforehand to avoid wasted cycles. 
It's OK to open a draft PR and put the impl proposal into `docs/developer` for now. it can later serve as documentation.

A few hints:
- do not spam the vault needlessly
- handle errors gracefully 
- test extensively

**Comment by domreuter** [comment]
We also implemented the same thing on our end. 

The most trickiest part was to inject the vault to VaultConfig during the service extension loading provided by the ServiceLoader.

ConfigExtensions --> FSConfig
ServiceExtensions --> Vault
 
ConfigExtensions are currently loaded by the Runtime before the ServiceExtensions, which totally makes sense to get the config in there before any extension runs through the initialize phase, but also makes it more complex cause they are treated in a different way.

Therefore there are some things you need to consider:
- Load VaultConfig with the possibility to inject the vault with setter injection
- Adding the Vault as one of the first available extensions in the list of service extensions loaded by the ServiceLoader
- Ensure that the VaultExtension is configured correctly, this can be ensured at this point by the FSConfigExtension
- Inject the vault to VaultConfig as soon as it is loaded within the ServiceLoader

If you need any further input or help, feel free to contact me.

**Comment by paullatzelsperger** [comment]
After some discussion we decided not to implement this, because a generic solution will possibly cause needless load on the vault. In addition, there may be nuanced situations, where client extensions may choose to read secrets from config only as fallback, or not at all.

Follow-up issues will take care of explicitly reading individual secrets (e.g. database creds) from the vault.
