### ISSUE TITLE
Story: Refactoring of token handling in EDC

### ISSUE THREAD

**Issue by paullatzelsperger** [eclipse-edc/Connector#3743]
# Feature Request

this is a story issue that tracks all necessary steps outlined in [decision-record 2023-12-23](https://github.com/eclipse-edc/Connector/blob/main/docs/developer/decision-records/2023-12-19-token-handling-refactor/README.md).

## Which Areas Would Be Affected?

wide areas of the EDC code base, plus downstream EDC projects

## Why Is the Feature Desired?

token handling is currently all over the place, and it needs to be streamlined and unified.

## Solution Proposal

Implement the following issues:
- [x] #3740 
- [x] #3741 
- [x] #3742 
- [x] #3744 
- [x] #3757 
- [x] #3745 
- [x] #3746 
- [ ] #3747 
- [x] #3748 

All PRs should be merged into a temporary branch `refactor/token-handling` (https://github.com/eclipse-edc/Connector/tree/refactor/token-handling) to avoid constant build breakages and then merged into `main` in one fell swoop.

**Comment by xdxxxdx** [comment]
Hello @paullatzelsperger 
Thanks so much for your reply, what does IATP stand for?
