### ISSUE TITLE
Assets Containing the `proxyMethod=true` Property can not be used with the ProviderPushTransfer

### ISSUE THREAD

**Issue by efiege** [eclipse-edc/Connector#3768]
# Bug Report

## Describe the Bug

Assets containing the `proxyMethod=true` property can not be used with the ProviderPushTransfer.

### Expected Behavior

When starting a new `TransferProcess` with type `HttpData` over the POST `/transferprocesses` endpoint of the consumer the provider data-plane should use the `properties` of the `TransferRequest` to define the http-method for accessing the data-source.

### Observed Behavior

The validation in the `BaseSourceHttpParamsDecorator` fails with "DataFlowRequest %s: 'method' property is missing".

## Context Information

- Used version 0.2.1
- But should also hold for newer versions

## Detailed Description

This should origin from the `ProviderPushTransferDataFlowController`, which does not create an `DataFlowRequest` with the properties of the `TransferRequest`:
https://github.com/eclipse-edc/Connector/blob/cf3b2450b9bdcff749566e95b087b211b5d70fd9/extensions/control-plane/transfer/transfer-data-plane/src/main/java/org/eclipse/edc/connector/transfer/dataplane/flow/ProviderPushTransferDataFlowController.java#L64-L72

**Comment by ndr-brt** [comment]
hi, thanks for reporting, please add details of the calls that you made against the connectors.
we don't support version 0.2.1 anymore, so please try to replicate this against the latest version (0.4.1)

**Comment by FlorianFehrleIEE** [comment]
I ran into the same issue on version 0.4.1, so it also seems to be a problem on the newest version. 
My call for creating the asset was: 
```
curl -d '{
           "@context": {
             "edc": "https://w3id.org/edc/v0.0.1/ns/"
           },          
           "@id": "name",
           "properties": {
             "name": "Name data",
             "contenttype": "application/json"
           },
		   "privateProperties": {
		   },
           "dataAddress": {
             "name": "Name data",
             "baseUrl": "http://localhost:1001/namedata.json",
             "type": "HttpData",
			 "proxyMethod": "true"
           }
         }' -H 'content-type: application/json' http://localhost:19193/management/v3/assets \
         -s | jq
```
and my call for the transfer request was:
```
curl -X POST "http://localhost:29193/management/v2/transferprocesses" \
    -H "Content-Type: application/json" \
    -d '{
        "@context": {
          "edc": "https://w3id.org/edc/v0.0.1/ns/"
        },
        "@type": "TransferRequestDto",
        "connectorId": "kunde2",
        "connectorAddress": "http://172.20.0.2:19194/protocol",
        "contractId": "d53c3abd-c795-41f8-9e1e-d50795433891",
        "assetId": "name",
        "protocol": "dataspace-protocol-http",
        "dataDestination": { 
          "type": "HttpData",
          "baseUrl": "http://localhost:1000/"
        }
    }' \
    -s | jq
```
(The calls for the policy definition, contract definition and contract negotiation seemed to be irrelevant for this topic for me, which is why i left them out here)
When I start the transfer request, i get the following error on provider side:
```
Failed to build HttpDataSource: DataFlowRequest 3aa9247f-03ba-43de-9c94-d1dde99337df: 'method' property is missing
```
I hope that helps to further narrow down the problem

**Comment by ndr-brt** [comment]
Ok, I think I got it, in fact `proxyMethod` it is a `DataAddress` property that should only be considered for `pull` transfers, but in this case the asset is requested in a `push` manner so it that check should be eventually avoided.
