### ISSUE TITLE
Policy scopes for transfer process ingress calls

### ISSUE THREAD

**Issue by wolf4ood** [eclipse-edc/Connector#3818]
# Feature Request

As we do for transfer process `egress` call, we should be able to attach custom information to the current transfer process `ingress` call, like running policy scope extractors.

Part of #3662

**Comment by florianrusch-zf** [comment]
@wolf4ood could you explain, what the breaking changes are and how they would affect the user?

**Comment by wolf4ood** [comment]
Hi @florianrusch-zf  it's not a breaking change for users but rather internal EDC usage/spi
