### ISSUE TITLE
Story: Align with Dataspace Protocol v1.0

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-edc/Connector#3836]
# Feature Request

Dataspace Protocol [is heading to version 1.0](https://github.com/International-Data-Spaces-Association/ids-specification/issues?q=is%3Aissue+is%3Aopen+label%3A%22V1+pre-release%22)
This issue will track the progress for implementing it.

## Which Areas Would Be Affected?

protocol

## Why Is the Feature Desired?

dsp compliance

## Solution Proposal

_If possible, provide a (brief!) solution proposal._

# Checklist

Updated to the commit https://github.com/International-Data-Spaces-Association/ids-specification/commit/63e5a401192336177f1d547ebd1f8e8f6f129269

- [x] #3840 
- [x] #3841
- [x] #3842
- [x] #3843
- [x] #3792 
- [x] #3350
- [x] #3846 
- [x] #3866
- [x] #3872
- [x] #3880
- [x] #3930
- [x] #4047

**Comment by jimmarino** [comment]
Some things to check:

- If a filter is not understood, return [HTTP 400 Bad Request](https://github.com/International-Data-Spaces-Association/ids-specification/pull/228)
- [Participant Id prefix change](https://github.com/International-Data-Spaces-Association/ids-specification/pull/226)
