### ISSUE TITLE
test: make `EdcRuntimeExtension` able to build dynamic runtimes

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-edc/Connector#3857]
# Feature Request

Currently, when we set up an end-to-end test we need to define the runtime with a `build.gradle.kts` file.
It should be nice to being able to specify additional modules to be passed to the `EdcRuntimeExtension` constructor directly.
This would permit to define test matrix to permit certain tests to be run with different modules.

## Which Areas Would Be Affected?

tests

## Why Is the Feature Desired?

_Are there any requirements?_

## Solution Proposal

_If possible, provide a (brief!) solution proposal._

**Comment by jimmarino** [comment]
🚀
