### ISSUE TITLE
Wrong mapping of ODRL ``neq`` operator

### ISSUE THREAD

**Issue by IcarusCoding** [eclipse-edc/Connector#3874]
# Bug Report

## Describe the Bug
When I try to create a policy with a permission constraint using the ``neq`` operator, it gets mapped to ``neg``.

### Expected Behavior
The ODRL specification for a not-equals operator clearly states:
![image](https://github.com/eclipse-edc/Connector/assets/50166985/6d9ac7fe-5adb-499a-b1b3-f197817e8ef7)
Apparently the W3 ODRL specification has it wrong too: http://www.w3.org/ns/odrl.jsonld

### Observed Behavior
https://github.com/eclipse-edc/Connector/blob/28ccdc1c3c1fe2ab781209c3f606861a0ae88bfa/extensions/common/json-ld/src/main/resources/document/odrl.jsonld#L185

## Steps to Reproduce
1. Try to create a policy definition with operator ``neq``

**Comment by jimmarino** [comment]
Unfortunately, there is not much we can do unless ODRL updates their Json-Ld context. I would file a bug report with them and if they publish a newer version, we can support it.

**Comment by IcarusCoding** [comment]
Thank you for the quick reply, i will file a bug report with them.
