### ISSUE TITLE
Requests using the `SqlDataPlaneInstanceStores` `getAll` Method getting Stuck

### ISSUE THREAD

**Issue by efiege** [eclipse-edc/Connector#3887]
# Bug Report

## Describe the Bug

Requests using the `SqlDataPlaneInstanceStores` `getAll` method are getting stuck and run into timeouts after a while. We observed this mainly on the dsp catalog endpoint `/catalog/request`, but also other parts may be affected. It should be caused by transactions not beeing closed by this method:

https://github.com/eclipse-edc/Connector/blob/83b6bcaf5fcd4b5359fe134219f374b50fa3ada9/extensions/data-plane-selector/store/sql/data-plane-instance-store-sql/src/main/java/org/eclipse/edc/connector/dataplane/selector/store/sql/SqlDataPlaneInstanceStore.java#L101-L109

Unlike in `getAll` methods of other stores, this method is not making use of the `transactionContext`. For example see the `SqlContractDefinitionStore`
https://github.com/eclipse-edc/Connector/blob/83b6bcaf5fcd4b5359fe134219f374b50fa3ada9/extensions/control-plane/store/sql/contract-definition-store-sql/src/main/java/org/eclipse/edc/connector/store/sql/contractdefinition/SqlContractDefinitionStore.java#L63-L75

### Expected Behavior
Transactions getting closed and requests not running into timeouts.

### Observed Behavior
Requests running into timeouts and transactions in the database beeing idle and not getting closed.

## Context Information

- Used version EDC v0.2.1

## Possible Implementation

Using the `transactionContext` to wrap the `getAll` method in the `SqlDataPlaneInstanceStore`. This fixed our issue in version 0.2.1!

```java
@Override
public Stream<DataPlaneInstance> getAll() {
    return transactionContext.execute(() -> {
        try {
            var sql = statements.getAllTemplate();
            return queryExecutor.query(getConnection(), true, this::mapResultSet, sql);
        } catch (SQLException exception) {
            throw new EdcPersistenceException(exception);
        }
    });
}
```

**Comment by wolf4ood** [comment]
Hi @efiege 

thanks for raising this, is this applicable also tp 0.5.1?
