### ISSUE TITLE
wrong namespace URI for dct

### ISSUE THREAD

**Issue by arnoweiss** [eclipse-edc/Connector#3910]
The [Dublin Core vocabulary](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/terms/type/) resides in a namespace starting with `http` instead of `https`. The EDC has hardcoded `https`.

https://github.com/eclipse-edc/Connector/blob/1120ba224774b3689c794bacf62c5fefba717ebb/spi/common/json-ld-spi/src/main/java/org/eclipse/edc/jsonld/spi/Namespaces.java#L27

**Comment by arnoweiss** [comment]
This is wrong in CX-0018 as well and will be fixed with the next iteration.

**Comment by ndr-brt** [comment]
Thanks for reporting. Closed by #3914
