### ISSUE TITLE
DPS: implement the Data plane Signaling API

### ISSUE THREAD

**Issue by wolf4ood** [eclipse-edc/Connector#3911]
# Feature Request

Implements a new controller for the Data plane signaling API

The definition of the Signaling API and the OpenAPI spec has already been addressed in [this](https://github.com/eclipse-edc/Connector/pull/3906) PR. 

## Which Areas Would Be Affected?

dpf

## Why Is the Feature Desired?

data plane signaling

_depends on https://github.com/eclipse-edc/Connector/issues/3934_

**Comment by paullatzelsperger** [comment]
Closed by #3955
