### ISSUE TITLE
[JSON-LD] Local odrl.jsonld has a wrong value for odrl:neq operator http://www.w3.org/ns/odrl/2/neq

### ISSUE THREAD

**Issue by domreuter** [eclipse-edc/Connector#3976]
# Bug Report

The local provided odrl.jsonld used within the json-ld extension has a wrong entry for the notEquals operator.

### Expected Behavior

Expect the notEquals (neq) operator to be evaluated correctly against 
http://www.w3.org/ns/odrl/2/neq 
instead of:
http://www.w3.org/ns/odrl/2/neg

### Observed Behavior

Policy creation from management-api is failing in the JsonObjectToOperatorTransformer with the following error message.

```json
[
    {
        "message": "http://www.w3.org/ns/odrl/2/Operator property '@id' was invalid: http://www.w3.org/ns/odrl/2/neg",
        "type": "InvalidRequest",
        "path": null,
        "invalidValue": null
    },
    {
        "message": "ARRAY must be EQ, NEQ, GT, GEQ, LT, LEQ, IN, HAS_PART, IS_A, IS_ALL_OF, IS_ANY_OF, or IS_NONE_OF but was: unknown",
        "type": "InvalidRequest",
        "path": null,
        "invalidValue": null
    }
]
```

## Steps to Reproduce

Try to create a policy with an constraint and use neq as the operator. Take this as an example payload, even if it is related to some Tractus-X extensions, the problem statement should be clear.

```json{
    "@context": {
        "@vocab": "https://w3id.org/edc/v0.0.1/ns/"
    },
    "@type": "PolicyDefinition",
    "@id": "{{policyId}}",
    "policy": {
        "@context": "http://www.w3.org/ns/odrl.jsonld",
        "@type": "Set",
        "permission": [
            {
                "target": "{{assetId}}",
                "action": "use",
                "constraint": {
                    "leftOperand": "https://w3id.org/tractusx/v0.0.1/ns/BusinessPartnerGroup",
                    "operator": "neq",
                    "rightOperand": "value"
                }
            }
        ],
        "prohibition": [],
        "obligation": []
    }
}
```

## Context Information

_Add any other context about the problem here._

EDC Connector v5.01
Tractus-X EDC Connector 0.6.0

## Possible Implementation

Fix the entry in the local odrl.jsonld to point to the correct value.

**Comment by wolf4ood** [comment]
Hi @domreuter 

thanks for raising this, it seems that it was opened previously a similar issue check here

https://github.com/eclipse-edc/Connector/issues/3874


Thanks

**Comment by domreuter** [comment]
Sorry, I must have missed that. Just read through and don't get why this can't be fixed as long as we evaluate against the local odrl.json-ld? Looks like a typo for me, cause "neg" is not in the list of supported operators within ODRL 2.2 https://www.w3.org/TR/odrl-vocab/#term-Operator

**Comment by paullatzelsperger** [comment]
if its two EDC-based connectors talking there shouldn't be a problem, but as soon as there is a non-EDC connector involved, who may or may not use a locally cached and "altered" file, the  JSON won't get expanded properly anymore.

**Comment by domreuter** [comment]
The thing is that atm it is not possible to get the policy in as neither "neg" nor "neq". So either update the local odrl.json-ld or update the `Operator` here `NEQ("neq")`.

**Comment by domreuter** [comment]
Did some additional research and need to correct myself in the sense that it is not possible to create the policy at all.

If we use `odrl:neq` operator in the payload it will be resolved as `http://www.w3.org/ns/odrl/2/neq` and goes through. This is because the operator class will return the same odrl representation, as it points to `neq` internally. 

Seems as it will not be checked against the odr.json-ld at all when provided with the prefix, this could be another issue here.
