### ISSUE TITLE
Documentation for `edc.transfer.proxy.token...` config is wrong

### ISSUE THREAD

**Issue by florianrusch-zf** [eclipse-edc/Connector#3986]
The documentation at the following lines is wrong. There is no mechanism in place which will create random keys.

https://github.com/eclipse-edc/Connector/blob/8193f3d99e60c22a30ab39385c7769ec1af492d7/extensions/control-plane/transfer/transfer-data-plane/README.md?plain=1#L51-L52

Proof:
https://github.com/eclipse-edc/Connector/blob/8193f3d99e60c22a30ab39385c7769ec1af492d7/extensions/control-plane/transfer/transfer-data-plane/src/main/java/org/eclipse/edc/connector/transfer/dataplane/TransferDataPlaneCoreExtension.java#L113-L122

**Comment by ndr-brt** [comment]
documenting the settings in a readme is highly discouraged because they get outdated easily, better to properly annotate the setting with the `@Setting` annotation so the documentation can be generated with the `autodoc` plugin

**Comment by ndr-brt** [comment]
the documentation is being posted on gh pages, this is the current one: 
https://eclipse-edc.github.io/Connector/autodoc/0.5.2-SNAPSHOT/

**Comment by segoranov** [comment]
> documenting the settings in a readme is highly discouraged because they get outdated easily, better to properly annotate the setting with the `@Setting` annotation so the documentation can be generated with the `autodoc` plugin

already outdated, apart from the inconsistency mentioned in the issue, there is also no such parameter used at all: `edc.transfer.client.selector.strategy` (it's in the readme file only).

can i take this issue?
