### ISSUE TITLE
Contract Agreement IDs are not being size validated

### ISSUE THREAD

**Issue by afonsocorreiactw** [eclipse-edc/Connector#4003]
# Bug Report

## Describe the Bug

The Database column related to the Contract Agreement ID has type character varying(255). Since the Contract Agreement ID is computed like:

<base64 contract definition id> : <base64 asset id> : <base64 random salt>

A large enough Contract Agreement ID, composed of a large contract definition id and a large asset id, will break the transfer process.

### Expected Behavior

Either allow bigger Contract Agreement IDs to be registered, or restrict the size of the Contract Definitions ID and Asset IDs

### Observed Behavior

Snippet of the stack trace:

org.eclipse.edc.spi.persistence.EdcPersistenceException: ERROR: value too long for type character varying(255)
  at org.eclipse.edc.sql.SqlQueryExecutor.execute(SqlQueryExecutor.java:66)
  at org.eclipse.edc.connector.store.sql.transferprocess.store.SqlTransferProcessStore.insertDataRequest(SqlTransferProcessStore.java:324)
  at org.eclipse.edc.connector.store.sql.transferprocess.store.SqlTransferProcessStore.insert(SqlTransferProcessStore.java:318)

## Steps to Reproduce

1. Register an Asset with a large ID (~100 chars)
2. Register a Contract Definition for that Asset also with a large ID (~100 chars)
3. Fetch the catalog for that EDC
4. Verify if the Offer ID has more than 255 chars (Offer ID and Contract Agreement ID are computed in the same manner, and have the same number of chars)
5. Negotiate the offer
6. Transfer the Offer

## Context Information

- Used version EDC v0.2.1

**Comment by ndr-brt** [comment]
the EDC does not define a strict schema, you can find examples in the `sql` related modules but in fact how to define the schema is up to the specific connector implementation.

Anyway, the example schema for transfer process does not define length for the contract_id ([in postgresql that should equal to define a field of length of 10,485,760](https://www.postgresql.org/docs/current/datatype-character.html))
https://github.com/eclipse-edc/Connector/blob/df48c3e0d3cf2daf00355215653210c3cd9e00e4/extensions/control-plane/store/sql/transfer-process-store-sql/docs/schema.sql#L60-L75

**Comment by afonsocorreiactw** [comment]
Thanks for the quick reply.
Closing this issue as it only applies to the EDC implementation I'm using
