### ISSUE TITLE
Solve little flaws in `BaseRuntime`

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-edc/Connector#4060]
# Feature Request

Currently there are two little flaws in the `BaseRuntime` that could be solved:
- the `System.exit` call has no reason to be and it's better to replace it with an extension throwing, that will help the caller to understand what happened. as a positive side effect this will also provide better output on the e2e tests when they fail for runtime issues (now they fall silently)
- the `HealthCheckService` is currently mandatory but this does not look like a good practice, because there could be the necessity to start a Runtime without that service, but now it causes an unavoidable exception.

## Which Areas Would Be Affected?

boot

## Why Is the Feature Desired?

_Are there any requirements?_

## Solution Proposal

_If possible, provide a (brief!) solution proposal._

**Comment by jimmarino** [comment]
Can we deal with the Healthcheck service after I split the boot services from the core services? The System.exit can be addressed independently.

**Comment by ndr-brt** [comment]
@jimmarino I already opened a PR, but it can wait, no problems
