### ISSUE TITLE
Documentation of available config keys

### ISSUE THREAD

**Issue by KosrenDQ** [eclipse-edc/Connector#4136]
# Feature Request

The setup of an EDC is complicated as the needed configuration possibilities are not well documented. The code must be reverse-engineered to understand the full configuration of a core service or an extension. Even from the names of the keys, it sometimes takes work to derive their effect.
A table containing at least the standard config parameters with a short description, the default value, and an example value would be very helpful.

## Which Areas Would Be Affected?

Documentation

## Why Is the Feature Desired?

The onboarding process for setting up a new EDC would be more straightforward.

## Solution Proposal

Add a config_parameter.md file with a table containing, in best case, all configuration parameters.
Like the following:
| Key                                               | Description                                                                                    | Default Value                       | Example Value                          | Comment                                                                                      |
|---------------------------------------------------|------------------------------------------------------------------------------------------------|-------------------------------------|----------------------------------------|----------------------------------------------------------------------------------------------|
| EDC_CONNECTOR_NAME                                | The name of this connector in the data space                                                   | edc-`random UUID`                   | my-connector                           |                                                                                              |
| EDC_DSP_CALLBACK_ADDRESS                          | The endpoint to proxy data space protocol requests                                             | http://localhost:8282/api/v1/dsp    | https://example.com/connector/protocol | If `WEB_HTTP_PROTOCOL_*` is used, the path/port needs to be adjusted                         | 
| EDC_HOSTNAME                                      | The host name of the EDC connector                                                             | localhost                           | https://example.com                    |                                                                                              |
| EDC_KEYSTORE                                      | Keystore file to save sensitive values like private keys                                       | dataspaceconnector-keystore.jks     | /app/keystore.pfx                      | Should not be used productively. Supported file formats `*.jks`, `*.jceks`, `*.pfx`, `*.p12` |
| EDC_KEYSTORE_PASSWORD                             | Password to open keystore file from `EDC_KEYSTORE`                                             | null                                | 123456                                 | Should not be used productively                                                              |
| EDC_PARTICIPANT_ID                                | A unique name of this connector in a certain data space                                        | anonymous                           | my-connector                           |                                                                                              |
| EDC_DATAPLANE_TOKEN_VALIDATION_ENDPOINT           | If the public Data Plane API is activated, this endpoint validates the send authentication key | null                                | http://localhost:19192/control/token   | If `WEB_HTTP_CONTROL_*` is used, the path/port needs to be adjusted                          |
| EDC_TRANSFER_PROXY_TOKEN_SIGNER_PRIVATEKEY_ALIAS  | Needed for PUSH / PULL data transfer, name of private key from the keystore                    | null                                | 1                                      | In our current example, `1` means first key in the keystore `*.pxf\|*.jks\|*.jcks\|*.p12`    |
| EDC_TRANSFER_PROXY_TOKEN_VERIFIER_PUBLICKEY_ALIAS | Needed for PUSH / PULL data transfer, name of public key from the vault                        | null                                | public-key                             | From the file storage vault, compare `vault.properties`                                      | 
| EDC_VAULT                                         | File name of the vault file that will be loaded during startup                                 | dataspaceconnector-vault.properties | /app/vault.properties                  | Should not be used productively                                                              |
| EDC_VAULT_PERSISTENT                              | EDC will overwrite the vault file from `ECD_VAULT` with new keys                               | true                                |                                        | Should not be used productively                                                              |
| WEB_HTTP_PATH                                     | Default Jetty base path                                                                        | /api                                |                                        | Health check registers itself under this path                                                |
| WEB_HTTP_PORT                                     | Default Jetty port                                                                             | 8181                                |                                        |                                                                                              |
| WEB_HTTP_CONTROL_PATH                             | Control Plane API path                                                                         | /api/v1/control                     |                                        |                                                                                              |
| WEB_HTTP_CONTROL_PORT                             | Control Plane API port                                                                         | 9191                                |                                        |                                                                                              |
| WEB_HTTP_MANAGEMENT_PATH                          | Management API path                                                                            | /api/v1/management                  |                                        |                                                                                              |
| WEB_HTTP_MANAGEMENT_PORT                          | Management API port                                                                            | 8181                                |                                        |                                                                                              |
| WEB_HTTP_PROTOCOL_PATH                            | Data Space Protocol API path                                                                   | /api/v1/dsp                         |                                        |                                                                                              |
| WEB_HTTP_PROTOCOL_PORT                            | Data Space Protocol port                                                                       | 8282                                |                                        |                                                                                              |
| WEB_HTTP_PUBLIC_PATH                              | Public Data Plane API path                                                                     | /api/v1/public                      |                                        |                                                                                              |
| WEB_HTTP_PUBLIC_PORT                              | Public Data Plane API port                                                                     | 8185                                |                                        |                                                                                              |

**Comment by paullatzelsperger** [comment]
that documentation can already be generated using the `autodoc` gradle task, check the [documentation](https://github.com/eclipse-edc/docs/blob/main/developer/autodoc.md).
Just do `./gradlew autodoc` and `./gradlew mergeManifests`, and then you should find the generated json at `build/manifest.json`. 

Then, you can even convert it to markdown using `./gradlew doc2md`

**Comment by KosrenDQ** [comment]
Thank you. I was unaware of the meaning of 'manifest' in this context. Maybe a short hint in the documentation that shows what a manifest contains would be great :D

**Comment by paullatzelsperger** [comment]
it is [in there](https://github.com/eclipse-edc/GradlePlugins/blob/main/docs/developer/autodoc.md#merging-the-manifests).

**Comment by KosrenDQ** [comment]
ok
