### ISSUE TITLE
dependency error

### ISSUE THREAD

**Issue by ShawalKhan786** [eclipse-edc/Connector#4137]
When i add this dependency then i get ARTIFACT related error. would you please provide solution.

dependencies {
    implementation("org.eclipse.edc:spi:core-spi:0.6.3-SNAPSHOT")
    // any other dependencies
} 

ERROR: failed
:spi:common:policy-model:compileJava
Could not resolve org.eclipse.edc:spi:core-spi

**Comment by jimmarino** [comment]
This is not an issue but a problem with your local setup. Please read up on how Gradle resolves Maven snapshot dependencies.
