### ISSUE TITLE
No persistence of nested `odrl:leftOperand`.`@id` property in /v2/policydefinitions API

### ISSUE THREAD

**Issue by arnoweiss** [eclipse-edc/Connector#4179]
# Bug Report

## Describe the Bug

The `/v2/policydefinitions` API does not persist resources/objects with `@id` in the `leftOperand` property.

#### 1. Create policy
`POST /v2/policydefinitions` with
```json
{
  "@context": [
    {
      "@vocab": "https://w3id.org/edc/v0.0.1/ns/"
    },
    "http://www.w3.org/ns/odrl.jsonld"
  ],
  "@id": "left-op-scen-0",
  "policy": {
    "@type": "http://www.w3.org/ns/odrl/2/Set",
    "permission": [
      {
        "action": "use",
        "odrl:constraint": {
          "leftOperand": {
            "@id": "https://w3id.org/catenax/policy/FrameworkAgreement"
          },
          "odrl:operator": {
            "@id": "odrl:eq"
          },
          "odrl:rightOperand": "traceability:3.0"
        }
      }
    ]
  }
}
```
returns HTTP 200.
```json
{
    "@type": "IdResponse",
    "@id": "left-op-scen-0",
    "createdAt": 1715705166810,
    "@context": {
        "@vocab": "https://w3id.org/edc/v0.0.1/ns/",
        "edc": "https://w3id.org/edc/v0.0.1/ns/",
        "tx": "https://w3id.org/tractusx/v0.0.1/ns/",
        "tx-auth": "https://w3id.org/tractusx/auth/",
        "cx-policy": "https://w3id.org/catenax/policy/",
        "odrl": "http://www.w3.org/ns/odrl/2/"
    }
}
```
#### 2. Retrieve resource
`GET /v2/policydefinitions/left-op-scen-0`

### Expected Behavior

Though the compacted notation may differ, the content in the `constraint` property should be equal in expanded form.

### Observed Behavior

Step 2 returns:

```json
{
    "@id": "left-op-scen-0",
    "@type": "PolicyDefinition",
    "createdAt": 1715705166810,
    "policy": {
        "@id": "177d7dbf-6ea8-4b7c-aa3d-3576dd4596c0",
        "@type": "odrl:Set",
        "odrl:permission": {
            "odrl:action": {
                "odrl:type": "http://www.w3.org/ns/odrl/2/use"
            },
            "odrl:constraint": {
                "odrl:leftOperand": "https://w3id.org/catenax/policy/FrameworkAgreement",
                "odrl:operator": {
                    "@id": "odrl:eq"
                },
                "odrl:rightOperand": "traceability:3.0"
            }
        },
        "odrl:prohibition": [],
        "odrl:obligation": []
    },
    "@context": {
        "@vocab": "https://w3id.org/edc/v0.0.1/ns/",
        "edc": "https://w3id.org/edc/v0.0.1/ns/",
        "tx": "https://w3id.org/tractusx/v0.0.1/ns/",
        "tx-auth": "https://w3id.org/tractusx/auth/",
        "cx-policy": "https://w3id.org/catenax/policy/",
        "odrl": "http://www.w3.org/ns/odrl/2/"
    }
}
```
Note that the `leftOperand` holds a string unwrapped from the object from step 1. Since the returned `@context` object doesn't include the odrl-context but just the odrl-term/prefix, this expands to a different payload in json-ld, holding a literal (`@value`) instead a resource (`@id`).

## Context Information

Given the context from call 1, titanium coerces the payload into an object holding `@id`. It also allows to use 

- `"leftOperand": "cx-policy:FrameworkAgreement"`, 
- `"leftOperand": "https://w3id.org/catenax/policy/FrameworkAgreement"`, 
- `"leftOperand": {"@id":"cx-policy:FrameworkAgreement"}`, 
- `"leftOperand": {"@id":"https://w3id.org/catenax/policy/FrameworkAgreement"}`, 

however NOT (yielding an object with `@value`):
- `"odrl:leftOperand": "cx-policy:FrameworkAgreement"`, 
- `"odrl:leftOperand": "https://w3id.org/catenax/policy/FrameworkAgreement"`, 

That makes me guess the issue may lie somewhere in the persistence.

Setup: eclipse-edc 0.6.2 (as part of tractusx-edc 0.7.0).

**Comment by wolf4ood** [comment]
Hi @arnoweiss 

thanks for raising this, i think this is a serialization issue and not at persistence level

Since the `leftOperand` is an `id` at odrl level the output should reflect this when serialized with `odrl:prefix`
