### ISSUE TITLE
Management API: add workflow to assert version bump

### ISSUE THREAD

**Issue by paullatzelsperger** [eclipse-edc/Connector#4182]
## WHAT
add a GitHub workflow that checks that the version information file (#4181) was changed if a Management API module changed. 

## WHY
Every change to the API must increment the version. 

## HOW
One way could be a workflow that is only triggered on changes within `extensions/control-plane/api/managment-api` directory, and that inspects the PR's changeset if it contains the `version.json` file

**Comment by ndr-brt** [comment]
could the job based on the generated `openapi` file instead? otherwise any change to any other file could cause the version to change, but that shouldn't be the case.
It could be compared with the one in the `gh-pages` branch
