### ISSUE TITLE
Bump all Management API endpoints to `/v3`

### ISSUE THREAD

**Issue by paullatzelsperger** [eclipse-edc/Connector#4208]
## WHAT

To achieve API consistency, we should bump the version of every Management API Endpoint to `/v3`

## WHY

currently we have some `/v2` endpoints, some `/v3` endpoints and some are unversioned. We should have this consistent.

## HOW

All controllers, that are currently available under `/v2` or with no versioning will remain so for compatibility and will be deprecated, but will also be available under `/v3`.

**Comment by ndr-brt** [comment]
@paullatzelsperger I think `data-plane-selector-api` slipped through the cracks, it also needs to be bumped to v3

**Comment by paullatzelsperger** [comment]
> @paullatzelsperger I think `data-plane-selector-api` slipped through the cracks, it also needs to be bumped to v3

the previous PR (bumping the API controllers), and this one only relate to the management API

**Comment by paullatzelsperger** [comment]
> @paullatzelsperger I think `data-plane-selector-api` slipped through the cracks, it also needs to be bumped to v3

yep, thanks for noticing!

**Comment by paullatzelsperger** [comment]
closed as the last PR was also merged.
