### ISSUE TITLE
Duplicate entry for participantId in the CatalogResponse

### ISSUE THREAD

**Issue by domreuter** [eclipse-edc/Connector#4231]
# Feature Request

## Which Areas Would Be Affected?

CatalogResponse -> CatalogProtocolServiceImpl

## Why Is the Feature Desired?

Actually there are duplicates of the participantId present in the catalogResponse.

 1. "dspace:participantId": "BPNPROVIDER" which expands to  "https://w3id.org/dspace/v0.8/participantId": "ProviderId"
 2. "participantId": "BPNPROVIDER" which expands to "https://w3id.org/edc/v0.0.1/ns/participantId": "ProviderId"
 
Option 2 is marked as deprecated since "0.5.1" so cleanup the participantId from the properties might be a good option.
 
## Solution Proposal

Small refactoring to remove the deprecated field to go with the participantId coming from dspace context.

At the same time i am volunteering for providing the PR to fix this.

**Comment by ndr-brt** [comment]
hey, there's a specific policy for deprecations cleanup, and we do that after every "milestone" release, so this cleanup will happen in a pair of milestones or so.

**Comment by domreuter** [comment]
Any hint where that policy can be found?

Just let me know whenever there can be something done from our side.

**Comment by ndr-brt** [comment]
this was never been carved into a DR, given that we're still in a "incubating" phase, we currently do not support older versions generally (https://github.com/eclipse-edc/docs/blob/main/developer/releases.md#towards-a-first-release), the deprecation thing is just an helper for the users to get the new versions in a smoother way.
In this case, given that we are referring to the DSP apis (that are not under our control but we're implementing existing specs) we could just drop that field, but keeping a deprecation for some months doesn't cost anything, so...
