### ISSUE TITLE
TitaniumJsonLd context caching loads document on every call

### ISSUE THREAD

**Issue by ricardas-buc** [eclipse-edc/Connector#4232]
# Bug Report

## Describe the Bug

A mixup of orElse VS orElseGet causes document to be loaded every time, even though cache is being hit.

https://github.com/eclipse-edc/Connector/blob/564d6270bb32ea751e206461be8f2c1c01dfce24/core/common/lib/json-ld-lib/src/main/java/org/eclipse/edc/jsonld/TitaniumJsonLd.java#L199-L200

### Expected Behavior

Cached document should not be loaded again.

## Context Information

- Used version EDC 0.7

## Detailed Description

_If applicable, add screenshots and logs to help explain your problem._

## Possible Implementation

Switching to orElseGet solves the issue. This does save extra 2-5ms per execution.

**Comment by ndr-brt** [comment]
thanks for reporting, would you like to provide a PR to provide this enhancement?

**Comment by ricardas-buc** [comment]
I would not agree that it is not a bug, document cache is not being properly utilized :) In any case it should be a simple fix:

```java
            var document = Optional.ofNullable(documentCache.get(uri));
            if (document.isEmpty()) {
                return loader.loadDocument(uri, options);
            }
            return document.get();
```

using orElseGet would require additional code to handle `JsonLdError` exception, but this way it is rather straightforward. If PR is still required, then this will have to wait, not enough resources on my end for it to happen this week.

**Comment by ndr-brt** [comment]
@ricardas-buc no worries, a PR has been already opened for this enhancement
