### ISSUE TITLE
Control Plane does not check asset id when initiating transfer process

### ISSUE THREAD

**Issue by bscholtes1A** [eclipse-edc/Connector#4240]
# Bug Report

## Describe the Bug

The request for initiating a transfer process contains an `assetId` and a `contractId` field. The `contractId` points to a contract agreement, which itself contains an asset id. 

No check is performed in order to asset that the asset id passed in the request matches the one defined in the contract agreement. 

If there is a mismatch, this results in an inconsistency in the Endpoint Data Reference that is generated. 

### Expected Behavior

Control Plane should return a validation error if the `assetId` in the request does not match the one defined in the contract agreement. 

### Observed Behavior

No error is returned, and an inconsistent Endpoint Data Reference is generated.

## Steps to Reproduce

Initiate a transfer process through the control plane management API, and use a random `assetId` in the request instead of the one stored in the contract.

**Comment by ndr-brt** [comment]
Yes, I also think that the `assetId` property is definitely not needed on `TransferRequest`, because the `assetId` can be obtained by the `ContractAgreement` as you said.
Related to that, I think that the `contractId` is not validated too.
