### ISSUE TITLE
Missing transformer in data-plane-selector-control-api

### ISSUE THREAD

**Issue by timdah** [eclipse-edc/Connector#4245]
# Bug Report

## Describe the Bug

The `getAllDataPlaneInstances` endpoint throws a 500 because the `DataPlaneInstance --> JsonObject` transformer is not registered.

https://github.com/eclipse-edc/Connector/blob/6e7bb67dfbd08d5a41300af15db2688691a3017a/extensions/data-plane-selector/data-plane-selector-control-api/src/main/java/org/eclipse/edc/connector/dataplane/selector/control/api/DataplaneSelectorControlApiController.java#L103-L113

https://github.com/eclipse-edc/Connector/blob/6e7bb67dfbd08d5a41300af15db2688691a3017a/extensions/data-plane-selector/data-plane-selector-control-api/src/main/java/org/eclipse/edc/connector/dataplane/selector/control/api/DataplaneSelectorControlApiExtension.java#L58-L66

## Context Information

- EDC 0.7.0

## Possible Implementation

I see two possible solutions:

1. Register the transformer
2. Delete the endpoint, as this is a duplicate of the only endpoint (at least in V3) in the `data-plane-selector-api` extension.
https://github.com/eclipse-edc/Connector/blob/6e7bb67dfbd08d5a41300af15db2688691a3017a/extensions/data-plane-selector/data-plane-selector-api/src/main/java/org/eclipse/edc/connector/dataplane/selector/api/v3/DataplaneSelectorApiV3Controller.java#L32-L56

**Comment by ndr-brt** [comment]
I vote solution 1, deletion is not correct, because `control` and `management` context should be kept separated as they serve separate needs, so this duplication is accepted (and I'll say needed) tho.

**Comment by paullatzelsperger** [comment]
also, generally we shouldn't just remove endpoints without deprecating them first.
