### ISSUE TITLE
EndpointDataReferenceEntry: null check for providerId refers to the wrong message

### ISSUE THREAD

**Issue by domreuter** [eclipse-edc/Connector#4250]
Hi there,

the null check for providerId will give the wrong validation message. Actually it is pointing to `transferProcessId` but should be `providerId`.

`Objects.requireNonNull(((EndpointDataReferenceEntry)this.entity).providerId, "transferProcessId");`

https://github.com/eclipse-edc/Connector/blob/893296628a643154cb8811038c06e14c3483f739/spi/common/edr-store-spi/src/main/java/org/eclipse/edc/edr/spi/types/EndpointDataReferenceEntry.java#L121C13-L121C68

**Comment by wolf4ood** [comment]
Hi @domreuter 

thanks for raising this, Do you plane to provide a PR on this or are you working on this?

Otherwise i can quickly fix it

Thanks

**Comment by domreuter** [comment]
Hi @wolf4ood ,

i will try to provide the PR

Thanks for the quick reply.

**Comment by wolf4ood** [comment]
Thanks :+1:
