### ISSUE TITLE
Enhancing debug information for HttpDataSource transfers

### ISSUE THREAD

**Issue by zub4t** [eclipse-edc/Connector#4280]
# Feature Request

Currently, when the `openPartStream` method on `HttpDataSource` is called, if the transfer fails the reason for this failure is not logged. Providing information about why a transfer fails or when it succeeds would improve the maintenance of the connector.

## Which Areas Would Be Affected?

transfer

## Why Is the Feature Desired?

When multiple users are using the same connector, there is sometimes a necessity to reply to support tickets. If there is no logging of the reasons for transfer failures, it becomes difficult to provide effective support services.
## Solution Proposal

```Java
 if (response.isSuccessful()) {
             ...
            monitor.debug("transfer successes");
            } else {
                try {
                    monitor.debug("transfer fails with status code: "+response.code() );
                    if (NOT_AUTHORIZED == response.code() || FORBIDDEN == response.code()) {
                        return StreamResult.notAuthorized();
                    } else if (NOT_FOUND == response.code()) {
                        return StreamResult.notFound();
                    } else {
                        return error(format("Received code transferring HTTP data: %s - %s.", response.code(), response.message()));
                    }
                   ...

```

**Comment by jimmarino** [comment]
Stacktraces for requests against internal systems should not be forwarded for security reasons. This can be handled by logging the request failure at the backend and correlating it.

**Comment by zub4t** [comment]
Therefore, is it  not possible to record the request failure in the EDC without forwarding the response to the caller? If we can do this, it would allow for better troubleshooting in cases where access to the backend system logs is unavailable.

**Comment by jimmarino** [comment]
No, we explicitly do not want to do that due to concerns about logging potentially private data.

**Comment by gerbigf** [comment]
Hey @jimmarino  - fully understood. Could we at least add a log statement that tells us if the request to the backend was (un-)successful and with which status code? I know that the partner receives this information, but it helps us to trace the error down ourselves and have a complete log trace. Neither do we as the EDC Ops team or our users always have access to the logs of the backend API, nor does our partner always provide us with the full response. 

Knowing if it was e.g. a 404 or 403 already would help, even without getting the complete error message.

**Comment by jimmarino** [comment]
That is already done so it should allow you to track it down

**Comment by gerbigf** [comment]
I'm not sure if that works as intended - in our scenario neither there's a log message of any type, nor a proper response message to the partner EDC  We're working on reproducing the issue and will open a separate issue if we can reproduce.

**Comment by jimmarino** [comment]
Ok

**Comment by ndr-brt** [comment]
the error detail with the status code should be stored in the `DataFlow` object when it transition to `failed`.
The problem here is that it stores the `failure.getFailureDetail()`, that could be empty if there's no message in the failure.
That seems to be the case according to the code posted in the issue:
```java
if (NOT_AUTHORIZED == response.code() || FORBIDDEN == response.code()) {
                        return StreamResult.notAuthorized();
                    } else if (NOT_FOUND == response.code()) {
                        return StreamResult.notFound();
                    } else {
```

I see different solutions:
- avoid "empty message" failures
- make the `transitionToFailed` accept a `Failure` as argument and put as errorDetail a string representation of the `Failure`, that, for the `StreamFailure` case will contain the `reason` as well
- make the `DataPlaneManager` to appent the `reason` to the message that will be stored in the database.

I'd say that the second one is my favurite: passing the `Failure` object around instead of having `String` will make the code more expressive (and less primitive-obsessed).

**Comment by zub4t** [comment]
Good 😊
@jimmarino or @ndr-brt can you assign this issue to me?
