### ISSUE TITLE
Bug: Failed to run tests with EdcRuntimeExtension on Windows OS

### ISSUE THREAD

**Issue by ieuna** [eclipse-edc/Connector#4285]
# Bug Report

## Describe the Bug
Passing 0 argument to "modules"(type: varagrs) parameter to EdcRuntimeExtension constructor results in failed tests on Windows OS. EdcRuntimeExtension fails to resolve class path on Windows.
It works on Linux.
![image](https://github.com/eclipse-edc/Connector/assets/161810204/bba87c35-269a-483d-9bb2-3b9455428065)

### Expected Behavior

Passing no arguments to "modules" parameter to EdcRuntimeExtension constructor should not cause any issue on Windows OS since the argument type is varargs.

### Observed Behavior

Failed tests:
![image](https://github.com/eclipse-edc/Connector/assets/161810204/e900350d-4adf-44ff-904e-aff49c8182cd)

StackTrace:
![StackTrace](https://github.com/eclipse-edc/Connector/assets/161810204/aef2c8ae-3cc2-4241-88f0-ec6330df763a)

Passing an empty string to "modules" parameter fixes the problem on Windows.
## Steps to Reproduce

1. While creating EDCRuntimeExtension, do not pass third parameter.
```
@RegisterExtension
EdcRuntimeExtension RUNTIME = new EdcRuntimeExtension(
		"name",
		Map.of(....)
);
```
2. Run tests with gradle on Windows: 
```./gradlew clean test```
4. See test report

## Context Information
- EDC version- 0.7.0
- OS: Windows
- Java version- 21
- Gradle- 8.6

## Detailed Description

Tests are not running because EdcRuntimeExtension fails to read class path if "modules" is an empty array.
![image](https://github.com/eclipse-edc/Connector/assets/161810204/4acf027c-8f7f-499a-b822-a64970720b5e)

**Comment by paullatzelsperger** [comment]
@ieuna We don't support native Windows as base OS, typically what people do is run the tests on WSL, or a linux VM. MacOS works too.

You're welcome to contribute a fix (that doesn't break stuff anywhere else!) though.
