### ISSUE TITLE
Permit `ConsoleMonitor` level configuration

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-edc/Connector#4392]
# Feature Request

Currently it's not possible to configure the output level of the default `ConsoleMonitor` instance. The constructor is called without passing the `level`, that by default is `DEBUG`:
https://github.com/eclipse-edc/Connector/blob/8d259e911f2edef8fb036f515588b9b9e9030d16/core/common/boot/src/main/java/org/eclipse/edc/boot/system/ExtensionLoader.java#L92

this should be configurable through command line arguments (preferred, as they are already used to configure it) or system properties.

## Which Areas Would Be Affected?

_e.g., DPF, CI, build, transfer, etc._

## Why Is the Feature Desired?

_Are there any requirements?_

## Solution Proposal

_If possible, provide a (brief!) solution proposal._

**Comment by rafaelmag110** [comment]
@ndr-brt I'm curious to understand the rational behind creating this issue as a "Feature Request" and not as a "Bug". Could you help me understand this so I can consider similar reasoning in the future?

**Comment by ndr-brt** [comment]
> @ndr-brt I'm curious to understand the rational behind creating this issue as a "Feature Request" and not as a "Bug". Could you help me understand this so I can consider similar reasoning in the future?

This does not affect the any connector functionality, there aren't any unexpected exception thrown or broken flows.
This is a nice definition of a "non-bug" thing.
Plus, for what I saw in the code the level configuration has never been implemented (there's no test describing it), so it's definitely a missing feature

> I can provide my view on why I would see this as a bug: The console monitor has been around for a while and the ability to configure the log level was taken as a feature. I believe this is the case because downstream projects include this configuration in helm charts, and it was even considered a solution to an issue that appeared in one of the downstream projects. Hence my confusion.

if you are referring to TractusX-EDC, there's no such configuration in helm charts, also because it does not exist in the upstream, [all the things under the `logging` block](https://github.com/eclipse-tractusx/tractusx-edc/blob/main/charts/tractusx-connector/values.yaml#L330-L336) look to be a naive copy-and-paste from the old project that nobody ever touched since.
Curious how nobody discovered this in more than a year.

> Why I care about the distinction? Upstream doesn't support older versions unless there is a serious security problem, however downstream projects might and I could see the discussion around if this is feature or bug happen.

Downstream projects could (and likely they) have a complete different development cycle/teams/perspective so what here's a missing feature, for somebody else could be a bug, but, luckily, EDC is flexible enough and, for example, this log filter feature could be easily implemented downstream with a simple `MonitorExtension`.

**Comment by rafaelmag110** [comment]
Understood, thanks for your explanation.
Nevertheless, can you assign this to me? I can contribute with a PR.
