### ISSUE TITLE
Extract a `PolicyPreValidator` and a `PolicyPostValidator` interface

### ISSUE THREAD

**Issue by wolf4ood** [eclipse-edc/Connector#4446]
proposal for a subsequent refactoring: to extract a `PolicyPreValidator` and a `PolicyPostValidator` interface, to hide that `BiFunction<Policy, PolicyContext, Boolean>` not really readable

_Originally posted by @ndr-brt in https://github.com/eclipse-edc/Connector/pull/4442#discussion_r1738027526_

**Comment by bmg13** [comment]
hey @wolf4ood can you assign this to me please? :)

**Comment by bmg13** [comment]
Oh okay, was unaware, created a draft pr since saw this issue around 😅 nevermind, will close it, thanks @wolf4ood !
