### ISSUE TITLE
feat: add `dcterms:issued` and `dcterms:modified` properties in `Dataset` catalog output

### ISSUE THREAD

**Issue by bscholtes1A** [eclipse-edc/Connector#4472]
# Feature Request

In the catalog output, we need to know the issuance date and last modification date for each `dcat:Dataset`. 
These are covered by [`dcterms:issued`](https://www.w3.org/TR/vocab-dcat-3/#Property:resource_release_date) and [`dcterms:modified`](https://www.w3.org/TR/vocab-dcat-3/#Property:resource_update_date fields) of the  `dcat:Resource`, from which `Dataset` is a child class.

## Which Areas Would Be Affected?

`Entity` related stores and mapping.

## Why Is the Feature Desired?

Know first issuance and last modification date of each dataset. 

## Solution Proposal

Add and populate `modifiedAt` field in `Entity` class.

**Comment by jimmarino** [comment]
I don't think these should be put in a dataspace-specific extension, not in the EDC. Can't this be implemented using an event subscriber and updating the asset with a custom property?
