### ISSUE TITLE
Optimize Catalog-Endpoint Performance

### ISSUE THREAD

**Issue by efiege** [eclipse-edc/Connector#4499]
# Feature Request

The performance of the Catalog-Endpoint degrades as the number of `ContractDefinitions` increases. This appears to be due to an n+1 query issue within the `ContractDefinitionResolverImpl`. Currently, for each `ContractDefinition`, the corresponding access policy is resolved by its ID, resulting in a separate database query for each policy.

This issue seems to persists in the `main` branch. The relevant code can be found here: 
https://github.com/eclipse-edc/Connector/blob/dfa1be6100ed7037aed03a89badb805044fcc74a/core/control-plane/control-plane-contract/src/main/java/org/eclipse/edc/connector/controlplane/contract/offer/ContractDefinitionResolverImpl.java#L72-L89

## Which Areas Would Be Affected?

- Control-Plane
- PolicyDefinitionStore

## Why Is the Feature Desired?

As the number of `ContractDefinitions` grows, the Catalog-Endpoint experiences significant performance degradation due to the increasing number of database queries.

## Solution Proposal

Implement a database join to retrieve all relevant policies in a single query, reducing the number of queries executed.

**Comment by ndr-brt** [comment]
could you please provide a detailed benchmark trying to highlight after how many contract negotiations the performances start to degrade and what's the time factor?

**Comment by paullatzelsperger** [comment]
I 100% agree with what @ndr-brt said - provide speeds and feeds, otherwise it's all conjecture.

Querying with a `JOIN` will have a widespread impact, because we'd have to introduce a new `ContractDefinition` object, i.e. one that contains `Policy` objects instead of just their IDs. This will also have an impact on all the stores. And even then, I'm very sceptic that it would bring much of an advantage, since connections are pooled, and establishing them is what takes time. Also, databases typically have a cache.

If anything, I would think about a local policy cache, i.e. a `HashMap` that gets lazily populated, and gets evicted after the request.

**Comment by efiege** [comment]
Thank you for your prompt responses.

The performance degradation is not tied to any contract negotiation process, but rather scales with the number of `ContractDefinitions` present in the EDC.

To illustrate this, consider the following example: resolving a policy by its ID from the database takes approximately 1ms. With 100,000 `ContractDefinitions`, a catalog request requires at least 100,000 * 1ms, which translates to a minimum of 100 seconds.

**Comment by paullatzelsperger** [comment]
first, is that an actual measurement? if so, can you share the results? 
second, why are there 100_000 contract definitions? again, is this an actual use case?

like I said, a local policy cache would be a good option, but unless you provide hard facts (not fictitious numbers) there is nothing we can do.

**Comment by ndr-brt** [comment]
> Thank you for your prompt responses.
> 
> The performance degradation is not tied to any contract negotiation process, but rather scales with the number of `ContractDefinitions` present in the EDC.

it was a typo :hand_over_mouth: 

> To illustrate this, consider the following example: resolving a policy by its ID from the database takes approximately 1ms. With 100,000 `ContractDefinitions`, a catalog request requires at least 100,000 * 1ms, which translates to a minimum of 100 seconds.

as we already stated, please provide more details.

(btw: if you have 100.000 definitions, is very likely that you have modeled them in the wrong way. read: the pattern 1 asset/1 policy/1 contract definition is definitely not correct and needs to be avoided)

**Comment by efiege** [comment]
I just wanted to give an example ☺️ 

If I understand correctly, you suggest that the response time for the catalog is acceptable when dealing with a reasonable number of `ContractDefinitions` for typical use cases. 

I don't know what you think is a reasonable number, but even if there are just ~100 `ContractDefinitions` this will reduce the response time by ~100ms.

Wouldn't you agree that there is still potential for optimization here?

**Comment by jimmarino** [comment]
> I just wanted to give an example ☺️
> 
> If I understand correctly, you suggest that the response time for the catalog is acceptable when dealing with a reasonable number of `ContractDefinitions` for typical use cases.
> 
> I don't know what you think is a reasonable number, but even if there are just ~100 `ContractDefinitions` this will reduce the response time by ~100ms.
> 
> Wouldn't you agree that there is still potential for optimization here?

What we are asking for is a benchmark. How do you know the response time will be reduced ~100ms. It certainly may be the case, but on what basis is this asserted?

What is the test case, how was the database and other infrastructure configured, and what were the actual numbers? Did you profile the behavior? What bottlenecks were observed?

**Comment by richardtreier** [comment]
Guys, I believe we do not need a benchmark to understand that any N+1 select problem on a highly used and visited endpoint such as the catalog, that scales over any of the EDC entities, is an issue.

I understand the challenges the EDC faces with its design decision to split the stores with accessing even its own DB. I believe we can still find a good solution by using batched DB queries The following is a common pattern I have met in many JPA code bases, as JPA code bases also often face N+1 select issues:

```java

var policyIds = contractDefinitions.stream()
    .map(it -> it.getPolicyId())
    .collect(toSet());
var policiesById = policyService.findByIdIn(policyIds).stream()
    .collect(toMap(it -> it.getId(), Function.identity()))

return contractDefinitions.stream()
    .map(contractDefinition -> {
        var policy = policiesById.get(contractDefinition.getPolicyId());
        return buildContractOffer(contractDefinition, policy);
    })
    .toList();
```

Trying to change EDC usage also does not help here:
- In cloud environments even the smallest DB query might take 24ms - 32ms.
- In terms of quantity structure, even with optimized EDC usage, we have seen:
  - Transfers have easily hundreds of thousands.
  - Hundreds of individual data offers with individual policies on a brokering EDC connecting a data marketplace platform with an EDC dataspace

**Comment by paullatzelsperger** [comment]
> Guys, I believe we do not need a benchmark to understand that any N+1 select problem on a highly used and visited endpoint such as the catalog, that scales over any of the EDC entities, is an issue.

Three committers disagree with you and are in agreement that we do need a benchmark and hard facts.

> I believe we can still find a good solution 

one has been offered, in the form of a local policy cache.

> The following is a common pattern I have met in many JPA code bases,

This is not JPA. 

> In cloud environments even the smallest DB query might take 24ms - 32ms.

measurements? benchmarks? timing results? what does the deployment situation look like? is this geo-colocated? is database caching enabled? also, it is likely the connection establishment that takes time, and connections are pooled. 

> Transfers have easily hundreds of thousands.

this has nothing to do with offers

To be honest, this is starting to annoy me. We have asked for profound data, which you seem incapable of or unwilling to provide. We even offered a solution, that would alleviate this supposed problem, while keeping our entity data model intact. 

It seems I have to be blunt: unless you clearly demonstrate a problem, supported by hard facts, we will not invest any more time in this.

**Comment by ndr-brt** [comment]
Other than agreeing with @paullatzelsperger , taking a look at the code, from a "simplicity" point of view, I see that the `ContractDefinitionResolver` could be inlined into `DatasetResolverImpl`, other than simplify the design, it **would** permit also to add a thread local cache that would avoid multiple policy fetch in the case that multiple contract definitions use the same policies for access/contract scopes (that, I guess is really likely what happens).

I like the ids idea brought by @richardtreier but, really, we need data to take a decision that will impact countless adopters

**Comment by paullatzelsperger** [comment]
> it would permit also to add a thread local cache that would avoid multiple policy fetch in the case that multiple contract definitions use the same policies for access/contract scopes (that, I guess is really likely what happens).

that was exactly my point.

**Comment by paullatzelsperger** [comment]
@richardtreier thanks for your efforts, but it goes without saying that we will require those numbers based on `0.9.0`, ideally `0.10.0-SNAPSHOT`. No point in profiling or debugging an  ancient and thus unsupported version.

**Comment by efiege** [comment]
Awesome, thanks for incorparating those changes!
