### ISSUE TITLE
Unexpected context for DID documents

### ISSUE THREAD

**Issue by perher** [eclipse-edc/Connector#4501]
# Bug Report

## Describe the Bug
When performing a did:web resolution call towards Identity Hub it returns a DID document with `https://w3id.org/did-resolution/v1` context but expected it to be: `https://www.w3.org/ns/did/v1`.

### Expected Behavior
When returning a DID document it is expected that it follows the Decentralized Identifiers (DIDs) v1.0 specification.

### Observed Behavior
The current `https://w3id.org/did-resolution/v1` context as specified https://github.com/eclipse-edc/Connector/blob/main/spi/common/identity-did-spi/src/main/java/org/eclipse/edc/iam/did/spi/document/DidDocument.java#L31 is for "Decentralized Identifier Resolution (DID Resolution)" see https://w3c.github.io/did-resolution/#example

## Steps to Reproduce

1. Start MVD sample
2. Query did document with `curl http://localhost:7093/.well-known/did.json`. 
3. Observe that following document is returned
```
{
  "service": [
    {
      "id": "provider-credentialservice-1",
      "type": "CredentialService",
      "serviceEndpoint": "http://localhost:7091/api/presentation/v1/participants/ZGlkOndlYjpsb2NhbGhvc3QlM0E3MDkz"
    },
    {
      "id": "provider-catalogserver-dsp",
      "type": "ProtocolEndpoint",
      "serviceEndpoint": "http://localhost:8092/api/dsp"
    }
  ],
  "verificationMethod": [
    ...
  ],
  "authentication": [],
  "id": "did:web:localhost%3A7093",
  "@context": [
    "https://w3id.org/did-resolution/v1"
  ]
}
```

## Context Information
EDC version 0.10.0-SNAPSHOT

**Comment by paullatzelsperger** [comment]
@perher thanks for reporting. Do you want to create a PR for this?

**Comment by perher** [comment]
sure, I created a PR for this now
