### ISSUE TITLE
Policy model rightOperand can't handle list of literal values

### ISSUE THREAD

**Issue by gkirtzou** [eclipse-edc/Connector#4525]
# Bug Report

## Describe the Bug

Create  a policy that contains a list of literals as rightOperand in a constraint as the following:
```
{
    "@context": {
        "@vocab": "https://w3id.org/edc/v0.0.1/ns/",
        "edc": "https://w3id.org/edc/v0.0.1/ns/",
        "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
        "dcat": "http://www.w3.org/ns/dcat#",
        "xsd": "http://www.w3.org/2001/XMLSchema#",
        "foaf": "http://xmlns.com/foaf/0.1/",
        "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
        "adms": "http://www.w3.org/ns/adms#",
        "dcmitype": "http://purl.org/dc/dcmitype/",
        "skos": "http://www.w3.org/2004/02/skos/core#",
        "dct": "http://purl.org/dc/terms/",
        "odrl": "http://www.w3.org/ns/odrl/2/",
        "owl": "http://www.w3.org/2002/07/owl#",
        "cc": "http://creativecommons.org/ns#",
        "dalicc": "https://dalicc.net/ns#",
        "dalicclib": "https://dalicc.net/licenselibrary/",
        "osl": "http://opensource.org/licenses/",
        "prov": "http://www.w3.org/ns/prov#",
        "spdx": "http://spdx.org/rdf/terms#",
        "example": "http://www.example.com/"
    },
    "policy": {
        "@type": "odrl:Set",
        "dct:description": {
            "@language": "en",
            "@value":"Connector Restricted Usage"
        },
        "dct:title": {
            "@language": "en",
            "@value": "Connector Restricted Usage"
        },
        "odrl:permission": [
            {
                "@type": "odrl:Permission",
                "odrl:action": {
                    "@id": "odrl:use"
                },
                "odrl:constraint" : {
                    "@type" : "odrl:Constraint",
                    "odrl:rightOperand" : ["https://www.connector1.com", "https://www.connector2.com"],
                    "odrl:leftOperand" : {
                      "@id" : "odrl:systemDevice"
                    },
                    "odrl:operator" : {
                      "@id" : "odrl:isAnyOf"
                    }
                }
            }
        ],
        "odrl:obligation": null,
        "odrl:prohibition": null
    }
}

```
### Expected Behavior

Retrieve the policy,  where the odrl:rightOperand is a list of the provided values, similar to the one provided when creating the policy. 

### Observed Behavior
When retrieving the above create policy we get the following. Please note how odrl:rightOperand is returned
```
{
    "@id": "feea67e9-784a-4f86-83aa-02b17e95bdb1",
    "@type": "PolicyDefinition",
    "createdAt": 1727873504339,
    "policy": {
        "@id": "0614de32-3202-4bd0-8ef2-1031fa29a95d",
        "@type": "odrl:Set",
        "odrl:permission": {
            "odrl:action": {
                "@id": "odrl:use"
            },
            "odrl:constraint": {
                "odrl:leftOperand": {
                    "@id": "odrl:systemDevice"
                },
                "odrl:operator": {
                    "@id": "odrl:isAnyOf"
                },
                "odrl:rightOperand": "[{@value={valueType=STRING, chars=https://www.connector1.com, string=https://www.connector1.com}}, {@value={valueType=STRING, chars=https://www.connector2.com, string=https://www.connector2.com}}]"
            }
        },
        "odrl:prohibition": [],
        "odrl:obligation": []
    },
    "@context": {
        "@vocab": "https://w3id.org/edc/v0.0.1/ns/",
        "edc": "https://w3id.org/edc/v0.0.1/ns/",
        "lds": "https://lds.eu/",
        "omtd": "http://w3id.org/meta-share/omtd-share/",
        "odrl": "http://www.w3.org/ns/odrl/2/",
        "ms": "http://w3id.org/meta-share/meta-share/",
        "euvoc_auth": "http://publications.europa.eu/resource/authority/",
        "owl": "http://www.w3.org/2002/07/owl#",
        "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
        "dcat": "http://www.w3.org/ns/dcat#",
        "xsd": "http://www.w3.org/2001/XMLSchema#",
        "foaf": "http://xmlns.com/foaf/0.1/",
        "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
        "adms": "http://www.w3.org/ns/adms#",
        "loc": "http://id.loc.gov/vocabulary/iso639-1/",
        "dcmitype": "http://purl.org/dc/dcmitype/",
        "skos": "http://www.w3.org/2004/02/skos/core#",
        "iana": "http://www.iana.org/assignments/media-types/application/",
        "dct": "http://purl.org/dc/terms/",
        "schema": "https://schema.org/"
    }
}
```

## Context Information
EDC seems to support the representation of set operators. However, when a set operator is used, ODRL models expects odrl:rightOperant to be 

>  "for set-based operators; list of literals, or list of IRIs [[rfc3987](https://www.w3.org/TR/odrl-model/#bib-rfc3987)], or list of RightOperands;"

(from https://www.w3.org/TR/odrl-model/#constraint) .

The error probably comes from EDC implementation of the Expressions as a single literal value. 
Any plans to support list of literal values, in order to support set operators representation? Or is the above policy representation wrong and EDC expect the input somehow different?

Thanks is advance

**Comment by jimmarino** [comment]
Complex types are not currently supported. The core policy evaluator can handle complex types, but a number of considerations would need to be taken into account. The most important is that JSON-LD expands properties into array structures, so it is not possible to reliably determine if a type is a scalar value or an array of types.

The code that would need to be modified is `JsonObjectToConstraintTransformer.extractComplexValue(JsonValue root)`. Leaving aside the JSON-LD issue, the code would need to return the deserialized Map, List, or scalar values.

This is a feature that requires investigation, and barring a proposal and subsequent PR, I don't think will get priority.

**Comment by gkirtzou** [comment]
Thanks for the clarification and I hope to get resolved at some point, as it is limiting the possible policies that a dataspace can use, if we cannot represent them with EDC to be used in order to make an offer. 

You mentioned that the core policy evaluator can handle complex types, meaning lists of literals like the one above? I haven't checked the policy evaluator, my initial focus was to check what policies I could represent within EDC, as my understanding was that the policy evaluator evaluates the policy that comes from a specific contract, which are based policies (aka odrl:sets) that are stored within EDC and have been used in offers. Do I miss something?

**Comment by jimmarino** [comment]
Look at the method I pointed to in my previous post. The best way to prioritize this is to submit a proposal and subsequent PR.
