### ISSUE TITLE
`Consumer-Asset` with the same ID as a `Provider-Asset` Cannot Be Deleted After Contract Negotiation

### ISSUE THREAD

**Issue by efiege** [eclipse-edc/Connector#4583]
# Bug Report

## Describe the Bug

After a `Contract` for an `Asset` of a `Provider` has successfully been negotiated,  an `Asset` reciding at the `Consumer` with the same ID and not being part of a Contract, can not be deleted anymore.

### Expected Behavior

`Asset` can be deleted, because it has not been part of a contract.

### Observed Behavior

`Asset` can't be deleted.

## Steps to Reproduce

1. Create and negotiate a `Contract` for `Asset-A` reciding at the `Provider`
2. Create `Asset-B` with the same ID as `Asset-A` at the `Consumer`
3. Try to delete `Asset-B` using the Management-API

## Context Information

- Used version: `v0.7.2`

## Possible Implementation

Query just for `Assets` with `ContractNegotations` of type `PROVIDER` in the `AssetServiceImpl`.

https://github.com/eclipse-edc/Connector/blob/d708305568eed6061bacc4dfaf3594e9837320dd/core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/controlplane/services/asset/AssetServiceImpl.java#L94-L102

**Comment by ndr-brt** [comment]
This should never happen because the identifier of the dataset (asset)
> is a text string which is assigned to the resource to provide an unambiguous reference within a particular context.

([ref.](https://www.w3.org/TR/vocab-dcat-3/#Property:resource_identifier))

this is an edge case that won't get prioritized, but we're open to contributions in form of PR.

**Comment by SebastianOpriel** [comment]
Thanks @ndr-brt for clarification. Yes, we will take care of fixing it and provide a PR.
@ununhexium @AbdullahMuk
