### ISSUE TITLE
Make ContractAgreement duration configurable

### ISSUE THREAD

**Issue by DominikPinsel** [eclipse-edc/Connector#722]
At the time of writing there is still some placeholder code for the duration of contract agreements. I assume the default duration of contracts should be configurable in the `ContractDefinition`.

<sub>Dominik Pinsel <dominik.pinsel@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md) </sub>

**Comment by algattik** [comment]
Would this be in the ContractDefinition? In the Policy? In a pluggable service?

**Comment by bscholtes1A** [comment]
Hi @jimmarino 
as just discussed, how can we move on concerning that issue?

**Comment by dheerajbhargava** [comment]
@jimmarino @DominikPinsel 
Can we prioritise this as we need it for our feature release??
