### ISSUE TITLE
Document DAPS integration

### ISSUE THREAD

**Issue by DominikPinsel** [eclipse-edc/Connector#799]
Currently it is not documented how an IDS connector can be configured to use a certain IDS DAPS. Without written documentation this is a very difficult task to do for everybody who isn't a developer. Therefore I assume it would be a good thing to add this documentation to `/docs/ids`.

<sub>Dominik Pinsel <dominik.pinsel@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md) </sub>

**Comment by juliapampus** [comment]
@ronjaquensel is already working on that: https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/pull/760.

**Comment by juliapampus** [comment]
I followed her documentation and I think this is a huge improvement. She even added details on how to setup an IDS DAPS locally.

**Comment by DominikPinsel** [comment]
@juliapampus  Oh, sorry I didn't see that. Really great work. I will close this issue then.
