### ISSUE TITLE
DataPlaneFramework: add documentation

### ISSUE THREAD

**Issue by paullatzelsperger** [eclipse-edc/Connector#833]
For the DPF we should have the following developer documentation items showing how to 
- set up a DPF runtime
- configure an EDC so that it can communicate with the DPF
- develop your first `DataSource` and `DataSink`

In addition, creating Youtube videos will greatly aid understanding.

**Comment by MoritzKeppler** [comment]
Would be great also to have documentation for which scenarios the dataplane framework is a suitable solution, so especially document limitations.

**Comment by jimmarino** [comment]
Closing this as some items have been done and others are wish list items.
