### ISSUE TITLE
DPF Test and Sample Updates

### ISSUE THREAD

**Issue by zeier** [eclipse-edc/Connector#902]
## Description

Samples and tests currently use the `InlineDataFlowController`, which was a temporary solution until the Data Plane Framework was in place.

Issue #871 will use the `HttpDataFlowController` to perform communication between the Control Plane and the Data Plane.

The goal of this issue is to adapt samples and tests to use the Data Plane and validate that end to end observability works as expected.

## Acceptance Criteria

- [ ] Usage of `InlineDataflowController` is replaced by the `HTTPDataFlowController`
- [ ] Samples and system tests leverage the Data Plane for data transfer
- [ ] Existing samples can be used to show end to end observability (distributed tracing) for data transfers where both the Control Plane and the Data Plane are involved
- [ ] Test are available for both Azure Object Storage extensions (integration test for the simple data transfer and system test for Azure D) and can be used to show end to end observability (distributed tracing) for data transfers where both the Control Plane and the Data Plane are involved

**Comment by zeier** [comment]
@bscholtes1A is my understanding correct that you will cover this issue as part of your ongoing work? 
If not, please let me know and we can coordinate accordingly.

**Comment by bscholtes1A** [comment]
> @bscholtes1A is my understanding correct that you will cover this issue as part of your ongoing work? If not, please let me know and we can coordinate accordingly.

Hi @zeier 
I will tackle the creation of the Control Plane client that delegates the work to the DPF and the possibility to have the DPF embedded within the Control Plane runtime (which will be the config used in the samples...)
However I did not plan to update the samples by myself as there are still a lot to do on the DPF for this milestone.

**Comment by zeier** [comment]
> 

Hi @bscholtes1A 
OK, could you please ping us when you have your changes in, so that we can update the samples?

**Comment by bscholtes1A** [comment]
> > 
> 
> Hi @bscholtes1A OK, could you please ping us when you have your changes in, so that we can update the samples?

As soon as #988 is merged
