### ISSUE TITLE
Pass EndpointDataReference to endpoint specific to DataTransferProcess

### ISSUE THREAD

**Issue by MoritzKeppler** [eclipse-edc/Connector#922]
# Feature Request
The `EndpointDataReferenceHandler` passes an `EndpointsDataReference` to receiver - currently to `HttpEndpointDataReferenceReceiver` which then sends the information to a preconfigured http endpoint (e.g. to a backend application).
We expect to have more than one backend application, therefore we need  a way to specifiy this endpoint per DataTransferRequest.

## Which Areas Would Be Affected?
DPF

## Solution Proposal
Maybe pass callback endpoint details as part of `TransferRequestDto` and store in the `TransferProcess`/`DataRequest`.

## Type of Issue
improvement

**Comment by florianrusch-zf** [comment]
@jimmarino do you have already started with the implementation for this issue? If not, it would maybe better do move it again into the backlog or not? Currently it's in the state `In progress`

**Comment by florianrusch-zf** [comment]
A preparation for this issue was already merged ([event framework ](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/pull/1587)). We now just need a possibility to register multiple callbacks, which will be called by a listener.

**Comment by jimmarino** [comment]
Closing as the new callback feature enables this.
